#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	_hbpcreg.c \
	chartabs.c \
	pcrecomp.c \
	pcreconf.c \
	pcredfa.c \
	pcreexec.c \
	pcrefind.c \
	pcrefinf.c \
	pcreget.c \
	pcreinfo.c \
	pcremktb.c \
	pcrenewl.c \
	pcreoutf.c \
	pcrerefc.c \
	pcrestud.c \
	pcretabs.c \
	pcretryf.c \
	pcrever.c \
	pcrevutf.c \
	pcrexcls.c \

LIBNAME=hbpcre

include $(TOP)$(ROOT)config/lib.cf
