// Office example 'sheet2'
// From \contrib\hboffice\tests
// ..\..\..\bin\win\mingw64\hbmk2 sheet2.prg hboffice.hbc -comp=mingw64
// ../../../bin/linux/gcc/hbmk2 sheet2.prg hboffice.hbc
#include "hboffice.ch"

REQUEST HB_CODEPAGE_PTISO
REQUEST HB_LANG_PT_BR

***********************************
STAT FUNCTION FULL_PATH( C_FileName )
***********************************
#if defined(__PLATFORM__WINDOWS) || defined(__PLATFORM__Windows)
    return DiskName() + ":\" + CurDir() + "\result\" + C_FileName
#else
    return "/" + CurDir() + "/result/" + C_FileName
#endif

***********************************
STAT FUNCTION FULL_RESOURCE( C_FileName )
***********************************
#if defined(__PLATFORM__WINDOWS) || defined(__PLATFORM__Windows)
    return DiskName() + ":\" + CurDir() + "\" + C_FileName
#else
    return "/" + CurDir() + "/" + C_FileName
#endif

***********************************
STAT FUNCTION OFFICE_ERROR( C_Text )
***********************************
LOCAL N_Err := HBOFFICE_LAST_ERROR()
LOCAL C_Err := HBOFFICE_ERROR_STR(N_Err)
LOCAL L_Err := .F.

IF N_Err != HBOFFICE_RES_OK
    ? C_Text + ": " + C_Err
    L_Err = .T.
ENDIF

RETURN L_Err

***********************************
STAT PROC CELL_TEXT( O_XLS, N_Page, N_Col, N_Row, C_Text, N_Size, L_Bold, N_RowHeight )
HBOFFICE_XLS_CELL_TEXT(O_XLS, N_Page, N_Col, N_Row, C_Text)
HBOFFICE_XLS_CELL_FONT_FAMILY(O_XLS, N_Page, N_Col, N_Row, "LucidaSansRegular")
HBOFFICE_XLS_CELL_FONT_SIZE(O_XLS, N_Page, N_Col, N_Row, N_Size)
HBOFFICE_XLS_CELL_BOLD(O_XLS, N_Page, N_Col, N_Row, L_Bold)
HBOFFICE_XLS_CELL_WRAP(O_XLS, N_Page, N_Col, N_Row, .T.)

IF N_RowHeight != 0
    HBOFFICE_XLS_ROW_HEIGHT(O_XLS, N_Page, N_Row, N_RowHeight)
ENDIF

RETURN

***********************************
STAT PROC ADD_PAGE( O_XLS, N_Id, C_Name )
HBOFFICE_XLS_ADD(O_XLS)
HBOFFICE_XLS_NAME(O_XLS, N_Id, C_Name)
RETURN

***********************************
PROCEDURE Main()
***********************************
LOCAL O_XLS := NIL
LOCAL N_Page := 0
LOCAL N_Col, N_Row, N_Cont
LOCAL C_File := FULL_PATH("sheet2.ods")
LOCAL C_PDF := FULL_PATH("sheet2.pdf")
LOCAL C_Formula := ""

hb_cdpSelect("PTISO")
hb_LangSelect("pt_BR","PTISO")

HBOFFICE_INIT()

? "Creating office example: " + C_File

O_XLS := HBOFFICE_XLS_CREATE()

IF OFFICE_ERROR("ERROR Creando a planilha")
    RETURN
ENDIF

// Generate the spreadsheet pages
HBOFFICE_XLS_NAME(O_XLS, 0, "RREO-Anexo 01")     // The first is allways created by an empty document
ADD_PAGE(O_XLS, 1, "RREO-Anexo 02")
ADD_PAGE(O_XLS, 2, "RREO-Anexo 03")
ADD_PAGE(O_XLS, 3, "RREO-Anexo 04")
ADD_PAGE(O_XLS, 4, "RREO-Anexo 06")
ADD_PAGE(O_XLS, 5, "RREO-Anexo 07")
ADD_PAGE(O_XLS, 6, "RREO-Anexo 13")
ADD_PAGE(O_XLS, 7, "RREO-Anexo 14")

FOR N_Page := 0 TO 7

// Remove all grid lines
HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 0, 0, 1000, 1000, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_COLUMN_WIDTH(O_XLS, N_Page, 0, 15250)
HBOFFICE_XLS_ROW_HEIGHT(O_XLS, N_Page, 0, 2616)
HBOFFICE_XLS_CELL_IMAGE(O_XLS, N_Page, 0, 0, {|| FULL_RESOURCE("cell_image_01.png") })

HBOFFICE_XLS_FREEZE(O_XLS, N_Page, 1, 0)
CELL_TEXT(O_XLS, N_Page, 0, 2, "RELATÓRIO RESUMIDO DE EXECUÇÃO ORÇAMENTÁRIA: " + hb_ntos(N_Page), 14, .T., 715)
CELL_TEXT(O_XLS, N_Page, 0, 3, "VERSÃO: v11: " + hb_ntos(N_Page), 14, .T., 715)
CELL_TEXT(O_XLS, N_Page, 0, 4, "VIGÊNCIA: 04/01/2023: " + hb_ntos(N_Page), 14, .T., 715)
CELL_TEXT(O_XLS, N_Page, 0, 6, "Ente: 2301604 - Assaré/CE: " + hb_ntos(N_Page), 10, .T., 0)
CELL_TEXT(O_XLS, N_Page, 0, 7, "Poder: E - Executivo: " + hb_ntos(N_Page), 10, .T., 0)
CELL_TEXT(O_XLS, N_Page, 0, 8, "Instituição: 2029 - Prefeitura Municipal de Assaré - CE: " + hb_ntos(N_Page), 10, .T., 0)
CELL_TEXT(O_XLS, N_Page, 0, 9, "Exercício: 2023: " + hb_ntos(N_Page), 10, .T., 0)
CELL_TEXT(O_XLS, N_Page, 0, 10, "Periodicidade: BIMESTRAL: " + hb_ntos(N_Page), 10, .T., 0)
CELL_TEXT(O_XLS, N_Page, 0, 11, "Período: 5º bimestre: " + hb_ntos(N_Page), 10, .T., 0)

CELL_TEXT(O_XLS, N_Page, 0, 13, "Grupo: Tabela 1.0 - Balanço Orçamentário", 10, .T., 0)
CELL_TEXT(O_XLS, N_Page, 0, 14, "Quadro: Receitas Orçamentárias", 10, .T., 0)
CELL_TEXT(O_XLS, N_Page, 0, 15, "Rótulo: Padrão", 10, .T., 0)
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 0, 13, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 0, 14, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 0, 15, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 0, 13, HBOFFICE_RGB(63, 103, 151))
HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 0, 14, HBOFFICE_RGB(63, 103, 151))
HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 0, 15, HBOFFICE_RGB(63, 103, 151))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 0, 13, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 0, 14, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 0, 15, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 0, 1, 0, 12, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELLS_BORDER(O_XLS, N_Page, 0, 1, 0, 12, HBOFFICE_LINE_STYLE_SOLID, 50, HBOFFICE_RGB(0, 0, 0))

HBOFFICE_XLS_ROW_HEIGHT(O_XLS, N_Page, 16, 1067)
HBOFFICE_XLS_ROW_HEIGHT(O_XLS, N_Page, 17, 1067)
HBOFFICE_XLS_ROW_HEIGHT(O_XLS, N_Page, 18, 1067)

HBOFFICE_XLS_CELLS_MERGE(O_XLS, N_Page, 0, 16, 0, 18)
HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 0, 16, 0, 18, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 0, 16, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 0, 16, "Receitas Orçamentárias", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 0, 16, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 0, 16, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELLS_BORDER(O_XLS, N_Page, 0, 16, 0, 18, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_COLUMN_WIDTH(O_XLS, N_Page, 1, 4496)
HBOFFICE_XLS_COLUMN_WIDTH(O_XLS, N_Page, 2, 5588)
HBOFFICE_XLS_COLUMN_WIDTH(O_XLS, N_Page, 3, 7722)
HBOFFICE_XLS_COLUMN_WIDTH(O_XLS, N_Page, 4, 7823)
HBOFFICE_XLS_COLUMN_WIDTH(O_XLS, N_Page, 5, 4115)
HBOFFICE_XLS_COLUMN_WIDTH(O_XLS, N_Page, 6, 7468)
HBOFFICE_XLS_COLUMN_WIDTH(O_XLS, N_Page, 7, 7823)

HBOFFICE_XLS_CELLS_MERGE(O_XLS, N_Page, 1, 16, 7, 16)
HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 1, 16, 7, 16, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 1, 16, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 1, 16, "Estágios da Receita Orçamentária", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 1, 16, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 1, 16, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELLS_BORDER(O_XLS, N_Page, 1, 16, 7, 16, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELLS_MERGE(O_XLS, N_Page, 1, 17, 1, 18)
HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 1, 17, 1, 18, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 1, 17, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 1, 17, "PREVISÃO INICIAL", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 1, 17, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 1, 17, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELLS_BORDER(O_XLS, N_Page, 1, 17, 1, 18, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELLS_MERGE(O_XLS, N_Page, 2, 17, 2, 18)
HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 2, 17, 2, 18, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 2, 17, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 2, 17, "PREVISÃO ATUALIZADA (a)", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 2, 17, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 2, 17, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELLS_BORDER(O_XLS, N_Page, 2, 17, 2, 18, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELLS_MERGE(O_XLS, N_Page, 3, 17, 6, 17)
HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 3, 17, 6, 17, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 3, 17, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 3, 17, "RECEITAS REALIZADAS", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 3, 17, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 3, 17, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELLS_BORDER(O_XLS, N_Page, 3, 17, 6, 17, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 3, 18, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 3, 18, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 3, 18, "No Bimestre (b)", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 3, 18, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 3, 18, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 3, 18, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 4, 18, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 4, 18, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 4, 18, "% (b/a)", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 4, 18, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 4, 18, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 4, 18, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 5, 18, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 5, 18, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 5, 18, "Até o Bimestre (c)", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 5, 18, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 5, 18, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 5, 18, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 6, 18, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 6, 18, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 6, 18, "% (c/a)", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 6, 18, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 6, 18, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 6, 18, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELLS_MERGE(O_XLS, N_Page, 7, 17, 7, 18)
HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 7, 17, 7, 18, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 7, 17, HBOFFICE_RGB(255, 255, 255))
CELL_TEXT(O_XLS, N_Page, 7, 17, "SALDO (a-c)", 10, .T., 0)
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 7, 17, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 7, 17, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELLS_BORDER(O_XLS, N_Page, 7, 17, 7, 18, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

CELL_TEXT(O_XLS, N_Page, 0, 19, "Receitas Orçamentárias", 10, .F., 0)
HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 0, 19, HBOFFICE_RGB(219, 229, 241))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 0, 19, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

CELL_TEXT(O_XLS, N_Page, 0, 20, "  RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I)", 10, .F., 0)
HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 0, 20, HBOFFICE_RGB(184, 204, 228))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 0, 19, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

CELL_TEXT(O_XLS, N_Page, 0, 21, "    RECEITAS CORRENTES", 10, .F., 0)
HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 0, 21, HBOFFICE_RGB(219, 229, 241))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 0, 21, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

CELL_TEXT(O_XLS, N_Page, 0, 22, "      IMPOSTOS, TAXAS E CONTRIBUIÇÕES DE MELHORIA", 10, .F., 0)
HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 0, 22, HBOFFICE_RGB(184, 204, 228))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 0, 22, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))

HBOFFICE_XLS_CELL_VALUE(O_XLS, N_Page, 1, 21, 136742327.00)
HBOFFICE_XLS_CELL_VALUE(O_XLS, N_Page, 1, 22, 7169100.07)
HBOFFICE_XLS_CELL_FORMULA(O_XLS, N_Page, 1, 20, "B22+B23")
HBOFFICE_XLS_CELL_NUMFORMAT(O_XLS, N_Page, 1, 21, HBOFFICE_NUMFORMAT_DEC2_1000)
HBOFFICE_XLS_CELL_NUMFORMAT(O_XLS, N_Page, 1, 22, HBOFFICE_NUMFORMAT_DEC2_1000)
HBOFFICE_XLS_CELL_NUMFORMAT(O_XLS, N_Page, 1, 20, HBOFFICE_NUMFORMAT_DEC2_1000)

HBOFFICE_XLS_ROW_HEIGHT(O_XLS, N_Page, 24, 1067)
HBOFFICE_XLS_ROW_HEIGHT(O_XLS, N_Page, 25, 1067)
HBOFFICE_XLS_CELLS_MERGE(O_XLS, N_Page, 0, 24, 0, 25)

HBOFFICE_XLS_CELLS_BACKCOLOR(O_XLS, N_Page, 0, 24, 0, 25, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 0, 24, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELLS_BORDER(O_XLS, N_Page, 0, 24, 0, 25, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 0, 24, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 0, 24, HBOFFICE_VALIGN_CENTER)
CELL_TEXT(O_XLS, N_Page, 0, 24, "Notas Explicativas", 10, .T., 0)

HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 1, 24, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 1, 24, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 1, 24, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 1, 24, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 1, 24, HBOFFICE_VALIGN_CENTER)
CELL_TEXT(O_XLS, N_Page, 1, 24, "Valores", 10, .T., 0)

HBOFFICE_XLS_CELL_BACKCOLOR(O_XLS, N_Page, 1, 25, HBOFFICE_RGB(79, 129, 189))
HBOFFICE_XLS_CELL_COLOR(O_XLS, N_Page, 1, 25, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_BORDER(O_XLS, N_Page, 1, 25, HBOFFICE_LINE_STYLE_SOLID, 25, HBOFFICE_RGB(255, 255, 255))
HBOFFICE_XLS_CELL_HALIGN(O_XLS, N_Page, 1, 25, HBOFFICE_HALIGN_CENTER)
HBOFFICE_XLS_CELL_VALIGN(O_XLS, N_Page, 1, 25, HBOFFICE_VALIGN_CENTER)
HBOFFICE_XLS_CELL_DATE(O_XLS, N_Page, 1, 25, 31, 10, 2023)
HBOFFICE_XLS_CELL_NUMFORMAT(O_XLS, N_Page, 1, 25, HBOFFICE_NUMFORMAT_DATE_SYS_NNNNDMMMMYYYY)

NEXT

// Testing multi-page formula
HBOFFICE_XLS_CELL_VALUE(O_XLS, 0, 0, 28, 1000.23)
HBOFFICE_XLS_CELL_VALUE(O_XLS, 1, 0, 28, 543.15)
HBOFFICE_XLS_CELL_VALUE(O_XLS, 2, 0, 28, 823.45)
HBOFFICE_XLS_CELL_VALUE(O_XLS, 3, 0, 28, -330.89)
HBOFFICE_XLS_CELL_VALUE(O_XLS, 4, 0, 28, 829.00)
HBOFFICE_XLS_CELL_VALUE(O_XLS, 5, 0, 28, -100.99)
HBOFFICE_XLS_CELL_VALUE(O_XLS, 6, 0, 28, 43.74)
HBOFFICE_XLS_CELL_VALUE(O_XLS, 7, 0, 28, 600.64)
HBOFFICE_XLS_CELL_FORMULA(O_XLS, 0, 0, 29, "$'RREO-Anexo 01'.A29+$'RREO-Anexo 02'.A29+$'RREO-Anexo 03'.A29+$'RREO-Anexo 04'.A29+$'RREO-Anexo 06'.A29+$'RREO-Anexo 07'.A29+$'RREO-Anexo 13'.A29+$'RREO-Anexo 14'.A29")

// Compose the same formula using cell references
C_Formula:=""

FOR N_Page := 0 TO 7
    C_Formula += HBOFFICE_XLS_CELL_REF(O_XLS, N_Page, 0, 28)
    IF N_Page < 7
        C_Formula += "+"
    ENDIF
NEXT
HBOFFICE_XLS_CELL_FORMULA(O_XLS, 0, 0, 30, C_Formula)

// Save the spreadsheet
HBOFFICE_XLS_SAVE(O_XLS, C_File)
IF OFFICE_ERROR("ERROR Salvando a planilha")
    RETURN
ENDIF

// Save the pdf
HBOFFICE_XLS_PDF(O_XLS, C_PDF)
IF OFFICE_ERROR("Erro ao salvar PDF")
    RETURN
ENDIF

// Close the spreadsheet (mandatory)
HBOFFICE_XLS_CLOSE(O_XLS)
IF OFFICE_ERROR("ERROR Fechando planilha")
    RETURN
ENDIF

? "A planilha foi criada com sucesso."

HBOFFICE_FINISH()
RETURN
