#
# $Id$
#

ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

LIBNAME := hbxpp

C_SOURCES := \
   binnumx.c \
   dbcmdx.c \
   dbdetacx.c \
   dllx.c \
   idlex.c \
   mousex.c \
   oemansix.c \
   philesx.c \
   pvalue.c \
   xppopc.c \

PRG_SOURCES := \
   browdbx.prg \
   dbfuncsx.prg \
   dbjoinx.prg \
   dblistx.prg \
   dbsortx.prg \
   dbstruxx.prg \
   dbtotalx.prg \
   dbupdatx.prg \
   runshell.prg \
   tbcolumx.prg \
   tbrowsex.prg \
   tgetx.prg \
   thfuncx.prg \
   tthreadx.prg \
   typefilx.prg \
   xppop.prg \

PRG_HEADERS := \
   dll.ch \
   hbxpp.ch \
   hbxppext.ch \
   thread.ch \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
