#
# $Id$
#

ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

LIBNAME := hbsms

PRG_SOURCES := \
   hbsms.prg \

HB_INC_DEPEND := -I$(TOP)$(ROOT)contrib/hbtpathy

include $(TOP)$(ROOT)config/lib.mk
