#
# $Id: Makefile 12881 2009-11-15 04:31:21Z vszakats $
#

ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

LIBNAME := hbsms

PRG_SOURCES := \
   hbsms.prg \

include $(TOP)$(ROOT)config/lib.mk
