#
# $Id$
#

ifeq ($(HB_MAIN),)
   HB_MAIN := std
endif

ROOT := ../../

PRG_SOURCES := \
   hbi18n.prg \

PRG_MAIN := hbi18n.prg

LIBS := \
   hbdebug \
   hbvm \
   hbrtl \
   hblang \
   hbcpage \
   hbnulrdd \
   hbrtl \
   hbvm \
   hbmacro \
   hbcommon \

include $(TOP)$(ROOT)config/bin.cf
