/*
 * $Id$
 */

/* -------------------------------------------------------------------- */
/* WARNING: Automatically generated source file. DO NOT EDIT!           */
/*          Instead, edit corresponding .ui file,                       */
/*          with Qt Generator, and run hbqtui.exe.                      */
/* -------------------------------------------------------------------- */
/*                                                                      */
/*               Pritpal Bedi <bedipritpal@hotmail.com>                 */
/*                                                                      */
/* -------------------------------------------------------------------- */

FUNCTION uiDocviewgenerator( qParent )
   LOCAL oUI
   LOCAL oWidget
   LOCAL qObj := {=>}

   hb_hCaseMatch( qObj, .f. )

   oWidget := QWidget():new( qParent )
  
   oWidget:setObjectName( "FormDocViewer" )
  
   qObj[ "FormDocViewer"      ] := oWidget
  
   qObj[ "gridLayout"         ] := QGridLayout():new(qObj[ "FormDocViewer" ])
   qObj[ "horizontalLayout_3" ] := QHBoxLayout():new()
   qObj[ "buttonHome"         ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "buttonBackward"     ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "buttonForward"      ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "buttonUp"           ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "buttonRefresh"      ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "buttonPrint"        ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "buttonPdf"          ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "horizontalSpacer_2" ] := QSpacerItem():new(40, 20, 7, 1)
   qObj[ "buttonExit"         ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "horizontalLayout"   ] := QHBoxLayout():new()
   qObj[ "labelInstall"       ] := QLabel():new(qObj[ "FormDocViewer" ])
   qObj[ "editInstall"        ] := QLineEdit():new(qObj[ "FormDocViewer" ])
   qObj[ "buttonInstall"      ] := QToolButton():new(qObj[ "FormDocViewer" ])
   qObj[ "labelDocPrefix"     ] := QLabel():new(qObj[ "FormDocViewer" ])
   qObj[ "editDocPrefix"      ] := QLineEdit():new(qObj[ "FormDocViewer" ])
   qObj[ "splitter"           ] := QSplitter():new(qObj[ "FormDocViewer" ])
   qObj[ "tabWidgetContents"  ] := QTabWidget():new(qObj[ "splitter" ])
   qObj[ "tabContents"        ] := QWidget():new()
   qObj[ "verticalLayout"     ] := QVBoxLayout():new(qObj[ "tabContents" ])
   qObj[ "treeDoc"            ] := QTreeWidget():new(qObj[ "tabContents" ])
   qObj[ "__qtreewidgetitem"  ] := QTreeWidgetItem():new()
   qObj[ "tabByName"          ] := QWidget():new()
   qObj[ "verticalLayout_2"   ] := QVBoxLayout():new(qObj[ "tabByName" ])
   qObj[ "editIndex"          ] := QLineEdit():new(qObj[ "tabByName" ])
   qObj[ "listIndex"          ] := QListWidget():new(qObj[ "tabByName" ])
   qObj[ "tabByCategory"      ] := QWidget():new()
   qObj[ "verticalLayout_3"   ] := QVBoxLayout():new(qObj[ "tabByCategory" ])
   qObj[ "treeCategory"       ] := QTreeWidget():new(qObj[ "tabByCategory" ])
   qObj[ "__qtreewidgetitem1" ] := QTreeWidgetItem():new()
   qObj[ "tabWidgetElements"  ] := QTabWidget():new(qObj[ "splitter" ])
   qObj[ "tabView"            ] := QWidget():new()
   qObj[ "gridLayout_8"       ] := QGridLayout():new(qObj[ "tabView" ])
   qObj[ "browserView"        ] := QTextBrowser():new(qObj[ "tabView" ])
   qObj[ "tabTests"           ] := QWidget():new()
   qObj[ "gridLayout_12"      ] := QGridLayout():new(qObj[ "tabTests" ])
   qObj[ "frameButtons"       ] := QFrame():new(qObj[ "tabTests" ])
   qObj[ "horizontalLayout_2" ] := QHBoxLayout():new(qObj[ "frameButtons" ])
   qObj[ "buttonLoadFromCurFunc" ] := QToolButton():new(qObj[ "frameButtons" ])
   qObj[ "buttonLoadFromDocFile" ] := QToolButton():new(qObj[ "frameButtons" ])
   qObj[ "buttonLoadFromSource" ] := QToolButton():new(qObj[ "frameButtons" ])
   qObj[ "buttonArgs"         ] := QToolButton():new(qObj[ "frameButtons" ])
   qObj[ "buttonDesc"         ] := QToolButton():new(qObj[ "frameButtons" ])
   qObj[ "buttonExamples"     ] := QToolButton():new(qObj[ "frameButtons" ])
   qObj[ "buttonTests"        ] := QToolButton():new(qObj[ "frameButtons" ])
   qObj[ "horizontalSpacer"   ] := QSpacerItem():new(40, 20, 7, 1)
   qObj[ "buttonSave"         ] := QToolButton():new(qObj[ "frameButtons" ])
   qObj[ "scrollArea"         ] := QScrollArea():new(qObj[ "tabTests" ])
   qObj[ "scrollAreaWidgetContents" ] := QWidget():new()
   qObj[ "verticalLayout_4"   ] := QVBoxLayout():new(qObj[ "scrollAreaWidgetContents" ])
   qObj[ "splitter_2"         ] := QSplitter():new(qObj[ "scrollAreaWidgetContents" ])
   qObj[ "frameGeneral"       ] := QFrame():new(qObj[ "splitter_2" ])
   qObj[ "gridLayout_6"       ] := QGridLayout():new(qObj[ "frameGeneral" ])
   qObj[ "labelTemplate"      ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "labelVersion"       ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "labelStatus"        ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "label_7"            ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "comboTemplate"      ] := QComboBox():new(qObj[ "frameGeneral" ])
   qObj[ "editVersion"        ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "editStatus"         ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "editCompliance"     ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "labelCategory"      ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "labelSubCategory"   ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "editCategory"       ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "editSubCategory"    ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "labelName"          ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "labelExtLink"       ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "editName"           ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "editExtLink"        ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "labelOneLiner"      ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "editOneLiner"       ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "labelSyntax"        ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "editSyntax"         ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "labelReturns"       ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "editReturns"        ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "labelSeeAlso"       ] := QLabel():new(qObj[ "frameGeneral" ])
   qObj[ "editSeeAlso"        ] := QLineEdit():new(qObj[ "frameGeneral" ])
   qObj[ "frameArgs"          ] := QFrame():new(qObj[ "splitter_2" ])
   qObj[ "gridLayout_7"       ] := QGridLayout():new(qObj[ "frameArgs" ])
   qObj[ "labelArgs"          ] := QLabel():new(qObj[ "frameArgs" ])
   qObj[ "buttonCloseArgs"    ] := QToolButton():new(qObj[ "frameArgs" ])
   qObj[ "plainArgs"          ] := QPlainTextEdit():new(qObj[ "frameArgs" ])
   qObj[ "frameDesc"          ] := QFrame():new(qObj[ "splitter_2" ])
   qObj[ "gridLayout_9"       ] := QGridLayout():new(qObj[ "frameDesc" ])
   qObj[ "labelDesc"          ] := QLabel():new(qObj[ "frameDesc" ])
   qObj[ "buttonCloseDesc"    ] := QToolButton():new(qObj[ "frameDesc" ])
   qObj[ "plainDesc"          ] := QPlainTextEdit():new(qObj[ "frameDesc" ])
   qObj[ "frameExamples"      ] := QFrame():new(qObj[ "splitter_2" ])
   qObj[ "gridLayout_10"      ] := QGridLayout():new(qObj[ "frameExamples" ])
   qObj[ "labelExamples"      ] := QLabel():new(qObj[ "frameExamples" ])
   qObj[ "buttonCloseExamples" ] := QToolButton():new(qObj[ "frameExamples" ])
   qObj[ "plainExamples"      ] := QPlainTextEdit():new(qObj[ "frameExamples" ])
   qObj[ "frameTests"         ] := QFrame():new(qObj[ "splitter_2" ])
   qObj[ "gridLayout_11"      ] := QGridLayout():new(qObj[ "frameTests" ])
   qObj[ "labelTests"         ] := QLabel():new(qObj[ "frameTests" ])
   qObj[ "buttonCloseTests"   ] := QToolButton():new(qObj[ "frameTests" ])
   qObj[ "plainTests"         ] := QPlainTextEdit():new(qObj[ "frameTests" ])
   
   qObj[ "FormDocViewer"      ]:resize(645, 557)
   qObj[ "buttonHome"         ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_3" ]:addWidget(qObj[ "buttonHome" ])
   qObj[ "buttonBackward"     ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_3" ]:addWidget(qObj[ "buttonBackward" ])
   qObj[ "buttonForward"      ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_3" ]:addWidget(qObj[ "buttonForward" ])
   qObj[ "buttonUp"           ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_3" ]:addWidget(qObj[ "buttonUp" ])
   qObj[ "buttonRefresh"      ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_3" ]:addWidget(qObj[ "buttonRefresh" ])
   qObj[ "buttonPrint"        ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_3" ]:addWidget(qObj[ "buttonPrint" ])
   qObj[ "horizontalLayout_3" ]:addWidget(qObj[ "buttonPdf" ])
   qObj[ "horizontalLayout_3" ]:addItem(qObj[ "horizontalSpacer_2" ])
   qObj[ "buttonExit"         ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_3" ]:addWidget(qObj[ "buttonExit" ])
   qObj[ "gridLayout"         ]:addLayout_1(qObj[ "horizontalLayout_3" ], 0, 0, 1, 1)
   qObj[ "horizontalLayout"   ]:addWidget(qObj[ "labelInstall" ])
   qObj[ "horizontalLayout"   ]:addWidget(qObj[ "editInstall" ])
   qObj[ "buttonInstall"      ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout"   ]:addWidget(qObj[ "buttonInstall" ])
   qObj[ "horizontalLayout"   ]:addWidget(qObj[ "labelDocPrefix" ])
   qObj[ "editDocPrefix"      ]:setMaximumSize(QSize():new(70, 16777215))
   qObj[ "horizontalLayout"   ]:addWidget(qObj[ "editDocPrefix" ])
   qObj[ "gridLayout"         ]:addLayout_1(qObj[ "horizontalLayout" ], 1, 0, 1, 1)
   qObj[ "splitter"           ]:setOrientation(1)
   qObj[ "tabWidgetContents"  ]:setMaximumSize(QSize():new(16777215, 16777215))
   qObj[ "tabWidgetContents"  ]:setDocumentMode(.F.)
   qObj[ "__qtreewidgetitem"  ]:setText( [] )
   qObj[ "treeDoc"            ]:setHeaderItem(qObj[ "__qtreewidgetitem" ])
   qObj[ "verticalLayout"     ]:addWidget(qObj[ "treeDoc" ])
   qObj[ "tabWidgetContents"  ]:addTab(qObj[ "tabContents" ], "")
   qObj[ "verticalLayout_2"   ]:addWidget(qObj[ "editIndex" ])
   qObj[ "verticalLayout_2"   ]:addWidget(qObj[ "listIndex" ])
   qObj[ "tabWidgetContents"  ]:addTab(qObj[ "tabByName" ], "")
   qObj[ "__qtreewidgetitem1" ]:setText( [] )
   qObj[ "treeCategory"       ]:setHeaderItem(qObj[ "__qtreewidgetitem1" ])
   qObj[ "verticalLayout_3"   ]:addWidget(qObj[ "treeCategory" ])
   qObj[ "tabWidgetContents"  ]:addTab(qObj[ "tabByCategory" ], "")
   qObj[ "splitter"           ]:addWidget(qObj[ "tabWidgetContents" ])
   qObj[ "gridLayout_8"       ]:addWidget_1(qObj[ "browserView" ], 0, 0, 1, 1)
   qObj[ "tabWidgetElements"  ]:addTab(qObj[ "tabView" ], "")
   qObj[ "gridLayout_12"      ]:setContentsMargins(0, 0, 0, -1)
   qObj[ "frameButtons"       ]:setMinimumSize(QSize():new(0, 30))
   qObj[ "frameButtons"       ]:setMaximumSize(QSize():new(16777215, 30))
   qObj[ "frameButtons"       ]:setFrameShape(2)
   qObj[ "frameButtons"       ]:setFrameShadow(32)
   qObj[ "horizontalLayout_2" ]:setContentsMargins(-1, 2, 5, 4)
   qObj[ "buttonLoadFromCurFunc" ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_2" ]:addWidget(qObj[ "buttonLoadFromCurFunc" ])
   qObj[ "buttonLoadFromDocFile" ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_2" ]:addWidget(qObj[ "buttonLoadFromDocFile" ])
   qObj[ "buttonLoadFromSource" ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_2" ]:addWidget(qObj[ "buttonLoadFromSource" ])
   qObj[ "buttonArgs"         ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_2" ]:addWidget(qObj[ "buttonArgs" ])
   qObj[ "buttonDesc"         ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_2" ]:addWidget(qObj[ "buttonDesc" ])
   qObj[ "buttonExamples"     ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_2" ]:addWidget(qObj[ "buttonExamples" ])
   qObj[ "buttonTests"        ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_2" ]:addWidget(qObj[ "buttonTests" ])
   qObj[ "horizontalLayout_2" ]:addItem(qObj[ "horizontalSpacer" ])
   qObj[ "buttonSave"         ]:setAutoRaise(.F.)
   qObj[ "horizontalLayout_2" ]:addWidget(qObj[ "buttonSave" ])
   qObj[ "gridLayout_12"      ]:addWidget_1(qObj[ "frameButtons" ], 0, 0, 1, 1)
   qObj[ "scrollArea"         ]:setFrameShape(0)
   qObj[ "scrollArea"         ]:setWidgetResizable(.T.)
   qObj[ "scrollAreaWidgetContents" ]:setGeometry(QRect():new(0, 0, 369, 625))
   qObj[ "verticalLayout_4"   ]:setSpacing(3)
   qObj[ "verticalLayout_4"   ]:setContentsMargins(0, 0, 0, 9)
   qObj[ "splitter_2"         ]:setOrientation(2)
   qObj[ "splitter_2"         ]:setHandleWidth(2)
   qObj[ "frameGeneral"       ]:setMaximumSize(QSize():new(16777215, 268))
   qObj[ "frameGeneral"       ]:setFrameShape(0)
   qObj[ "frameGeneral"       ]:setFrameShadow(16)
   qObj[ "gridLayout_6"       ]:setVerticalSpacing(2)
   qObj[ "gridLayout_6"       ]:setContentsMargins(-1, 4, 4, 0)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelTemplate" ], 0, 0, 1, 1)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelVersion" ], 0, 1, 1, 1)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelStatus" ], 0, 2, 1, 1)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "label_7" ], 0, 3, 1, 1)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "comboTemplate" ], 1, 0, 1, 1)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editVersion" ], 1, 1, 1, 1)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editStatus" ], 1, 2, 1, 1)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editCompliance" ], 1, 3, 1, 1)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelCategory" ], 2, 0, 1, 2)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelSubCategory" ], 2, 2, 1, 2)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editCategory" ], 3, 0, 1, 2)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editSubCategory" ], 3, 2, 1, 2)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelName" ], 4, 0, 1, 2)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelExtLink" ], 4, 2, 1, 2)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editName" ], 5, 0, 1, 2)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editExtLink" ], 5, 2, 1, 2)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelOneLiner" ], 6, 0, 1, 4)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editOneLiner" ], 7, 0, 1, 4)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelSyntax" ], 8, 0, 1, 4)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editSyntax" ], 9, 0, 1, 4)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelReturns" ], 10, 0, 1, 4)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editReturns" ], 11, 0, 1, 4)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "labelSeeAlso" ], 12, 0, 1, 4)
   qObj[ "gridLayout_6"       ]:addWidget_1(qObj[ "editSeeAlso" ], 13, 0, 1, 4)
   qObj[ "splitter_2"         ]:addWidget(qObj[ "frameGeneral" ])
   qObj[ "frameArgs"          ]:setFrameShape(0)
   qObj[ "frameArgs"          ]:setFrameShadow(32)
   qObj[ "gridLayout_7"       ]:setVerticalSpacing(2)
   qObj[ "gridLayout_7"       ]:setContentsMargins(-1, 2, 4, 0)
   qObj[ "gridLayout_7"       ]:addWidget_1(qObj[ "labelArgs" ], 0, 0, 1, 1)
   qObj[ "buttonCloseArgs"    ]:setAutoRaise(.T.)
   qObj[ "gridLayout_7"       ]:addWidget_1(qObj[ "buttonCloseArgs" ], 0, 1, 1, 1)
   qObj[ "gridLayout_7"       ]:addWidget_1(qObj[ "plainArgs" ], 1, 0, 1, 2)
   qObj[ "splitter_2"         ]:addWidget(qObj[ "frameArgs" ])
   qObj[ "frameDesc"          ]:setFrameShape(0)
   qObj[ "frameDesc"          ]:setFrameShadow(32)
   qObj[ "gridLayout_9"       ]:setVerticalSpacing(2)
   qObj[ "gridLayout_9"       ]:setContentsMargins(-1, 2, 4, 0)
   qObj[ "gridLayout_9"       ]:addWidget_1(qObj[ "labelDesc" ], 0, 0, 1, 1)
   qObj[ "buttonCloseDesc"    ]:setAutoRaise(.T.)
   qObj[ "gridLayout_9"       ]:addWidget_1(qObj[ "buttonCloseDesc" ], 0, 1, 1, 1)
   qObj[ "gridLayout_9"       ]:addWidget_1(qObj[ "plainDesc" ], 1, 0, 1, 2)
   qObj[ "splitter_2"         ]:addWidget(qObj[ "frameDesc" ])
   qObj[ "frameExamples"      ]:setFrameShape(0)
   qObj[ "frameExamples"      ]:setFrameShadow(32)
   qObj[ "gridLayout_10"      ]:setVerticalSpacing(2)
   qObj[ "gridLayout_10"      ]:setContentsMargins(-1, 2, 4, 0)
   qObj[ "gridLayout_10"      ]:addWidget_1(qObj[ "labelExamples" ], 0, 0, 1, 1)
   qObj[ "buttonCloseExamples" ]:setAutoRaise(.T.)
   qObj[ "gridLayout_10"      ]:addWidget_1(qObj[ "buttonCloseExamples" ], 0, 1, 1, 1)
   qObj[ "plainExamples"      ]:setLineWrapMode(0)
   qObj[ "gridLayout_10"      ]:addWidget_1(qObj[ "plainExamples" ], 1, 0, 1, 2)
   qObj[ "splitter_2"         ]:addWidget(qObj[ "frameExamples" ])
   qObj[ "frameTests"         ]:setMinimumSize(QSize():new(0, 0))
   qObj[ "frameTests"         ]:setFrameShape(0)
   qObj[ "frameTests"         ]:setFrameShadow(32)
   qObj[ "gridLayout_11"      ]:setVerticalSpacing(2)
   qObj[ "gridLayout_11"      ]:setContentsMargins(-1, 2, 4, 0)
   qObj[ "gridLayout_11"      ]:addWidget_1(qObj[ "labelTests" ], 0, 0, 1, 1)
   qObj[ "buttonCloseTests"   ]:setAutoRaise(.T.)
   qObj[ "gridLayout_11"      ]:addWidget_1(qObj[ "buttonCloseTests" ], 0, 1, 1, 1)
   qObj[ "plainTests"         ]:setLineWrapMode(0)
   qObj[ "gridLayout_11"      ]:addWidget_1(qObj[ "plainTests" ], 1, 0, 1, 2)
   qObj[ "splitter_2"         ]:addWidget(qObj[ "frameTests" ])
   qObj[ "verticalLayout_4"   ]:addWidget(qObj[ "splitter_2" ])
   qObj[ "scrollArea"         ]:setWidget(qObj[ "scrollAreaWidgetContents" ])
   qObj[ "gridLayout_12"      ]:addWidget_1(qObj[ "scrollArea" ], 1, 0, 1, 1)
   qObj[ "tabWidgetElements"  ]:addTab(qObj[ "tabTests" ], "")
   qObj[ "splitter"           ]:addWidget(qObj[ "tabWidgetElements" ])
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "splitter" ], 2, 0, 1, 1)
   qObj[ "tabWidgetContents"  ]:setCurrentIndex(0)
   qObj[ "tabWidgetElements"  ]:setCurrentIndex(0)
   qObj[ "FormDocViewer"      ]:setWindowTitle(q__tr("FormDocViewer", "Form", 0, "UTF8"))
   qObj[ "buttonHome"         ]:setText( [] )
   qObj[ "buttonBackward"     ]:setText( [] )
   qObj[ "buttonForward"      ]:setText( [] )
   qObj[ "buttonUp"           ]:setText( [] )
   qObj[ "buttonRefresh"      ]:setText( [] )
   qObj[ "buttonPrint"        ]:setText( [] )
   qObj[ "buttonPdf"          ]:setText( [] )
   qObj[ "buttonExit"         ]:setText( [] )
   qObj[ "labelInstall"       ]:setText( [Harbour Installation Root:] )
   qObj[ "buttonInstall"      ]:setText( [] )
   qObj[ "labelDocPrefix"     ]:setText( [Doc folder prefix:] )
   qObj[ "tabWidgetContents"  ]:setTabText(qObj[ "tabWidgetContents" ]:indexOf(qObj[ "tabContents" ]), q__tr("FormDocViewer", "Topics", 0, "UTF8"))
   qObj[ "tabWidgetContents"  ]:setTabText(qObj[ "tabWidgetContents" ]:indexOf(qObj[ "tabByName" ]), q__tr("FormDocViewer", "Index", 0, "UTF8"))
   qObj[ "tabWidgetContents"  ]:setTabText(qObj[ "tabWidgetContents" ]:indexOf(qObj[ "tabByCategory" ]), q__tr("FormDocViewer", "Category", 0, "UTF8"))
   qObj[ "tabWidgetElements"  ]:setTabText(qObj[ "tabWidgetElements" ]:indexOf(qObj[ "tabView" ]), q__tr("FormDocViewer", "View", 0, "UTF8"))
   qObj[ "buttonLoadFromCurFunc" ]:setToolTip( [Load from current function] )
   qObj[ "buttonLoadFromCurFunc" ]:setText( [...] )
   qObj[ "buttonLoadFromDocFile" ]:setToolTip( [Load from .txt file] )
   qObj[ "buttonLoadFromDocFile" ]:setText( [...] )
   qObj[ "buttonLoadFromSource" ]:setToolTip( [Load from source ( .prg,.c,.c++ ) file] )
   qObj[ "buttonLoadFromSource" ]:setText( [...] )
   qObj[ "buttonArgs"         ]:setToolTip( [Toggle Arguments Section] )
   qObj[ "buttonArgs"         ]:setText( [...] )
   qObj[ "buttonDesc"         ]:setToolTip( [Toggle Descriptions Section] )
   qObj[ "buttonDesc"         ]:setText( [...] )
   qObj[ "buttonExamples"     ]:setToolTip( [Toggle Examples Section] )
   qObj[ "buttonExamples"     ]:setText( [...] )
   qObj[ "buttonTests"        ]:setToolTip( [Toggle Tests Section] )
   qObj[ "buttonTests"        ]:setText( [...] )
   qObj[ "buttonSave"         ]:setToolTip( [Save written/updated documentation] )
   qObj[ "buttonSave"         ]:setText( [...] )
   qObj[ "labelTemplate"      ]:setText( [Template:] )
   qObj[ "labelVersion"       ]:setText( [Version:] )
   qObj[ "labelStatus"        ]:setText( [Status:] )
   qObj[ "label_7"            ]:setText( [Compliance:] )
   qObj[ "editVersion"        ]:setToolTip( [Version of this document contents] )
   qObj[ "editStatus"         ]:setToolTip( [Status should usually be described as one character] )
   qObj[ "editCompliance"     ]:setToolTip( [Describe comatibility with other language] )
   qObj[ "labelCategory"      ]:setText( [Category:] )
   qObj[ "labelSubCategory"   ]:setText( [Sub-category:] )
   qObj[ "editCategory"       ]:setToolTip( [Category should describe main area this function belongs to] )
   qObj[ "labelName"          ]:setText( [Name:] )
   qObj[ "labelExtLink"       ]:setText( [External Link:] )
   qObj[ "editName"           ]:setToolTip( [Name of the function, and if appropriate, with open/close parenthis.] )
   qObj[ "editExtLink"        ]:setToolTip( [External link, i.e., http://www.trolltech.com/] )
   qObj[ "labelOneLiner"      ]:setText( [One Liner:] )
   qObj[ "editOneLiner"       ]:setToolTip( [A brief description this function accomlishes] )
   qObj[ "labelSyntax"        ]:setText( [Syntax:] )
   qObj[ "editSyntax"         ]:setToolTip( [Syntax, or prototype as to how this function will be called] )
   qObj[ "labelReturns"       ]:setText( [Returns:] )
   qObj[ "editReturns"        ]:setToolTip( [Variable name with hungarian notation with brief description as what this function returns] )
   qObj[ "labelSeeAlso"       ]:setText( [See Also:] )
   qObj[ "editSeeAlso"        ]:setToolTip( [A comma separated list of related functions/keywords ] )
   qObj[ "labelArgs"          ]:setText( [Arguments:] )
   qObj[ "buttonCloseArgs"    ]:setText( [...] )
   qObj[ "plainArgs"          ]:setToolTip( [One argument per line in the form - argName    description] )
   qObj[ "labelDesc"          ]:setText( [Description:] )
   qObj[ "buttonCloseDesc"    ]:setText( [...] )
   qObj[ "plainDesc"          ]:setToolTip( [Detailed description as musch as possible to convey to the user what should be kept in mind when this function is called.] )
   qObj[ "labelExamples"      ]:setText( [Examples:] )
   qObj[ "buttonCloseExamples" ]:setText( [...] )
   qObj[ "plainExamples"      ]:setToolTip( [A real-time source code which could be compiled out of this box.] )
   qObj[ "labelTests"         ]:setText( [Tests:] )
   qObj[ "buttonCloseTests"   ]:setText( [...] )
   qObj[ "plainTests"         ]:setToolTip( [Compilable code out of the box which could be used to test this function] )
   qObj[ "tabWidgetElements"  ]:setTabText(qObj[ "tabWidgetElements" ]:indexOf(qObj[ "tabTests" ]), q__tr("FormDocViewer", "Write", 0, "UTF8"))

   oUI         := HbQtUI():new()
   oUI:qObj    := qObj
   oUI:oWidget := oWidget

   RETURN oUI

/*----------------------------------------------------------------------*/

