/*
 * $Id$
 */

/* -------------------------------------------------------------------- */
/* WARNING: Automatically generated source file. DO NOT EDIT!           */
/*          Instead, edit corresponding .ui file,                       */
/*          with Qt Generator, and run hbqtui.exe.                      */
/* -------------------------------------------------------------------- */
/*                                                                      */
/*               Pritpal Bedi <bedipritpal@hotmail.com>                 */
/*                                                                      */
/* -------------------------------------------------------------------- */

FUNCTION uiFindinfilesex( qParent )
   LOCAL oUI
   LOCAL oWidget
   LOCAL qObj := {=>}

   hb_hCaseMatch( qObj, .f. )

   oWidget := QWidget():new( qParent )
  
   oWidget:setObjectName( "FormFindInFilesEx" )
  
   qObj[ "FormFindInFilesEx"  ] := oWidget
  
   qObj[ "gridLayout"         ] := QGridLayout():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "horizontalLayout_5" ] := QHBoxLayout():new()
   qObj[ "comboFolder"        ] := QComboBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "buttonFolder"       ] := QToolButton():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "horizontalLayout_6" ] := QHBoxLayout():new()
   qObj[ "labelFileTypes"     ] := QLabel():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkAll"           ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkPrg"           ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkC"             ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkCpp"           ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkCh"            ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkH"             ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkRc"            ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "line_5"             ] := QFrame():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "labelProjects"      ] := QLabel():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "listProjects"       ] := QListWidget():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "line_3"             ] := QFrame():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "labelExpr"          ] := QLabel():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "comboExpr"          ] := QComboBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkRegEx"         ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkMatchCase"     ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "checkListOnly"      ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "labelRepl"          ] := QLabel():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "comboRepl"          ] := QComboBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "line_4"             ] := QFrame():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "editResults"        ] := QTextEdit():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "labelStatus"        ] := QLabel():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "horizontalLayout_7" ] := QHBoxLayout():new()
   qObj[ "buttonFind"         ] := QPushButton():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "buttonRepl"         ] := QPushButton():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "buttonStop"         ] := QPushButton():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "buttonClose"        ] := QPushButton():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "labelFolder"        ] := QLabel():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "horizontalLayout_4" ] := QHBoxLayout():new()
   qObj[ "checkOpenTabs"      ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "horizontalSpacer"   ] := QSpacerItem():new(40, 20, 7, 1)
   qObj[ "checkSubProjects"   ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "horizontalLayout_8" ] := QHBoxLayout():new()
   qObj[ "checkFolders"       ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   qObj[ "horizontalSpacer_2" ] := QSpacerItem():new(40, 20, 7, 1)
   qObj[ "checkSubFolders"    ] := QCheckBox():new(qObj[ "FormFindInFilesEx" ])
   
   qObj[ "FormFindInFilesEx"  ]:resize(404, 443)
   qObj[ "comboFolder"        ]:setEditable(.T.)
   qObj[ "horizontalLayout_5" ]:addWidget(qObj[ "comboFolder" ])
   qObj[ "horizontalLayout_5" ]:addWidget(qObj[ "buttonFolder" ])
   qObj[ "gridLayout"         ]:addLayout_1(qObj[ "horizontalLayout_5" ], 4, 1, 1, 3)
   qObj[ "labelFileTypes"     ]:setMinimumSize(QSize():new(52, 0))
   qObj[ "labelFileTypes"     ]:setMaximumSize(QSize():new(52, 16777215))
   qObj[ "horizontalLayout_6" ]:addWidget(qObj[ "labelFileTypes" ])
   qObj[ "horizontalLayout_6" ]:addWidget(qObj[ "checkAll" ])
   qObj[ "horizontalLayout_6" ]:addWidget(qObj[ "checkPrg" ])
   qObj[ "horizontalLayout_6" ]:addWidget(qObj[ "checkC" ])
   qObj[ "horizontalLayout_6" ]:addWidget(qObj[ "checkCpp" ])
   qObj[ "horizontalLayout_6" ]:addWidget(qObj[ "checkCh" ])
   qObj[ "horizontalLayout_6" ]:addWidget(qObj[ "checkH" ])
   qObj[ "checkRc"            ]:setMaximumSize(QSize():new(33, 16777215))
   qObj[ "horizontalLayout_6" ]:addWidget(qObj[ "checkRc" ])
   qObj[ "gridLayout"         ]:addLayout_1(qObj[ "horizontalLayout_6" ], 0, 0, 1, 4)
   qObj[ "line_5"             ]:setFrameShape(4)
   qObj[ "line_5"             ]:setFrameShadow(48)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "line_5" ], 1, 0, 1, 4)
   qObj[ "labelProjects"      ]:setMaximumSize(QSize():new(52, 16777215))
   qObj[ "labelProjects"      ]:setAlignment(hb_bitOR(hb_bitOR(1,1),32))
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "labelProjects" ], 2, 0, 1, 1)
   qObj[ "listProjects"       ]:setMinimumSize(QSize():new(0, 60))
   qObj[ "listProjects"       ]:setMaximumSize(QSize():new(16777215, 60))
   qObj[ "listProjects"       ]:setEditTriggers(0)
   qObj[ "listProjects"       ]:setSelectionMode(2)
   qObj[ "listProjects"       ]:setSortingEnabled(.F.)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "listProjects" ], 2, 1, 1, 3)
   qObj[ "line_3"             ]:setFrameShape(4)
   qObj[ "line_3"             ]:setFrameShadow(48)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "line_3" ], 9, 0, 1, 4)
   qObj[ "labelExpr"          ]:setMaximumSize(QSize():new(52, 16777215))
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "labelExpr" ], 11, 0, 1, 1)
   qObj[ "comboExpr"          ]:setEditable(.T.)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "comboExpr" ], 11, 1, 1, 3)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "checkRegEx" ], 12, 1, 1, 1)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "checkMatchCase" ], 12, 2, 1, 1)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "checkListOnly" ], 12, 3, 1, 1)
   qObj[ "labelRepl"          ]:setMaximumSize(QSize():new(52, 16777215))
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "labelRepl" ], 13, 0, 1, 1)
   qObj[ "comboRepl"          ]:setEditable(.T.)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "comboRepl" ], 13, 1, 1, 3)
   qObj[ "line_4"             ]:setFrameShape(4)
   qObj[ "line_4"             ]:setFrameShadow(48)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "line_4" ], 14, 0, 1, 4)
   qObj[ "editResults"        ]:setLineWrapMode(0)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "editResults" ], 16, 0, 1, 4)
   qObj[ "labelStatus"        ]:setFrameShape(2)
   qObj[ "labelStatus"        ]:setFrameShadow(48)
   qObj[ "labelStatus"        ]:setWordWrap(.F.)
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "labelStatus" ], 17, 0, 1, 4)
   qObj[ "horizontalLayout_7" ]:addWidget(qObj[ "buttonFind" ])
   qObj[ "horizontalLayout_7" ]:addWidget(qObj[ "buttonRepl" ])
   qObj[ "horizontalLayout_7" ]:addWidget(qObj[ "buttonStop" ])
   qObj[ "horizontalLayout_7" ]:addWidget(qObj[ "buttonClose" ])
   qObj[ "gridLayout"         ]:addLayout_1(qObj[ "horizontalLayout_7" ], 15, 1, 1, 3)
   qObj[ "labelFolder"        ]:setMaximumSize(QSize():new(52, 16777215))
   qObj[ "gridLayout"         ]:addWidget_1(qObj[ "labelFolder" ], 4, 0, 1, 1)
   qObj[ "horizontalLayout_4" ]:addWidget(qObj[ "checkOpenTabs" ])
   qObj[ "horizontalLayout_4" ]:addItem(qObj[ "horizontalSpacer" ])
   qObj[ "horizontalLayout_4" ]:addWidget(qObj[ "checkSubProjects" ])
   qObj[ "gridLayout"         ]:addLayout_1(qObj[ "horizontalLayout_4" ], 3, 1, 1, 3)
   qObj[ "horizontalLayout_8" ]:addWidget(qObj[ "checkFolders" ])
   qObj[ "horizontalLayout_8" ]:addItem(qObj[ "horizontalSpacer_2" ])
   qObj[ "horizontalLayout_8" ]:addWidget(qObj[ "checkSubFolders" ])
   qObj[ "gridLayout"         ]:addLayout_1(qObj[ "horizontalLayout_8" ], 5, 1, 1, 3)
   qObj[ "FormFindInFilesEx"  ]:setWindowTitle(q__tr("FormFindInFilesEx", "Form", 0, "UTF8"))
   qObj[ "buttonFolder"       ]:setText( [...] )
   qObj[ "labelFileTypes"     ]:setText( [File types:] )
   qObj[ "checkAll"           ]:setText( [all] )
   qObj[ "checkPrg"           ]:setText( [.prg] )
   qObj[ "checkC"             ]:setText( [.c] )
   qObj[ "checkCpp"           ]:setText( [.c++] )
   qObj[ "checkCh"            ]:setText( [.ch] )
   qObj[ "checkH"             ]:setText( [.h] )
   qObj[ "checkRc"            ]:setText( [.rc] )
   qObj[ "labelProjects"      ]:setText( [Projects:] )
   qObj[ "labelExpr"          ]:setText( [Expression] )
   qObj[ "checkRegEx"         ]:setText( [RegEx] )
   qObj[ "checkMatchCase"     ]:setText( [Match case] )
   qObj[ "checkListOnly"      ]:setText( [List only] )
   qObj[ "labelRepl"          ]:setText( [Replace:] )
   qObj[ "labelStatus"        ]:setText( [] )
   qObj[ "buttonFind"         ]:setText( [Find] )
   qObj[ "buttonRepl"         ]:setText( [Replace] )
   qObj[ "buttonStop"         ]:setText( [Stop] )
   qObj[ "buttonClose"        ]:setText( [Close] )
   qObj[ "labelFolder"        ]:setText( [Folder:] )
   qObj[ "checkOpenTabs"      ]:setText( [Include open tabs ] )
   qObj[ "checkSubProjects"   ]:setText( [Include sub-projects] )
   qObj[ "checkFolders"       ]:setText( [Include folders] )
   qObj[ "checkSubFolders"    ]:setText( [Include sub-folders] )

   oUI         := HbQtUI():new()
   oUI:qObj    := qObj
   oUI:oWidget := oWidget

   RETURN oUI

/*----------------------------------------------------------------------*/

