#
# $Id$
#

ROOT = ../../

LIBNAME=hbole

ifeq ($(HB_ARCHITECTURE),w32)

C_SOURCES=\
	ole2.c \

PRG_SOURCES=\
	oleauto.prg \

include $(TOP)$(ROOT)config/lib.cf

else
include $(TOP)$(ROOT)config/none.cf
endif
