#
# $Id$
#

ROOT = ../../

LIBNAME=hbole

ifeq ($(HB_ARCHITECTURE),win)

C_SOURCES=\
	oleinit.c \
	olecore.c \

PRG_SOURCES=\
	oleauto.prg \

include $(TOP)$(ROOT)config/lib.cf

else
include $(TOP)$(ROOT)config/none.cf
endif
