#
# $Id$
#

ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

LIBNAME := hbfoxpro

PRG_SOURCES := \
   dll.prg \

PRG_HEADERS := \
   hbfoxpro.ch \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
