#
# $Id$
#

ifeq ($(HB_MAIN),)
   HB_MAIN := std
endif

ROOT := ../../

PRG_SOURCES := \
   hbformat.prg \

C_SOURCES := \
   hbformac.c \

PRG_MAIN := hbformat.prg

LIBS := \
   hbdebug \
   hbvm \
   hbrtl \
   hblang \
   hbcpage \
   hbnulrdd \
   hbrtl \
   hbvm \
   hbmacro \
   hbcommon \

include $(TOP)$(ROOT)config/bin.cf
