.TH HBMAKE 1

.SH NAME
hbmake \- Harbour Project Make Utility

.SH SYNOPSIS
\fBhbmake\fP \fBcFile\fP \fB[options]\fP

.SH DESCRIPTION
\fBhbmake\fP is the Harbour Project make utility.

.SH OPTIONS
.IP "\fB-e[x]\fP" 10
Create a new Makefile. If /ex is used it creates a new make file in extended mode
.IP "\fB-el[x]\fP" 10
Create a new Makefile. If /elx is used it creates a new make file to build a library in extended mode
.IP "\fB-D\fP" 10
Define a macro
.IP "\fB-p\fP" 10
Print all commands and depedencies
.IP "\fB-b\fP" 10
Use BCC as C compiler
.IP "\fB-g\fP" 10
Use GCC as C compiler
.IP "\fB-gl\fP" 10
Use GCC as C compiler in Linux
.IP "\fB-v\fP" 10
Use MSVC as C compiler
.IP "\fB-f\fP" 10
Force recompilation of all files
.IP "\fB-i\fP" 10
Ignore errors returned by command
.IP "\fB-r\fP" 10
Recurse Source Directory
.IP "\fB-l[LANGID]\fP" 10
Specify the language to be used on hbmake Texts LANGID = (EN/PT/ES). On Windows
System, the default will be the SO language if is found. Otherwise, will be English.
On OS/2;FreeBSD/LINUX the default is English


.SH AUTHOR

Author of hbmake: The Harbour Project (http://www.harbour-project.org)

This manual page was written by Luis Mayoral <mayoral@linuxadicto.org>,
for the Debian GNU/Linux system (but may be used by others).
