#
# $Id$
#

ifeq ($(HB_ARCHITECTURE),w32)

ROOT = ../../

C_SOURCES = \
	wincorec.c \
	_winbmp.c \
	_winbrsh.c \
	_wincall.c \
	_wincdlg.c \
	_winclpb.c \
	_wincomm.c \
	_wincret.c \
	_windate.c \
	_windc.c \
	_windir.c \
	_windlg.c \
	_windll.c \
	_windraw.c \
	_winfont.c \
	_wingdi.c \
	_winhead.c \
	_winicon.c \
	_winilst.c \
	_wininet.c \
	_winini.c \
	_winkbrd.c \
	_winlv.c \
	_winmain.c \
	_winmapi.c \
	_winmem.c \
	_winmenu.c \
	_winmeta.c \
	_winmisc.c \
	_winmmcap.c \
	_winmous.c \
	_winmsg.c \
	_winpen.c \
	_winprn.c \
	_winrect.c \
	_winreg.c \
	_winrgn.c \
	_winscrlb.c \
	_winserial.c \
	_winshell.c \
	_winsock.c \
	_winsys.c \
	_wintab.c \
	_wintbar.c \
	_wintext.c \
	_wintree.c \
	_winview.c \
	_winwnd.c \

PRG_SOURCES= \
	whatutil.prg \
	wincdlg.prg \
	wincomm.prg \
	wincore.prg \
	windebug.prg \
	winerror.prg \
	winini.prg \
	winrbar.prg \
	wintabs.prg \
	wintbar.prg \

PRG_HEADERS= \
	commctrl.ch \
	commdlg.ch \
	debug.ch \
	import.ch \
	sqltypes.ch \
	what32.ch \
	wingdi.ch \
	wininet.ch \
	winstruc.ch \
	wintypes.ch \
	winuser.ch \

LIBNAME=hbwhat32

include $(TOP)$(ROOT)config/lib.cf

endif
