#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	guestbk.prg \
	inifiles.prg \
	testcgi.prg \
	
PRG_MAIN=guestbk.prg

LIBS=\
	debug \
	vm \
	rtl \
	lang \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	common \

include $(TOP)$(ROOT)config/bin.cf
