#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	guestbk.prg \
        inifiles.prg \
        testcgi.prg \
	
PRG_MAIN=guestbk.prg

LIBS=\
        runner \
	tools \
        debug \
	rdd \
	vm \
	rdd \
	rtl \
	pp \
	common \
	macro \

include $(TOP)$(ROOT)config/bin.cf
