#
# $Id$
#

ROOT := ../../

HB_BUILD_WARN := no

C_SOURCES := \
   adler32.c \
   compress.c \
   crc32.c \
   deflate.c \
   gzio.c \
   infback.c \
   inffast.c \
   inflate.c \
   inftrees.c \
   trees.c \
   uncompr.c \
   zutil.c \

LIBNAME := hbzlib

include $(TOP)$(ROOT)config/lib.mk
