#
# $Id$
#

ROOT = ../../../

PRG_SOURCES=\
	hbrun.prg \
        external.prg \
	
PRG_MAIN=hbrun.prg

LIBS=\
        runner \
	tools \
        debug \
	rdd \
	vm \
	rdd \
	rtl \
	pp \

include $(TOP)$(ROOT)config/bin.cf
