#
# $Id$
#

ifeq ($(HB_MAIN),)
HB_MAIN = std
endif

ROOT = ../../../

PRG_SOURCES=\
	hbrun.prg \
        external.prg \

PRG_MAIN=hbrun.prg

LIBS=\
        runner \
	tools \
        debug \
	rdd \
	vm \
	rdd \
	rtl \
	pp \
	common \
	macro \

include $(TOP)$(ROOT)config/bin.cf
