#
# $Id$
#

ROOT = ../../

C_SOURCES = \
	addascii.c \
	asciisum.c \
	ascpos.c \
	atadjust.c \
	atnum.c \
	atrepl.c \
	bit1.c \
	bit2.c \
	bit3.c \
	charevod.c \
	charlist.c \
	charmirr.c \
	charmix.c \
	charone.c \
	charonly.c \
	charop.c \
	charrepl.c \
	charsort.c \
	charswap.c \
	count.c \
	ctc.c \
	ctmath.c \
	ctset.c \
	ctstr.c \
	ctchksum.c \
	ctcrypt.c \
	exponent.c \
	files.c \
	finan.c \
	ftoc.c \
	justify.c \
	keyset.c \
	math.c \
	misc1.c \
	num1.c \
	numat.c \
	pad.c \
	pos1.c \
	pos2.c \
	posdiff.c \
	print.c \
	range.c \
	relation.c \
	remove.c \
	replace.c \
	screen1.c \
	strdiff.c \
	strswap.c \
	tab.c \
	token1.c \
	token2.c \
	trig.c \
	wordrepl.c \
	wordtoch.c \

PRG_SOURCES= \
	color.prg \
	ct.prg \
	ctmisc.prg \
	datetime.prg \
	numconv.prg \
	screen2.prg \

LIBNAME=ct

include $(TOP)$(ROOT)config/lib.cf

