#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	addascii.c \
	asciisum.c \
	ascpos.c \
	atadjust.c \
	atnum.c \
	atrepl.c \
	charevod.c \
	charlist.c \
	charmirr.c \
	charop.c \
	charrepl.c \
	ctset.c \
	ctstr.c \
	ctchksum.c \
	ctchrmix.c \
	ctcolton.c \
	ctcrypt.c \
	ctposupp.c \
	token1.c \
	wordrepl.c \

PRG_SOURCES=\
	ctmisc.prg \

LIBNAME=ct3

include $(TOP)$(ROOT)config/lib.cf
