#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	ainstest.prg \
	and_or.prg \
	array16.prg \
	arrays.prg \
	asctest.prg \
	atest.prg \
	byref.prg \
	calling.prg \
	classes.prg \
	codebl2.prg \
	codebloc.prg \
	comments.prg \
	dates.prg \
	dates2.prg \
	debugtst.prg \
	docase.prg \
	dupvars.prg \
	empty.prg \
	errorsys.prg \
	fib.prg \
	fileio.prg \
	fornext.prg \
	fornext2.prg \
	guess.prg \
	hello.prg \
	ifelse.prg \
	ifinline.prg \
	initexit.prg \
	longstr.prg \
	mankala.prg \
	mathtest.prg \
	next.prg \
	nums.prg \
	objects.prg \
	operat.prg \
	procname.prg \
	recursiv.prg \
	returns.prg \
	rtl_test.prg \
	set_num.prg \
	set_test.prg \
	statfun.prg \
	statics.prg \
	strcmp.prg \
	strings.prg \
	strings2.prg \
	strings3.prg \
	strings4.prg \
	t1.prg \
	test.prg \
	test10.prg \
	testerro.prg \
	testid.prg \
	testinc.prg \
	testmem.prg \
	testtok.prg \
	transfrm.prg \
	val.prg \
	while.prg \

LIBS=\
	vm \
	rtl \
	tools \

include $(TOP)$(ROOT)config/test.cf
