#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	ainstest.prg \
	and_or.prg \
	array16.prg \
	arrayidx.prg \
	arrays.prg \
	arrindex.prg \
	asctest.prg \
	atest.prg \
	box.prg \
	byref.prg \
	calling.prg \
	cdow.prg \
	clasinit.prg \
	classes.prg \
	cmphello.prg \
	codebl.prg \
	codebl2.prg \
	codebloc.prg \
	comments.prg \
	dates.prg \
	dates2.prg \
	dates3.prg \
	debugtst.prg \
	descend.prg \
	dirtest.prg \
	docase.prg \
	dosshell.prg \
	dynobj.prg \
	empty.prg \
	errorsys.prg \
	exittest.prg \
	fib.prg \
	fileio.prg \
	filexist.prg \
	fornext.prg \
	fornext2.prg \
	funcarr.prg \
	guess.prg \
	hardcr.prg \
	hello.prg \
	ifelse.prg \
	ifinline.prg \
	inherit.prg \
	inifiles.prg \
	initexit.prg \
	inline.prg \
	instr.prg \
	iotest.prg \
	iotest2.prg \
	longstr.prg \
	mankala.prg \
	mathtest.prg \
	mtran.prg \
	multiarg.prg \
	nums.prg \
	objarr.prg \
	objasign.prg \
	objects.prg \
	operat.prg \
	os.prg \
	output.prg \
	overload.prg \
	passref.prg \
	procname.prg \
	readhrb.prg \
	recursiv.prg \
	returns.prg \
	round.prg \
	rtfclass.prg \
	rtl_test.prg \
	scroll.prg \
	seconds.prg \
	set_num.prg \
	set_test.prg \
	statfun.prg \
	statics.prg \
	strcmp.prg \
	strdelim.prg \
	strings.prg \
	strings2.prg \
	strings3.prg \
	strings4.prg \
	strip.prg \
	t1.prg \
	test.prg \
	test_all.prg \
	testcgi.prg \
	testcopy.prg \
	testerro.prg \
	testfor.prg \
	testgt.prg \
	testhbf.prg \
	testhtml.prg \
	testinc.prg \
	testmem.prg \
	teststr.prg \
	testtok.prg \
	testvars.prg \
	testwarn.prg \
	transfrm.prg \
	val.prg \
	version.prg \
	while.prg \


BAD_PRG_SOURCES=\
	dupvars.prg \
	keywords.prg \
	spawn.prg \
	spawn2.prg \
	keywords.prg \
	linecont.prg \
	test10.prg \
	testid.prg \

LIBS=\
	vm \
	rtl \
	tools \

include $(TOP)$(ROOT)config/test.cf
