// Testing Harbour device management.

#include "set.ch"
#define cNewLine CHR( 13 ) + CHR( 10 )

function Main()

   OUTSTD (cNewLine,  "Testing Harbour device management on", DATE())
   SET ALTERNATE TO OUTPUT ADDITIVE
   SET PRINTER TO OUTPUT ADDITIVE
   QOUT ("SCREEN, NOT ALTERNATE, NOT PRINTER")
   @ 5,5 SAY "SCREEN, NOT ALTERNATE NOT PRINTER"
   SET ALTERNATE ON
   SET PRINTER ON
   QOUT ("SCREEN, ALTERNATE AND PRINTER")
   @ 10,10 SAY "SCREEN, NOT ALTERNATE, NOT PRINTER"
   SET DEVICE TO PRINTER
   QOUT ("SCREEN, ALTERNATE AND PRINTER AGAIN")
   SET PRINTER OFF
   QOUT ("SCREEN AND ALTERNATE, BUT NOT PRINTER")
   @ 15,15 SAY "PRINTER, NOT SCREEN, NOT ALTERNATE"
   EJECT

return nil
