// Testing SET

#include "set.ch"

function Main()
local NEWLINE := CHR (13) + CHR (10)

   outstd (NEWLINE)
   outstd (set (_SET_ALTERNATE))
   outstd (NEWLINE)
   outstd (set (_SET_ALTFILE))
   outstd (NEWLINE)
   outstd (set (_SET_BELL))
   outstd (NEWLINE)
   outstd (set (_SET_CANCEL))
   outstd (NEWLINE)
   outstd (set (_SET_COLOR))
   outstd (NEWLINE)
   outstd (set (_SET_CONFIRM))
   outstd (NEWLINE)
   outstd (set (_SET_CONSOLE))
   outstd (NEWLINE)
   outstd (set (_SET_CURSOR))
   outstd (NEWLINE)
   outstd (set (_SET_DATEFORMAT))
   outstd (NEWLINE)
   outstd (set (_SET_DEBUG))
   outstd (NEWLINE)
   outstd (set (_SET_DECIMALS))
   outstd (NEWLINE)
   outstd (set (_SET_DEFAULT))
   outstd (NEWLINE)
   outstd (set (_SET_DELETED))
   outstd (NEWLINE)
   outstd (set (_SET_DELIMCHARS))
   outstd (NEWLINE)
   outstd (set (_SET_DELIMITERS))
   outstd (NEWLINE)
   outstd (set (_SET_DEVICE))
   outstd (NEWLINE)
   outstd (set (_SET_EPOCH))
   outstd (NEWLINE)
   outstd (set (_SET_ESCAPE))
   outstd (NEWLINE)
   outstd (set (_SET_EVENTMASK))
   outstd (NEWLINE)
   outstd (set (_SET_EXACT))
   outstd (NEWLINE)
   outstd (set (_SET_EXCLUSIVE))
   outstd (NEWLINE)
   outstd (set (_SET_EXIT))
   outstd (NEWLINE)
   outstd (set (_SET_EXTRA))
   outstd (NEWLINE)
   outstd (set (_SET_EXTRAFILE))
   outstd (NEWLINE)
   outstd (set (_SET_FIXED))
   outstd (NEWLINE)
   outstd (set (_SET_INSERT))
   outstd (NEWLINE)
   outstd (set (_SET_INTENSITY))
   outstd (NEWLINE)
   outstd (set (_SET_MARGIN))
   outstd (NEWLINE)
   outstd (set (_SET_MCENTER))
   outstd (NEWLINE)
   outstd (set (_SET_MESSAGE))
   outstd (NEWLINE)
   outstd (set (_SET_PATH))
   outstd (NEWLINE)
   outstd (set (_SET_PRINTER))
   outstd (NEWLINE)
   outstd (set (_SET_PRINTFILE))
   outstd (NEWLINE)
   outstd (set (_SET_SCOREBOARD))
   outstd (NEWLINE)
   outstd (set (_SET_SCROLLBREAK))
   outstd (NEWLINE)
   outstd (set (_SET_SOFTSEEK))
   outstd (NEWLINE)
   outstd (set (_SET_TYPEAHEAD))
   outstd (NEWLINE)
   outstd (set (_SET_UNIQUE))
   outstd (NEWLINE)
   outstd (set (_SET_WRAP))

return nil
