/* encoding: cp850 */
#INCLUDE "cua.ch"
#INCLUDE "gtnap.ch"
#INCLUDE "hboffice.ch"

***********************************
PROC TST_R00044
***********************************
LOCAL O_DOC := HBOFFICE_DOC_CREATE()

// Total chars by line
LOCAL N_Width := 80

// Field tabulations
LOCAL V_Tabs := {45, HBOFFICE_HALIGN_LEFT, 17, HBOFFICE_HALIGN_RIGHT, 18, HBOFFICE_HALIGN_RIGHT}
LOCAL C_Line := ""

IF OFFICE_ERROR("Erro ao criar documento de texto")
    RETURN
ENDIF

// Header, footer and page margins config
HBOFFICE_DOC_PAGE_HEADER_SHOW(O_DOC, .T.)
HBOFFICE_DOC_PAGE_HEADER_MARGINS(O_DOC, 254, 280, 508, 102, .T., .T.)
HBOFFICE_DOC_PAGE_FOOTER_SHOW(O_DOC, .T.)
HBOFFICE_DOC_PAGE_FOOTER_MARGINS(O_DOC, 354, 380, 608, 202, .T., .T.)
HBOFFICE_DOC_PAGE_MARGINS(O_DOC, 2819, 178, 1270, 533, 0)

// Create and empty header with some line breaks
HBOFFICE_DOC_TEXT_SPACE(O_DOC, HBOFFICE_TEXT_SPACE_HEADER)
HBOFFICE_DOC_FONT_FAMILY(O_DOC, "Times New Roman")
HBOFFICE_DOC_FONT_SIZE(O_DOC, 10.0)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

// Set the text space to main page
HBOFFICE_DOC_TEXT_SPACE(O_DOC, HBOFFICE_TEXT_SPACE_PAGE)
HBOFFICE_DOC_FONT_FAMILY(O_DOC, "Courier New")
HBOFFICE_DOC_FONT_SIZE(O_DOC, 10.0)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Ceará")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Governo Municipal de Piquet Carneiro                                Página: 0001")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Total de Benefício(s) Pendente(s)")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

HBOFFICE_DOC_INSERT_PARAGRAPH(O_DOC)
HBOFFICE_DOC_PARAGRAPH_HALIGN(O_DOC, HBOFFICE_HALIGN_CENTER)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Período: 01/01/1997 a 18/01/2024")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

HBOFFICE_DOC_INSERT_PARAGRAPH(O_DOC)
HBOFFICE_DOC_PARAGRAPH_HALIGN(O_DOC, HBOFFICE_HALIGN_LEFT)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Beneficiário____: MARIA VIVIANE ALVES QUIRINO")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Entidade doadora:     -")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Código Descrição", "Quant.", "Valor R$"}, V_Tabs)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"098710 CESTA BÁSICA", 1.00, 107.29}, V_Tabs)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Total dos Benefícios Pendentes_______:", 1.00, 107.29}, V_Tabs)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Beneficiário____: DEURISVAN LEMOS DE FREITAS")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Entidade doadora:     -")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Código Descrição", "Quant.", "Valor R$"}, V_Tabs)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"098710 CESTA BÁSICA", 1.00, 107.29}, V_Tabs)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Total dos Benefícios Pendentes_______:", 1.00, 107.29}, V_Tabs)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Beneficiário____: ALOIZIO RODRIGUES COSTA")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Entidade doadora:     -")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Código Descrição", "Quant.", "Valor R$"}, V_Tabs)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"098710 CESTA BÁSICA", 1.00, 81.22}, V_Tabs)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Total dos Benefícios Pendentes_______:", 1.00, 81.22}, V_Tabs)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Beneficiário____: ROZILDA RODRIGUES DE MELO")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Entidade doadora:     -")
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Código Descrição", "Quant.", "Valor R$"}, V_Tabs)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"098710 CESTA BÁSICA", 1.00, 81.22}, V_Tabs)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Total dos Benefícios Pendentes_______:", 1.00, 81.22}, V_Tabs)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOCUMENT1_TABLINE(O_DOC, {"Total Geral dos Benefícios Pendentes___:", 4.00, 377.02}, V_Tabs)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)

// Save the document
HBOFFICE_DOC_SAVE(O_DOC, {|| NAP_WORK_PATH() + "/../office/ods_gen/Exemple_R00044.odt" })
OFFICE_ERROR("Erro ao salvar documento de texto")

// Export to PDF
HBOFFICE_DOC_PDF(O_DOC, {|| NAP_WORK_PATH() + "/../office/ods_gen/Exemple_R00044.pdf" })
OFFICE_ERROR("Exportando para PDF")

// Close the document (mandatory)
HBOFFICE_DOC_CLOSE(O_DOC)
OFFICE_ERROR("Erro ao fechar o documento de texto")

MOSTRAR("M15566", "O documento de texto foi criado com sucesso.")

// Open the result into a LibreOffice window
HBOFFICE_BROWSE_DOC(NAP_WORK_PATH() + "/../office/ods_gen/Exemple_R00044.odt")
