/* encoding: cp850 */
#INCLUDE "cua.ch"
#INCLUDE "gtnap.ch"
#INCLUDE "hboffice.ch"

***********************************************************
STAT PROC DOCUMENT3_HEADER(O_DOC, N_Page)
***********************************************************
    HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Ceará")
    HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
    HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Governo Municipal de Piquet Carneiro                              ")
    HBOFFICE_DOC_INSERT_TEXT(O_DOC, PAGINA_TEXT(N_Page))
    HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
    HBOFFICE_DOC_INSERT_TEXT(O_DOC, "Relatório de bens depreciados")
    HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

***********************************
PROC TST_R02680
***********************************
LOCAL O_DOC := HBOFFICE_DOC_CREATE()
LOCAL N_Page := 1
LOCAL N_Width := 80
LOCAL V_Tabs := {7, HBOFFICE_HALIGN_LEFT, 42, HBOFFICE_HALIGN_LEFT, 14, HBOFFICE_HALIGN_RIGHT, 17, HBOFFICE_HALIGN_RIGHT}

IF OFFICE_ERROR("Erro ao criar documento de texto")
    RETURN
ENDIF

// Header, footer and page margins config
HBOFFICE_DOC_PAGE_HEADER_SHOW(O_DOC, .T.)
HBOFFICE_DOC_PAGE_HEADER_MARGINS(O_DOC, 254, 280, 508, 102, .T., .T.)
HBOFFICE_DOC_PAGE_FOOTER_SHOW(O_DOC, .T.)
HBOFFICE_DOC_PAGE_FOOTER_MARGINS(O_DOC, 354, 380, 608, 202, .T., .T.)
HBOFFICE_DOC_PAGE_MARGINS(O_DOC, 2819, 178, 1270, 533, 0)

// Create and empty header with some line breaks
HBOFFICE_DOC_TEXT_SPACE(O_DOC, HBOFFICE_TEXT_SPACE_HEADER)
HBOFFICE_DOC_FONT_FAMILY(O_DOC, "Times New Roman")
HBOFFICE_DOC_FONT_SIZE(O_DOC, 10.0)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)
HBOFFICE_DOC_INSERT_NEW_LINE(O_DOC)

// Set the text space to main page
HBOFFICE_DOC_TEXT_SPACE(O_DOC, HBOFFICE_TEXT_SPACE_PAGE)
HBOFFICE_DOC_FONT_FAMILY(O_DOC, "Courier New")
HBOFFICE_DOC_FONT_SIZE(O_DOC, 10.0)
HBOFFICE_DOC_PARAGRAPH_LSPACING(O_DOC, 330)

// Page 1
DOCUMENT3_HEADER(O_DOC, N_Page)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Período_____________: 01/01/2023 a 31/01/2023")
DOC_LINE(O_DOC, "Grupo_______________: Consolidado")
DOC_LINE(O_DOC, "Ordem_______________: Numérica")
DOC_LINE(O_DOC, "Dados_______________: Analítico")
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Und. Gestora: 02  - Câmara Municipal de Piquet Carneiro")
DOC_LINE(O_DOC, "Orgão_______: 01  - Câmara Municipal de Piquet Carneiro")
DOC_LINE(O_DOC, "Área________: 134 - CÂMARA MUNICIPAL DE PIQUET CARNEIRO")
DOC_LINE(O_DOC, "Subárea_____: 739 - PLENARIO VER.ISRAEL HENRIQUE DE SOUSA")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA DO 2º BIÊNIO 2013/2016")
DOC_LINE(O_DOC, "Tombamento nº________: 10000161         Data de aquisição____: 07/07/2022")
DOC_LINE(O_DOC, "Data tombamento______: 01/09/2022       Valor residual_______: R$        58,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/10/2022       Valor Liq. contábil__: R$       523,45")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,35")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA BIÊNIO 2017/2018")
DOC_LINE(O_DOC, "Tombamento nº________: 10000162         Data de aquisição____: 06/07/2022")
DOC_LINE(O_DOC, "Data tombamento______: 01/09/2022       Valor residual_______: R$        58,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/10/2022       Valor Liq. contábil__: R$       523,45")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,35")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA MESA DIRETORA QUADRIÊNIO 2021/2022")
DOC_LINE(O_DOC, "Tombamento nº________: 10000163         Data de aquisição____: 06/07/2022")
DOC_LINE(O_DOC, "Data tombamento______: 01/09/2022       Valor residual_______: R$        58,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/10/2022       Valor Liq. contábil__: R$       523,45")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,35")
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Und. Gestora: 02  - Câmara Municipal de Piquet Carneiro")
DOC_LINE(O_DOC, "Orgão_______: 01  - Câmara Municipal de Piquet Carneiro")
DOC_LINE(O_DOC, "Área________: 134 - CÂMARA MUNICIPAL DE PIQUET CARNEIRO")
DOC_LINE(O_DOC, "Subárea_____: 740 - PLENÁRIO")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: CADEIRA DE PALHINHA")
DOC_LINE(O_DOC, "Tombamento nº________: 10000004         Data de aquisição____: 02/02/1998")
DOC_LINE(O_DOC, "Data tombamento______: 10/06/2015       Valor residual_______: R$        15,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$        37,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         1,13")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: CADEIRA DE PALHINHA")
DOC_LINE(O_DOC, "Tombamento nº________: 10000005         Data de aquisição____: 02/02/1998")
DOC_LINE(O_DOC, "Data tombamento______: 10/06/2015       Valor residual_______: R$        15,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$        37,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         1,13")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA 1993/1996")
DOC_LINE(O_DOC, "Tombamento nº________: 10000022         Data de aquisição____: 02/04/1993")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        46,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       115,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         3,45")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA 1997/2000")
DOC_LINE(O_DOC, "Tombamento nº________: 10000023         Data de aquisição____: 02/04/1997")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        50,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       125,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         3,75")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA BIÊNIO 1999 A 2000")
HBOFFICE_DOC_INSERT_PAGE_BREAK(O_DOC)

// Page 2
N_Page := 2
DOCUMENT3_HEADER(O_DOC, N_Page)
DOCUMENT1_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Tombamento nº________: 10000025         Data de aquisição____: 03/03/1999")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        50,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       125,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         3,75")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA BIÊNIO 2001/2002")
DOC_LINE(O_DOC, "Tombamento nº________: 10000026         Data de aquisição____: 02/04/2001")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        54,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       135,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,05")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA DO BIÊNIO 2003/2004")
DOC_LINE(O_DOC, "Tombamento nº________: 10000027         Data de aquisição____: 07/04/2003")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        57,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       142,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,28")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA BIÊNIO 2005/2008")
DOC_LINE(O_DOC, "Tombamento nº________: 10000028         Data de aquisição____: 29/04/2005")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        57,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       142,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,28")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA BIÊNIO 2005/2008 (1º BIÊNIO)")
DOC_LINE(O_DOC, "Tombamento nº________: 10000029         Data de aquisição____: 29/04/2015")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        57,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       142,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,28")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA 2009/2012 (BIÊNIO 2009/2010)")
DOC_LINE(O_DOC, "Tombamento nº________: 10000030         Data de aquisição____: 27/07/2009")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        59,90")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       150,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,49")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA 2009/2012 (BIÊNIO 2011/2012)")
DOC_LINE(O_DOC, "Tombamento nº________: 10000031         Data de aquisição____: 27/07/2009")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        59,90")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       150,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         4,49")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: GALERIA 2013/2016 (BIÊNIO 2015/2016)")
DOC_LINE(O_DOC, "Tombamento nº________: 10000035         Data de aquisição____: 10/04/2015")
DOC_LINE(O_DOC, "Data tombamento______: 12/06/2015       Valor residual_______: R$        70,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/07/2015       Valor Liq. contábil__: R$       175,00")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         5,25")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: EVAPORADOR 9K BTU CF SPLIT CL A")
DOC_LINE(O_DOC, "Tombamento nº________: 10000104         Data de aquisição____: 11/09/2015")
DOC_LINE(O_DOC, "Data tombamento______: 11/09/2015       Valor residual_______: R$        37,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/10/2015       Valor Liq. contábil__: R$       100,34")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         2,78")
DOCUMENT2_SEPARATOR(O_DOC, N_Width)
DOC_LINE(O_DOC, "Patrimônio___________: CONDICIONADOR DE AR 9K BTU CF SPLIT CL A")
DOC_LINE(O_DOC, "Tombamento nº________: 10000105         Data de aquisição____: 11/09/2015")
DOC_LINE(O_DOC, "Data tombamento______: 11/09/2015       Valor residual_______: R$        85,00")
DOC_LINE(O_DOC, "Data de inic. deprec.: 01/10/2015       Valor Liq. contábil__: R$       231,14")
DOC_LINE(O_DOC, "Vida útil____________:  10 ano(s).      Depreciação acumulada: R$         6,38")
HBOFFICE_DOC_INSERT_PAGE_BREAK(O_DOC)


// Save the document
HBOFFICE_DOC_SAVE(O_DOC, {|| NAP_WORK_PATH() + "/../office/ods_gen/Exemple_R02680.odt" })
OFFICE_ERROR("Erro ao salvar documento de texto")

// Export to PDF
HBOFFICE_DOC_PDF(O_DOC, {|| NAP_WORK_PATH() + "/../office/ods_gen/Exemple_R02680.pdf" })
OFFICE_ERROR("Exportando para PDF")

// Close the document (mandatory)
HBOFFICE_DOC_CLOSE(O_DOC)
OFFICE_ERROR("Erro ao fechar o documento de texto")

MOSTRAR("M15566", "O documento de texto foi criado com sucesso.")

// Open the result into a LibreOffice window
HBOFFICE_BROWSE_DOC(NAP_WORK_PATH() + "/../office/ods_gen/Exemple_R02680.odt")
