/* encoding: cp850 */
#ifndef MOUSECUA_CH
#define MOUSECUA_CH

*
* regi∆o onde o mouse se encontra
*
#DEFINE BUSCANDO_REGIAO        100   // define que busca est† em andamento
#DEFINE ACIMA_UMA_LINHA        200
#DEFINE ACIMA_UMA_PAGINA       220
#DEFINE ACIMA_TOTAL            240
#DEFINE ABAIXO_UMA_LINHA       300
#DEFINE ABAIXO_UMA_PAGINA      320
#DEFINE ABAIXO_TOTAL           340
#DEFINE ESQUERDA_UMA_COLUNA    400
#DEFINE ESQUERDA_UMA_PAGINA    420
#DEFINE ESQUERDA_TOTAL         440
#DEFINE DIREITA_UMA_COLUNA     500
#DEFINE DIREITA_UMA_PAGINA     520
#DEFINE DIREITA_TOTAL          540
#DEFINE BOTAO_IDENTIFICADO     600
#DEFINE BOTAO_NAO_IDENTIFICADO 700
#DEFINE SOBRE_IMAGEM           760
#DEFINE AREA_UTIL              800
#DEFINE REGIAO_SEM_EVENTO      900   // dentro da Janela, mas local n∆o ativo
#DEFINE FORA_DA_JANELA        1000   // fora da janela

#endif