/* LibreOffice-SDK C-wrapper */

#ifndef __OFFICESDK_HXX__
#define __OFFICESDK_HXX__

#include <core/core.hxx>

typedef struct _sheet_t Sheet;

typedef enum _sdkres_t
{
    ekSDKRES_OK     = 1,
    ekSDKRES_NO_ENVAR,
    ekSDKRES_PROC_KILL_FAIL,
    ekSDKRES_PROC_INIT_FAIL,
    ekSDKRES_CONECT_FAIL,
    ekSDKRES_COMPONENT_LOADER,
    ekSDKRES_CREATE_FILE_ERROR,
    ekSDKRES_OPEN_FILE_ERROR,
    ekSDKRES_SAVE_FILE_ERROR,
    ekSDKRES_CLOSE_DOC_ERROR,
    ekSDKRES_ACCESS_DOC_ERROR,
    ekSDKRES_ACCESS_CELL_ERROR,
    ekSDKRES_EDIT_CELL_ERROR,
    ekSDKRES_FORMAT_CELL_ERROR,
    ekSDKRES_ACCESS_COLUMN_ERROR,
    ekSDKRES_FORMAT_COLUMN_ERROR,
    ekSDKRES_ACCESS_ROW_ERROR,
    ekSDKRES_FORMAT_ROW_ERROR
} sdkres_t;

typedef enum _numformat_t
{
    ekNUMFORMAT_INT         = 1,
    ekNUMFORMAT_INT_1000,    
    ekNUMFORMAT_DEC2,
    ekNUMFORMAT_DEC2_1000,
    ekNUMFORMAT_PERC_INT,
    ekNUMFORMAT_PERC_DEC2
} numformat_t;

typedef enum _linestyle_t
{
    ekLINE_STYLE_NONE = 1,
    ekLINE_STYLE_SOLID,
    ekLINE_STYLE_DOTTED,
    ekLINE_STYLE_DASHED,
    ekLINE_STYLE_DOUBLE,
    ekLINE_STYLE_THINTHICK_SMALLGAP,
    ekLINE_STYLE_THINTHICK_MEDIUMGAP,
    ekLINE_STYLE_THINTHICK_LARGEGAP,
    ekLINE_STYLE_THICKTHIN_SMALLGAP,
    ekLINE_STYLE_THICKTHIN_MEDIUMGAP,
    ekLINE_STYLE_THICKTHIN_LARGEGAP,
    ekLINE_STYLE_EMBOSSED,
    ekLINE_STYLE_ENGRAVED,
    ekLINE_STYLE_OUTSET, 
    ekLINE_STYLE_INSET,
    ekLINE_STYLE_FINE_DASHED,
    ekLINE_STYLE_DOUBLE_THIN,
    ekLINE_STYLE_DASH_DOT,
    ekLINE_STYLE_DASH_DOT_DOT
} linestyle_t;

typedef enum _fileformat_t
{
    ekFORMAT_OPEN_OFFICE,
    ekFORMAT_PDF
} fileformat_t;

#endif
