#
# $Id$
#

ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

LIBNAME := hbcairo

C_SOURCES := \
   context.c \
   core.c \
   image.c \
   paths.c \
   pdf.c \
   png.c \
   text.c \

PRG_SOURCES := \

C_HEADERS := \
   hbcairo.h \

PRG_HEADERS := \
   hbcairo.ch \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
