#
# $Id$
#

ROOT = ../../

C_SOURCES=\
        asciisum.c \
        ascpos.c \
        atdiff.c \
        chareven.c \
        charmix.c \
        charodd.c \
        chrcount.c \
        chrfirst.c \
        chrtotal.c \
        ctchksum.c \
        ctchrmix.c \
        ctcrypt.c \
        dates2.c \
        datesx.c \
        dbftools.c \
        hb_f.c \
        io.c \
        mathx.c \
        strasint.c \
        strcount.c \
        strcspn.c \
        strdiff.c \
        strexpan.c \
        strfmt.c \
        stringsx.c \
        strleft.c \
        strpbrk.c \
        strright.c \

PRG_SOURCES=\
        fileread.prg \
        html.prg \
        nconvert.prg \
        ng.prg \
        numtxthu.prg \
        numtxten.prg \
        os2.prg \
        rtf.prg \
        stringp.prg \
        troff.prg \

LIBNAME=tools

include $(TOP)$(ROOT)config/lib.cf
