#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	asciisum.c \
	ascpos.c \
	atdiff.c \
	chareven.c \
	charmix.c \
	charodd.c \
	chrcount.c \
	chrfirst.c \
	chrtotal.c \
        dates2.c \
	datesx.c \
	debug.c \
	hb_f.c \
	io.c \
	mathx.c \
	strasint.c \
	strcount.c \
	strcspn.c \
	strdiff.c \
	strexpan.c \
        strfmt.c \
	stringsx.c \
	strleft.c \
	strpbrk.c \
	strright.c \

PRG_SOURCES=\
	fileread.prg \
        numtxthu.prg \
        numtxten.prg \
	stringp.prg \

LIB=tools

include $(TOP)$(ROOT)config/lib.cf
