#
# $Id$
#

ROOT = ../../../

C_SOURCES=\
	gtcrs.c \
	mousecrs.c \
   kbdcrs.c \

PRG_SOURCES=\
	keymap.prg

PRG_HEADERS=\
	eterm.map \
	linux.map \

LIBNAME=gtcrs

include $(TOP)$(ROOT)config/lib.cf
