#
# $Id$
#

ifeq ($(HB_MAIN),)
   HB_MAIN := std
endif

ROOT := ../../

PRG_SOURCES := \
   hbpptest.prg \

PRG_MAIN := hbpptest.prg

LIBS := \
   hbdebug \
   hbvm \
   hbrtl \
   hblang \
   hbcpage \
   hbrdd \
   hbrtl \
   hbvm \
   hbmacro \
   hbpp \
   hbcommon \

include $(TOP)$(ROOT)config/bin.cf
