#
# $Id$
#

ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

LIBNAME := hbbzip2

C_SOURCES := \
   hbbzip2.c \

PRG_HEADERS := \
   hbbzip2.ch

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
