#
# $Id$
#

ROOT := ../../

C_SOURCES := \
	asciisgt.c \
	ascposgt.c \
	atdiff.c \
	chareven.c \
	charmixg.c \
	charodd.c \
	chrcount.c \
	chrfirst.c \
	chrtotal.c \
	strasint.c \
	strcount.c \
	strcspn.c \
	strdiffg.c \
	strexpan.c \
	strleft.c \
	strpbrk.c \
	strright.c \

LIBNAME := hbgt

include $(TOP)$(ROOT)config/lib.cf
