#
# $Id$
#

ROOT = ../../../

C_SOURCES=\
	creawin.c \
	general.c \
	creamenu.c \
	creabutt.c \
	dispatch.c \
	msginfo.c \

PRG_SOURCES=\
	form.prg    \
	menu.prg    \
	button.prg    \
	menuitem.prg \
	winctrl.prg \


LIBNAME=hbgtk

include $(TOP)$(ROOT)config/lib.cf

