#
# $Id$
#

ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

LIBNAME := hbfship

C_SOURCES := \
   secondfs.c \
   strpeek.c \

PRG_SOURCES := \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
