#
# $Id$
#

ROOT = ../../../

PRG_SOURCES=\
	editorhi.prg \
	
C_SOURCES=\
	editorlo.c \

PRG_MAIN=pe.prg

LIBS=\
	debug \
	vm \
	rtl \
	lang \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	dbfntx \
	dbfcdx \
	dbffpt \
	hbsix \
	common \

include $(TOP)$(ROOT)config/bin.cf
