# $ID$
# Makefile for DOS DJGPP
#
# NOTE: use it with -r option
#
include ..\..\makedos.env

TARGET=$(HARBOURDIR)/bin/harbour.exe

all: $(TARGET)

$(TARGET): harboury.c harbour.c harbourl.c
	$(CC) $(CFLAGS) harboury.c harbour.c harbourl.c -o $(TARGET)

harboury.c : harbour.y
	bison -d -v -y harbour.y -o harboury.c

harbourl.c : harbour.l
	flex -i -8 -oharbourl.c harbour.l

clean:
	-del *.o 
	-del harboury.*
	-del harbourl.c
	-del *.out
