#
# $Id$
#

ROOT = ../../

#LEX_FLAGS = -Phb_comp -C
#LEX_SOURCE=harbour.l
#LEX_HEADERS=\
#	hbsetup.h \
#	hberrors.h \
#	hbdefs.h

#YACC_FLAGS = -p hb_comp
YACC_SOURCE=harbour.y
YACC_HEADERS=\
	hbcomp.h   \
	hbcompdf.h \
	hbsetup.h  \
	hbpcode.h  \
	hbdefs.h   \
	hberrors.h \
	hbpp.h

C_SOURCES=\
	cmdcheck.c \
	genc.c     \
	gencc.c    \
	gencobj.c  \
	genhrb.c   \
	genjava.c  \
	genobj32.c \
	gencli.c   \
	hbcomp.c   \
	hbfunchk.c \
	hbgenerr.c \
	hbpcode.c  \
	hbfix.c    \
	hbdead.c   \
	hblbl.c    \
	hbopt.c    \
	hbstripl.c \
	hbusage.c  \
	hbident.c  \
	ppcomp.c   \
	expropta.c \
	exproptb.c \
	complex.c  \
	hbmain.c \

LIBNAME=compiler
include $(TOP)$(ROOT)config/lib.cf
