#
# $Id$
#

ROOT = ../

DOC_FILES=\
	c_std.txt \
	class_tp.txt \
	cmdline.txt \
	cmpopt.txt \
	codebloc.txt \
	codestyl.txt \
	destruct.txt \
	dirstruc.txt \
	funclist.txt \
	gmake.txt \
	gtapi.txt \
	hbmake.txt \
	hdr_tpl.txt \
	howtobld.txt \
	howtobsd.txt \
	howtomak.txt \
	howtorel.txt \
	howtosvn.txt \
	hrb_faq.txt \
	inet.txt \
	lang_id.txt \
	license.txt \
	linux1st.txt \
	pcode.txt \
	pp.txt \
	pragma.txt \
	readme.txt \
	statics.txt \
	tracing.txt \
	transfrm.txt \
	vm.txt \
	whatsnew.txt \
	windll.txt \

DIRS=\
	en \
	es \

include $(TOP)$(ROOT)config/doc.cf
include $(TOP)$(ROOT)config/dir.cf
