#
# $Id$
#

ROOT := ../

DOC_FILES := \
   c_std.txt \
   class_tp.txt \
   clipper.txt \
   cmdline.txt \
   cmpopt.txt \
   codebloc.txt \
   codestyl.txt \
   destruct.txt \
   dirstruc.txt \
   gmake.txt \
   gtapi.txt \
   hdr_tpl.txt \
   howtorel.txt \
   howtosvn.txt \
   inet.txt \
   locks.txt \
   pcode.txt \
   pp.txt \
   pragma.txt \
   readme.txt \
   statics.txt \
   tracing.txt \
   transfrm.txt \
   vm.txt \
   windll.txt \
   xhb-diff.txt \

include $(TOP)$(ROOT)config/doc.mk
