# makefile for Borland C/C++ 32 bits

PROJECT: hbpp.exe

hbpp.exe : hbpp.c harb.c table.c
   bcc32  -O2 -I\borland\cbuilder\include hbpp.c harb.c table.c
   del hbpp.obj
   del harb.obj
   del table.obj