#
# $Id$
#

ROOT = ../../

C_SOURCES=\
        hbpp.c \
        hbppint.c \
        hbpplib.c \
        table.c \

LIB=hbpp

DIRS=\
	stdalone \

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf

#
# This is for building the stand-alone preprocessor.
#
#C_MAIN=hbppmain.c
#
#include $(TOP)$(ROOT)config/bin.cf
#
