#
# $Id$
#

ROOT = ../../

C_SOURCES=\
        hbpp.c \
        hbppint.c \
        hbpplib.c \
        table.c \

LIB=hbpp

DIRS=\
	stdalone \

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
