#
# $Id$
#

ROOT = ../../../

C_SOURCES=\
	os2pm.c \

PRG_SOURCES=\
	tform.prg    \
	tmenu.prg    \
	tmenuitm.prg \
	winctrl.prg  \
	button.prg   \
	edit.prg     \
	

LIBNAME=hbgfos2pm

include $(TOP)$(ROOT)config/lib.cf

