#
# $Id$
#

# Needs Windows official ddraw.h to be copied to this directory, 
# in order to compile under MingW. [vszakats]

ifeq ($(HB_ARCHITECTURE),w32)

ROOT = ../../

CPP_SOURCES=\
	w32_ddrw.cpp \

PRG_SOURCES=\

LIBNAME=hbw32ddr

include $(TOP)$(ROOT)config/lib.cf

C_USR += -I.

endif
