#
# $Id$
#

ROOT = ../../

DOC_SUBDIR=/es

DOC_FILES=\
	array.txt \
	binnum.txt \
	browse.txt \
	clipper.txt \
	cmdline.txt \
	codebloc.txt \
	command.txt \
	compiler.txt \
	datetime.txt \
	dbdelim.txt \
	dbsdf.txt \
	dbstrux.txt \
	dir.txt \
	dirstruc.txt \
	diskspac.txt \
	error.txt \
	eval.txt \
	garbage.txt \
	harbext.txt \
	hb_set.txt \
	hbpplib.txt \
	howtobsd.txt \
	idle.txt \
	lang.txt \
	license.txt \
	math.txt \
	memo.txt \
	pcode.txt \
	pragma.txt \
	readme.txt \
	setmode.txt \
	statics.txt \
	strotype.txt \
	tracing.txt \
	vm.txt \

include $(TOP)$(ROOT)config/doc.cf
