#
# $Id$
#

ROOT = ../../

DOC_SUBDIR=/es

DOC_FILES=\
	array.txt \
	binnum.txt \
	browse.txt \
	clipper.txt \
	cmdline.txt \
	codebloc.txt \
	codestyl.txt \
	command.txt \
	compiler.txt \
	datetime.txt \
	dbdelim.txt \
	dbsdf.txt \
	dbstrux.txt \
	dir.txt \
	dirstruc.txt \
	diskspac.txt \
	error.txt \
	eval.txt \
	file.txt \
	garbage.txt \
	gnulice.txt \
	harbext.txt \
	hb_apiln.txt \
	hb_set.txt \
	hb_vm.txt \
	hbpplib.txt \
	howtobsd.txt \
	hvm.txt \
	idle.txt \
	input.txt \
	lang.txt \
	license.txt \
	macro.txt \
	math.txt \
	memo.txt \
	memvar2.txt \
	misc.txt \
	nation.txt \
	objfunc.txt \
	pcode.txt \
	pragma.txt \
	rdd.txt \
	readme.txt \
	sayget.txt \
	setmode.txt \
	statics.txt \
	strotype.txt \
	subcodes.txt \
	tbrowse.txt \
	tclass.txt \
	tgetlist.txt \
	tlabel.txt \
	tracing.txt \
	treport.txt \
	var.txt \
	vm.txt \

include $(TOP)$(ROOT)config/doc.cf
