#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	dbcmd.c \
        dbf1.c \

PRG_SOURCES=\
        dbf0.prg \
	rddsys.prg \

LIB=rdd

DIRS=\
	dbfntx \

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
