# $Id$
# Make file for DOS DJGPP
#
include ../../makedos.env

SRCPRG:= $(wildcard *.prg)
CPRG=$(SRCPRG:.prg=.c)
OBJPRG=$(CPRG:.c=.o)

SRCC:= $(wildcard *.c)
OBJC=$(SRCC:.c=.o)

all:	$(HARBOURLIB) 

$(HARBOURLIB): ${OBJPRG} $(OBJC)
	ar r $(HARBOURLIB) ${OBJC} ${OBJPRG}

clean:
	-del *.o
