#
# $Id$
#

ROOT = ../../

ifeq ($(HB_ARCHITECTURE),w32)
DIRS = hbgfw32
endif

ifeq ($(HB_ARCHITECTURE),linux)
DIRS = hbgfgtk
endif

ifeq ($(HB_ARCHITECTURE),os2)
DIRS = hbgfos2
endif

include $(ROOT)config/dir.cf
