#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
        cccppc.prg    \
        cccpp_pr.prg  \
        creader.prg   \
        crlf.prg      \
        defdict.prg   \
        edefdict.prg  \
        expr.prg      \
        extrdict.prg  \
        felbont.prg   \
        fnutil.prg    \
        freader.prg   \
        guesseol.prg  \
        hparser.prg   \
        hparser2.prg  \
        incl.prg      \
        lparser.prg   \
        lreader.prg   \
        maltrset.prg  \
        mcontrol.prg  \
        mmarker.prg   \
        mparser.prg   \
        newline.prg   \
        nparser.prg   \
        parser.prg    \
        prserr.prg    \
        prtree.prg    \
        prtreepr.prg  \
        ralter.prg    \
        reader.prg    \
        rmarker.prg   \
        rsmmarkr.prg  \
        sreader.prg   \
        tbuffer.prg   \
        tkstr.prg     \
        token.prg     \
        tokenst.prg   \
        tostr.prg     \
        treader.prg   \
        util.prg      \
        xtrdict.prg   \
        object.prg    \
        package.prg   \
        version.prg   \

PRG_MAIN=cccppc.prg

LIBS=\
        runner \
        tools \
        debug \
        rdd \
        vm \
        rdd \
        rtl \
        pp \
	common \
	macro \

include $(TOP)$(ROOT)config/bin.cf
