//
// $Id$
//

//*******************************************************************
// tokenst.cls: Stream token reprezent ci¢. (BOS ‚s EOS)
// 1999, Csisz r Levente

class TOKENST TOKEN

   attrib deep         // Az egym sba skatuly z s m‚lys‚ge. 1-t“l
                       // sz moz¢dik.

   rmethod oinit(id,str,file,line,pos,deep)
   // Inicializ lja az objektumot.
   
metaclass

   rmethod onew(id,str,file,line,pos,deep)


