#
# $Id$
#

ROOT = ../../

C_SOURCES=\

PRG_SOURCES=\
    ohtm.prg \
    ocgi.prg \
    oedit.prg \
    oframe.prg \
    oini.prg \
    ofile.prg \
    jwindow.prg \
    htmutil.prg \
    counter.prg \
    errorsys.prg \
    htmbrows.prg \
    jlist.prg \

LIBNAME=html

include $(TOP)$(ROOT)config/lib.cf
