#
# $Id$
#

ROOT = ../

DOC_FILES=\
	c_std.txt \
	class_tp.txt \
	cmdline.txt \
	codebloc.txt \
	codestyl.txt \
	dirstruc.txt \
	funclist.txt \
	genhtm.bat \
	genhtm.cmd \
	genhtm.lnk \
	genhtm.rsp \
	gmake.txt \
	gtapi.txt \
	hbmake.txt \
	hbpplib.txt \
	hdr_tpl.txt \
	howtobsd.txt \
	howtocvs.txt \
	howtomak.txt \
	hrb_faq.txt \
	lang_id.txt \
	license.txt \
	pcode.txt \
	pragma.txt \
	readme.txt \
	simplex.txt \
	statics.txt \
	tracing.txt \
	transfrm.txt \
	vm.txt \
	whatsnew.txt \
	windll.txt \

DIRS=\
	en \
	es \

include $(TOP)$(ROOT)config/doc.cf
include $(TOP)$(ROOT)config/dir.cf
