#
# $Id$
#

ifeq ($(HB_MAIN),)
   HB_MAIN = std
endif

ROOT = ../../../

CONTRIBS=\
	hbpgsql \

PRG_SOURCES=\
	test.prg \

PRG_MAIN=\
	test.prg

LIBS=\
	hbdebug \
	hbvm \
	hbrtl \
	hblang \
	hbrdd \
	hbrtl \
	hbvm \
	hbmacro \
	hbcommon \
	hbpgsql \

include $(TOP)$(ROOT)config/bin.cf
