#
# $Id: Makefile,v 1.1 2003/12/31 00:24:35 lculik Exp $
#

ifeq ($(HB_MAIN),)
    HB_MAIN = std
endif

ROOT = ../../../

CONTRIBS=\
	firebird \

PRG_SOURCES=\
	simple.prg \

PRG_MAIN=\
	simple.prg

LIBS=\
	debug \
	vm \
	rtl \
	lang \
	rdd \
	rtl \
	vm \
	macro \
	common \
	fbclient \

include $(TOP)$(ROOT)config/bin.cf
