#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	chartabs.c \
	pcrecomp.c \
	pcreconf.c \
	pcredfa.c  \
	pcreexec.c \
	pcrefinf.c \
	pcreget.c  \
	pcreglob.c \
	pcreinfo.c \
	pcremktb.c \
	pcreoutf.c \
	pcreprni.c \
	pcrerefc.c \
	pcrestud.c \
	pcretabs.c \
	pcretryf.c \
	pcrefind.c \
	pcrevutf.c \
	pcrever.c  \
	pcrexcls.c \

LIBNAME=hbpcre

include $(TOP)$(ROOT)config/lib.cf
