ROOT := ../

DOC_FILES := \
   c_std.txt \
   class_tp.txt \
   clipper.txt \
   cmdline.txt \
   cmpopt.txt \
   codebloc.txt \
   codestyl.txt \
   destruct.txt \
   dirstruc.txt \
   gmake.txt \
   gtapi.txt \
   gtslang.txt \
   hdr_tpl.txt \
   howtorel.txt \
   howtorep.txt \
   locks.txt \
   oldnews.txt \
   pcode.txt \
   pp.txt \
   pragma.txt \
   statics.txt \
   todo.txt \
   tracing.txt \
   transfrm.txt \
   vm.txt \
   windll.txt \
   xhb-diff.txt \

include $(TOP)$(ROOT)config/doc.mk
