#
# $Id$
#

ifeq ($(HB_MAIN),)
   HB_MAIN = std
endif

ROOT = ../

PRG_SOURCES=\
        hbdoc.prg 

PRG_MAIN=hbdoc.prg

LIBS=\
        tools \
        debug \
        rtl \
        rdd \
        vm \
        rdd \
        rtl \
	macro \
        pp \
        runner \
        common \

include $(TOP)$(ROOT)config/bin.cf
