#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	msgca.c      \
	msgen.c      \
	msges.c      \
	msgeu.c      \
	msgfr.c      \
	msggl.c      \
	msghe862.c   \
	msghewin.c   \
	msghu852.c   \
	msghucwi.c   \
	msghuwin.c   \
	msgis850.c   \
	msgpt.c      \
	msgro.c      \
	msgsr852.c   \
	msgsriso.c   \
	msgcs852.c   \
	msgcsiso.c   \
	msgcskam.c   \

LIBNAME=lang

include $(TOP)$(ROOT)config/lib.cf
