#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	msgca.c      \
	msgen.c      \
	msges.c      \
	msgeu.c      \
	msgfr.c      \
	msggl.c      \
	msghu852.c   \
	msghucwi.c   \
	msghuwin.c   \
	msgpt.c      \
	msgro.c      \

LIBNAME=lang

include $(TOP)$(ROOT)config/lib.cf

