#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	msgca.c      \
	msgcs852.c   \
	msgcsiso.c   \
	msgcskam.c   \
	msgcswin.c   \
	msgde.c      \
	msgen.c      \
	msges.c      \
	msgeu.c      \
	msgfr.c      \
	msggl.c      \
	msghe862.c   \
	msghewin.c   \
	msghr852.c   \
	msghriso.c   \
	msghu852.c   \
	msghucwi.c   \
	msghuwin.c   \
	msgid.c      \
	msgis850.c   \
	msgit.c      \
	msgko.c      \
	msgpt.c      \
	msgro.c      \
	msgsr852.c   \
	msgsriso.c   \

LIBNAME=lang

include $(TOP)$(ROOT)config/lib.cf
