#
# $Id$
#

ROOT := ../../

C_SOURCES := \
   msgbeutf.c \
   msgbgutf.c \
   msgcautf.c \
   msgcsutf.c \
   msgdeutf.c \
   msgelutf.c \
   msgeoutf.c \
   msgesutf.c \
   msgeuutf.c \
   msgfrutf.c \
   msgglutf.c \
   msgheutf.c \
   msghrutf.c \
   msghuutf.c \
   msgidutf.c \
   msgisutf.c \
   msgitutf.c \
   msgkoutf.c \
   msgltutf.c \
   msgnlutf.c \
   msgplutf.c \
   msgptutf.c \
   msgroutf.c \
   msgruutf.c \
   msgskutf.c \
   msgslutf.c \
   msgsrlat.c \
   msgsrutf.c \
   msgsvutf.c \
   msgtrutf.c \
   msguautf.c \
   msgzhsim.c \
   msgzhutf.c \

LIBNAME := hblang

include $(TOP)$(ROOT)config/lib.mk
