#
# $Id$
#

ROOT := ../../

C_SOURCES := \
   be.c \
   bg.c \
   ca.c \
   cs.c \
   de.c \
   el.c \
   eo.c \
   es.c \
   eu.c \
   fr.c \
   gl.c \
   he.c \
   hr.c \
   hu.c \
   id.c \
   is.c \
   it.c \
   ko.c \
   lt.c \
   nl.c \
   pl.c \
   pt.c \
   ro.c \
   ru.c \
   sk.c \
   sl.c \
   sr_cyr.c \
   sr_lat.c \
   sv.c \
   tr.c \
   uk.c \
   zh_sim.c \
   zh_tra.c \

LIBNAME := hblang

include $(TOP)$(ROOT)config/lib.mk
