#
# $Id$
#

ROOT := ../../

C_SOURCES := \
   msgbe866.c \
   msgbewin.c \
   msgbg866.c \
   msgbgiso.c \
   msgbgmik.c \
   msgbgwin.c \
   msgca.c \
   msgcs852.c \
   msgcsiso.c \
   msgcskam.c \
   msgcswin.c \
   msgde.c \
   msgdewin.c \
   msgel.c \
   msgelwin.c \
   msgeo.c \
   msges.c \
   msgeswin.c \
   msgeu.c \
   msgfr.c \
   msggl.c \
   msghe862.c \
   msghewin.c \
   msghr646.c \
   msghr852.c \
   msghriso.c \
   msghrwin.c \
   msghu852.c \
   msghucwi.c \
   msghuiso.c \
   msghuutf.c \
   msghuwin.c \
   msgid.c \
   msgis850.c \
   msgit.c \
   msgko.c \
   msgltwin.c \
   msgnl.c \
   msgpl852.c \
   msgpliso.c \
   msgplmaz.c \
   msgplwin.c \
   msgpt.c \
   msgptiso.c \
   msgro.c \
   msgru866.c \
   msgrukoi.c \
   msgruwin.c \
   msgskiso.c \
   msgskwin.c \
   msgskkam.c \
   msgsk852.c \
   msgsl646.c \
   msgsl852.c \
   msgsliso.c \
   msgslwin.c \
   msgsr852.c \
   msgsriso.c \
   msgtr857.c \
   msgtrwin.c \
   msgsrwin.c \
   msgsv.c \
   msgsvwin.c \
   msgua866.c \
   msguados.c \
   msguakoi.c \
   msguawin.c \
   msgzhb5.c \
   msgzhgb.c \

LIBNAME := hblang

include $(TOP)$(ROOT)config/lib.mk
