/* Copyright 2014 Viktor Szakats (vszakats.net/harbour) */

#include "hbapi.h"

/* mappings to hbwin (accepting/returning pointers/handles) */
HB_FUNC_TRANSLATE( WVG_SENDDLGITEMMESSAGE    , WAPI_SENDDLGITEMMESSAGE    )
HB_FUNC_TRANSLATE( WVG_GETFOCUS              , WAPI_GETFOCUS              )
HB_FUNC_TRANSLATE( WVG_SETFOCUS              , WAPI_SETFOCUS              )
HB_FUNC_TRANSLATE( WVG_SETTEXTCOLOR          , WAPI_SETTEXTCOLOR          )
HB_FUNC_TRANSLATE( WVG_SETBKCOLOR            , WAPI_SETBKCOLOR            )
HB_FUNC_TRANSLATE( WVG_SETBKMODE             , WAPI_SETBKMODE             )
HB_FUNC_TRANSLATE( WVG_GETDIALOGBASEUNITS    , WAPI_GETDIALOGBASEUNITS    )
HB_FUNC_TRANSLATE( WVG_SETDLGITEMTEXT        , WAPI_SETDLGITEMTEXT        )
HB_FUNC_TRANSLATE( WVG_GETDLGITEMTEXT        , WAPI_GETDLGITEMTEXT        )
HB_FUNC_TRANSLATE( WVG_CHECKDLGBUTTON        , WAPI_CHECKDLGBUTTON        )
HB_FUNC_TRANSLATE( WVG_ISDLGBUTTONCHECKED    , WAPI_ISDLGBUTTONCHECKED    )
HB_FUNC_TRANSLATE( WVG_CHECKRADIOBUTTON      , WAPI_CHECKRADIOBUTTON      )
HB_FUNC_TRANSLATE( WVG_GETDLGITEM            , WAPI_GETDLGITEM            )
HB_FUNC_TRANSLATE( WVG_MESSAGEBOX            , WAPI_MESSAGEBOX            )
HB_FUNC_TRANSLATE( WVG_DRAWTEXT              , WAPI_DRAWTEXT              )
HB_FUNC_TRANSLATE( WVG_MOVEWINDOW            , WAPI_MOVEWINDOW            )
HB_FUNC_TRANSLATE( WVG_GETDESKTOPWINDOW      , WAPI_GETDESKTOPWINDOW      )
HB_FUNC_TRANSLATE( WVG_SETPARENT             , WAPI_SETPARENT             )
HB_FUNC_TRANSLATE( WVG_BRINGWINDOWTOTOP      , WAPI_BRINGWINDOWTOTOP      )
HB_FUNC_TRANSLATE( WVG_SETFOREGROUNDWINDOW   , WAPI_BRINGWINDOWTOTOP      )
HB_FUNC_TRANSLATE( WVG_SETWINDOWTEXT         , WAPI_SETWINDOWTEXT         )
HB_FUNC_TRANSLATE( WVG_SETWINDOWLONG         , WAPI_SETWINDOWLONGPTR      )
HB_FUNC_TRANSLATE( WVG_SENDMESSAGE           , WAPI_SENDMESSAGE           )
HB_FUNC_TRANSLATE( WVG_SENDMESSAGETEXT       , WAPI_SENDMESSAGE           )
HB_FUNC_TRANSLATE( WVG_ISWINDOW              , WAPI_ISWINDOW              )
HB_FUNC_TRANSLATE( WVG_ENABLEWINDOW          , WAPI_ENABLEWINDOW          )
HB_FUNC_TRANSLATE( WVG_DESTROYWINDOW         , WAPI_DESTROYWINDOW         )
HB_FUNC_TRANSLATE( WVG_CLIENTTOSCREEN        , WAPI_CLIENTTOSCREEN        )
HB_FUNC_TRANSLATE( WVG_SCREENTOCLIENT        , WAPI_SCREENTOCLIENT        )
HB_FUNC_TRANSLATE( WVG_TREEVIEW_SETTEXTCOLOR , WAPI_TREEVIEW_SETLINECOLOR )
HB_FUNC_TRANSLATE( WVG_TREEVIEW_SETBKCOLOR   , WAPI_TREEVIEW_SETBKCOLOR   )
HB_FUNC_TRANSLATE( WVG_TREEVIEW_SETLINECOLOR , WAPI_TREEVIEW_SETLINECOLOR )
HB_FUNC_TRANSLATE( WVG_TREEVIEW_SELECTITEM   , WAPI_TREEVIEW_SELECTITEM   )
HB_FUNC_TRANSLATE( WVG_ISICONIC              , WAPI_ISICONIC              )
HB_FUNC_TRANSLATE( WVG_ISZOOMED              , WAPI_ISZOOMED              )
HB_FUNC_TRANSLATE( WVG_CREATEMENU            , WAPI_CREATEMENU            )
HB_FUNC_TRANSLATE( WVG_CREATEPOPUPMENU       , WAPI_CREATEPOPUPMENU       )
HB_FUNC_TRANSLATE( WVG_DELETEMENU            , WAPI_DELETEMENU            )
HB_FUNC_TRANSLATE( WVG_DESTROYMENU           , WAPI_DESTROYMENU           )
HB_FUNC_TRANSLATE( WVG_ENABLEMENUITEM        , WAPI_ENABLEMENUITEM        )
HB_FUNC_TRANSLATE( WVG_CHECKMENUITEM         , WAPI_CHECKMENUITEM         )
HB_FUNC_TRANSLATE( WVG_DRAWMENUBAR           , WAPI_DRAWMENUBAR           )
HB_FUNC_TRANSLATE( WVG_UPDATEWINDOW          , WAPI_UPDATEWINDOW          )
HB_FUNC_TRANSLATE( WVG_SHOWWINDOW            , WAPI_SHOWWINDOW            )

/* mappings to hbwin */
HB_FUNC_TRANSLATE( WVG_LOWORD                , WAPI_LOWORD                )
HB_FUNC_TRANSLATE( WVG_HIWORD                , WAPI_HIWORD                )
HB_FUNC_TRANSLATE( WVG_MAKELPARAM            , WAPI_MAKELPARAM            )
HB_FUNC_TRANSLATE( WVG_SLEEP                 , WAPI_SLEEP                 )
HB_FUNC_TRANSLATE( WVT__MAKEDLGTEMPLATE      , __WAPI_DLGTEMPLATE_RAW_NEW )

/* existing synonyms */
HB_FUNC_TRANSLATE( WVT_APPENDMENU            , WVG_APPENDMENU             )
HB_FUNC_TRANSLATE( WVT_CREATEMENU            , WVG_CREATEMENU             )
HB_FUNC_TRANSLATE( WVT_CREATEPOPUPMENU       , WVG_CREATEPOPUPMENU        )
HB_FUNC_TRANSLATE( WVT_DELETEMENU            , WVG_DELETEMENU             )
HB_FUNC_TRANSLATE( WVT_DESTROYMENU           , WVG_DESTROYMENU            )
HB_FUNC_TRANSLATE( WVT_ENABLEMENUITEM        , WVG_ENABLEMENUITEM         )

#ifdef HB_LEGACY_LEVEL5

HB_FUNC( WVG_AND )
{
   hb_retnl( hb_parnl( 1 ) & hb_parnl( 2 ) );
}

HB_FUNC( WVG_OR )
{
   hb_retnl( hb_parnl( 1 ) | hb_parnl( 2 ) );
}

HB_FUNC( WVG_NOT )
{
   hb_retnl( ~( hb_parnl( 1 ) ) );
}

#endif
