#
# $Id$
#

ROOT = ../../

C_SOURCES = \
	base64x.c \
	encmthd.c \
	utils.c   \

PRG_SOURCES= \
	popcln.prg \
	credent.prg \
	encoder.prg \
	encb64.prg \
	encqp.prg \
	encurl.prg \
	url.prg \
	client.prg \
	ftpcln.prg \
	smtpcln.prg	\
	httpcln.prg \
	mail.prg \
	cgi.prg \
	thtml.prg \

LIBNAME=tip

include $(TOP)$(ROOT)config/lib.cf
