#
# $Id$
#

ROOT := ../../

DOC_SUBDIR := /en

DOC_FILES := \
   1stread.txt \
   array.txt \
   binnum.txt \
   browse.txt \
   cmdline.txt \
   command.txt \
   compiler.txt \
   datetime.txt \
   dbdelim.txt \
   dbsdf.txt \
   dbstrux.txt \
   dir.txt \
   diskspac.txt \
   errsys.txt \
   eval.txt \
   file.txt \
   garbage.txt \
   gnulice.txt \
   gtslang.txt \
   harbext.txt \
   hb_api.txt \
   hb_apier.txt \
   hb_apifs.txt \
   hb_apigt.txt \
   hb_apiit.txt \
   hb_apiln.txt \
   hb_apird.txt \
   hb_compa.txt \
   hb_date.txt \
   hb_macro.txt \
   hb_set.txt \
   hb_vm.txt \
   hvm.txt \
   idle.txt \
   input.txt \
   lang.txt \
   license.txt \
   macro.txt \
   math.txt \
   memo.txt \
   memvar2.txt \
   menu.txt \
   misc.txt \
   nation.txt \
   objfunc.txt \
   rdd.txt \
   rdddb.txt \
   rddmisc.txt \
   rddord.txt \
   readme.txt \
   sayget.txt \
   set.txt \
   setmode.txt \
   string.txt \
   strotype.txt \
   subcodes.txt \
   tbrowse.txt \
   tclass.txt \
   terminal.txt \
   tgetlist.txt \
   tlabel.txt \
   treport.txt \
   var.txt \

include $(TOP)$(ROOT)config/doc.mk
