#
# $Id$
#

ROOT := ../../

LIBNAME := hbmisc

C_SOURCES := \
   dates2.c \
   ffind.c \
   hb_f.c \
   hbeditc.c \
   spd.c \
   strfmt.c \
   stringsx.c \

PRG_SOURCES := \
   fcomma.prg \
   fileread.prg \
   hbedit.prg \
   nconvert.prg \
   numtxthu.prg \
   numtxten.prg \
   stringp.prg \
   twirler.prg \

include $(TOP)$(ROOT)config/lib.mk
