#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	dates2.c \
	hb_f.c \
	spd.c \
	strfmt.c \
	stringsx.c \

PRG_SOURCES=\
	fileread.prg \
	nconvert.prg \
	numtxthu.prg \
	numtxten.prg \
	stringp.prg \
	twirler.prg \

LIBNAME=hbmisc

DIRS=test

include $(TOP)$(ROOT)config/lib.cf
#include $(TOP)$(ROOT)config/dir.cf
