#
# $Id$
#

ROOT = ../../

C_SOURCES=\
        hbfsapi.c \
        hbstr.c \
        hbtrace.c \
	reserved.c \
	expropt1.c \
	expropt2.c \

PRG_SOURCES=\

LIBNAME=common

include $(TOP)$(ROOT)config/lib.cf
