#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	hbfhnd.c \
	hbfsapi.c \
	hbgete.c \
	hbwince.c \
	hbhash.c \
	hbstr.c \
	hbdate.c \
	hbtrace.c \
	hbver.c \
	hbverdsp.c \
	hbarch.c \
	reserved.c \
	expropt1.c \
	expropt2.c \

PRG_SOURCES=\

LIBNAME=common

include $(TOP)$(ROOT)config/lib.cf
