#
# $Id$
#

ROOT := ../../

C_SOURCES := \
	expropt1.c \
	expropt2.c \
	hbffind.c \
	hbfopen.c \
	hbfsapi.c \
	hbgete.c \
	hbwince.c \
	hbhash.c \
	hbprintf.c \
	hbstr.c \
	hbdate.c \
	hbmem.c \
	hbtrace.c \
	hbver.c \
	hbverdsp.c \
	hbarch.c \
	reserved.c \
	strwild.c \

LIBNAME := hbcommon

include $(TOP)$(ROOT)config/lib.cf
