#
# $Id: Makefile 14244 2010-03-27 12:27:08Z vszakats $
#

ROOT := ../../

LIBNAME := hbblink

PRG_SOURCES := \
   blinker.prg \

PRG_HEADERS := \
   hbblink.ch \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
