# $Id$
# Make file for DOS DJGPP
#
include ../../../makedos.env

SRCPRG:= $(wildcard *.prg)
CPRG=$(SRCPRG:.prg=.c)
OBJPRG=$(CPRG:.c=.o)

SRCC:= $(wildcard *.c)
OBJC=$(SRCC:.c=.o)

all:	$(DBFNTXLIB) 

$(DBFNTXLIB): ${OBJPRG} $(OBJC)
	ar r $(DBFNTXLIB) ${OBJPRG} $(OBJC)

clean:
	-del *.o
