#
# $Id$
#

# --------------------------------------------------------------------
# WARNING: Automatically generated source file. DO NOT EDIT!
#          Instead, edit corresponding .qth file,
#          or the generator tool itself, and run regenarate.
# --------------------------------------------------------------------

CPP_SOURCES := \
   moc_slots.cpp \
   hbqt_base.cpp \
   hbqt_utils.cpp \
   hbqt_slots.cpp \
   QAbstractButton.cpp \
   QAbstractItemModel.cpp \
   QAbstractItemView.cpp \
   QAbstractListModel.cpp \
   QAbstractPrintDialog.cpp \
   QAbstractScrollArea.cpp \
   QAbstractSlider.cpp \
   QAbstractSpinBox.cpp \
   QAbstractTableModel.cpp \
   QAction.cpp \
   QApplication.cpp \
   QBitmap.cpp \
   QBoxLayout.cpp \
   QBrush.cpp \
   QButtonGroup.cpp \
   QCalendarWidget.cpp \
   QCheckBox.cpp \
   QClipboard.cpp \
   QColor.cpp \
   QColorDialog.cpp \
   QComboBox.cpp \
   QCommandLinkButton.cpp \
   QCommonStyle.cpp \
   QConicalGradient.cpp \
   QCoreApplication.cpp \
   QCursor.cpp \
   QDateEdit.cpp \
   QDateTime.cpp \
   QDateTimeEdit.cpp \
   QDesktopWidget.cpp \
   QDial.cpp \
   QDialog.cpp \
   QDir.cpp \
   QDirModel.cpp \
   QDockWidget.cpp \
   QDoubleSpinBox.cpp \
   QDropEvent.cpp \
   QDragMoveEvent.cpp \
   QDragEnterEvent.cpp \
   QDragLeaveEvent.cpp \
   QErrorMessage.cpp \
   QEvent.cpp \
   QEventLoop.cpp \
   QFileDialog.cpp \
   QFileSystemModel.cpp \
   QFocusEvent.cpp \
   QFocusFrame.cpp \
   QFont.cpp \
   QFontComboBox.cpp \
   QFontDatabase.cpp \
   QFontDialog.cpp \
   QFontInfo.cpp \
   QFontMetrics.cpp \
   QFontMetricsF.cpp \
   QFormLayout.cpp \
   QFrame.cpp \
   QFtp.cpp \
   QGradient.cpp \
   QGridLayout.cpp \
   QGroupBox.cpp \
   QHBoxLayout.cpp \
   QHeaderView.cpp \
   QHttp.cpp \
   QIcon.cpp \
   QImage.cpp \
   QImageReader.cpp \
   QImageWriter.cpp \
   QInputDialog.cpp \
   QInputEvent.cpp \
   QIODevice.cpp \
   QKeyEvent.cpp \
   QKeySequence.cpp \
   QLabel.cpp \
   QLatin1Char.cpp \
   QLatin1String.cpp \
   QLayout.cpp \
   QLayoutItem.cpp \
   QLCDNumber.cpp \
   QLine.cpp \
   QLinearGradient.cpp \
   QLineEdit.cpp \
   QList.cpp \
   QListView.cpp \
   QListWidget.cpp \
   QListWidgetItem.cpp \
   QMainWindow.cpp \
   QMenu.cpp \
   QMenuBar.cpp \
   QMessageBox.cpp \
   QModelIndex.cpp \
   QMouseEvent.cpp \
   QMoveEvent.cpp \
   QObject.cpp \
   QPaintDevice.cpp \
   QPageSetupDialog.cpp \
   QPainter.cpp \
   QPaintEvent.cpp \
   QPalette.cpp \
   QPen.cpp \
   QPicture.cpp \
   QPixmap.cpp \
   QPoint.cpp \
   QPointF.cpp \
   QPrintDialog.cpp \
   QPrintEngine.cpp \
   QPrinter.cpp \
   QPrintPreviewDialog.cpp \
   QProcess.cpp \
   QProgressBar.cpp \
   QProgressDialog.cpp \
   QPushButton.cpp \
   QRadialGradient.cpp \
   QRadioButton.cpp \
   QRect.cpp \
   QRectF.cpp \
   QRegion.cpp \
   QResizeEvent.cpp \
   QResource.cpp \
   QScrollArea.cpp \
   QScrollBar.cpp \
   QSignalMapper.cpp \
   QSize.cpp \
   QSizeF.cpp \
   QSizeGrip.cpp \
   QSizePolicy.cpp \
   QSlider.cpp \
   QSound.cpp \
   QSpinBox.cpp \
   QSplashScreen.cpp \
   QSplitter.cpp \
   QStandardItem.cpp \
   QStandardItemModel.cpp \
   QStatusBar.cpp \
   QStringList.cpp \
   QStringListModel.cpp \
   QStyle.cpp \
   QStyledItemDelegate.cpp \
   QStyleFactory.cpp \
   QStyleHintReturn.cpp \
   QStyleHintReturnMask.cpp \
   QStyleHintReturnVariant.cpp \
   QStyleOption.cpp \
   QStyleOptionButton.cpp \
   QStyleOptionComboBox.cpp \
   QStyleOptionComplex.cpp \
   QStyleOptionDockWidget.cpp \
   QStyleOptionFocusRect.cpp \
   QStyleOptionFrame.cpp \
   QStyleOptionGroupBox.cpp \
   QStyleOptionHeader.cpp \
   QStyleOptionMenuItem.cpp \
   QStyleOptionProgressBar.cpp \
   QStyleOptionSizeGrip.cpp \
   QStyleOptionSlider.cpp \
   QStyleOptionSpinBox.cpp \
   QStyleOptionTab.cpp \
   QStyleOptionTabBarBase.cpp \
   QStyleOptionTabWidgetFrame.cpp \
   QStyleOptionTitleBar.cpp \
   QStyleOptionToolBar.cpp \
   QStyleOptionToolBox.cpp \
   QStyleOptionToolButton.cpp \
   QStyleOptionViewItem.cpp \
   QStylePainter.cpp \
   QSystemTrayIcon.cpp \
   QTabBar.cpp \
   QTableView.cpp \
   QTableWidget.cpp \
   QTableWidgetItem.cpp \
   QTabWidget.cpp \
   QTextBlock.cpp \
   QTextBlockFormat.cpp \
   QTextBlockGroup.cpp \
   QTextBrowser.cpp \
   QTextBoundaryFinder.cpp \
   QTextCharFormat.cpp \
   QTextCodec.cpp \
   QTextCursor.cpp \
   QTextDecoder.cpp \
   QTextDocument.cpp \
   QTextDocumentFragment.cpp \
   QTextDocumentWriter.cpp \
   QTextEdit.cpp \
   QTextEncoder.cpp \
   QTextFormat.cpp \
   QTextFragment.cpp \
   QTextFrame.cpp \
   QTextFrameFormat.cpp \
   QTextImageFormat.cpp \
   QTextInlineObject.cpp \
   QTextItem.cpp \
   QTextLayout.cpp \
   QTextLength.cpp \
   QTextLine.cpp \
   QTextObject.cpp \
   QTextStream.cpp \
   QTimeEdit.cpp \
   QTimer.cpp \
   QToolBar.cpp \
   QToolBox.cpp \
   QToolButton.cpp \
   QTreeView.cpp \
   QTreeWidget.cpp \
   QTreeWidgetItem.cpp \
   QUrl.cpp \
   QVariant.cpp \
   QVBoxLayout.cpp \
   QWebFrame.cpp \
   QWebHistory.cpp \
   QWebHistoryInterface.cpp \
   QWebHistoryItem.cpp \
   QWebHitTestResult.cpp \
   QWebPage.cpp \
   QWebPluginFactory.cpp \
   QWebSecurityOrigin.cpp \
   QWebSettings.cpp \
   QWebView.cpp \
   QWheelEvent.cpp \
   QWidget.cpp \
   QWidgetAction.cpp \
   QWidgetItem.cpp \
   QWindowsStyle.cpp \
   QWindowsXPStyle.cpp \
   QWizard.cpp \



PRG_SOURCES := \
   TQAbstractButton.prg \
   TQAbstractItemModel.prg \
   TQAbstractItemView.prg \
   TQAbstractListModel.prg \
   TQAbstractPrintDialog.prg \
   TQAbstractScrollArea.prg \
   TQAbstractSlider.prg \
   TQAbstractSpinBox.prg \
   TQAbstractTableModel.prg \
   TQAction.prg \
   TQApplication.prg \
   TQBitmap.prg \
   TQBoxLayout.prg \
   TQBrush.prg \
   TQButtonGroup.prg \
   TQCalendarWidget.prg \
   TQCheckBox.prg \
   TQClipboard.prg \
   TQColor.prg \
   TQColorDialog.prg \
   TQComboBox.prg \
   TQCommandLinkButton.prg \
   TQCommonStyle.prg \
   TQConicalGradient.prg \
   TQCoreApplication.prg \
   TQCursor.prg \
   TQDateEdit.prg \
   TQDateTime.prg \
   TQDateTimeEdit.prg \
   TQDesktopWidget.prg \
   TQDial.prg \
   TQDialog.prg \
   TQDir.prg \
   TQDirModel.prg \
   TQDockWidget.prg \
   TQDoubleSpinBox.prg \
   TQDropEvent.prg \
   TQDragMoveEvent.prg \
   TQDragEnterEvent.prg \
   TQDragLeaveEvent.prg \
   TQErrorMessage.prg \
   TQEvent.prg \
   TQEventLoop.prg \
   TQFileDialog.prg \
   TQFileSystemModel.prg \
   TQFocusEvent.prg \
   TQFocusFrame.prg \
   TQFont.prg \
   TQFontComboBox.prg \
   TQFontDatabase.prg \
   TQFontDialog.prg \
   TQFontInfo.prg \
   TQFontMetrics.prg \
   TQFontMetricsF.prg \
   TQFormLayout.prg \
   TQFrame.prg \
   TQFtp.prg \
   TQGradient.prg \
   TQGridLayout.prg \
   TQGroupBox.prg \
   TQHBoxLayout.prg \
   TQHeaderView.prg \
   TQHttp.prg \
   TQIcon.prg \
   TQImage.prg \
   TQImageReader.prg \
   TQImageWriter.prg \
   TQInputDialog.prg \
   TQInputEvent.prg \
   TQIODevice.prg \
   TQKeyEvent.prg \
   TQKeySequence.prg \
   TQLabel.prg \
   TQLatin1Char.prg \
   TQLatin1String.prg \
   TQLayout.prg \
   TQLayoutItem.prg \
   TQLCDNumber.prg \
   TQLine.prg \
   TQLinearGradient.prg \
   TQLineEdit.prg \
   TQList.prg \
   TQListView.prg \
   TQListWidget.prg \
   TQListWidgetItem.prg \
   TQMainWindow.prg \
   TQMenu.prg \
   TQMenuBar.prg \
   TQMessageBox.prg \
   TQModelIndex.prg \
   TQMouseEvent.prg \
   TQMoveEvent.prg \
   TQObject.prg \
   TQPaintDevice.prg \
   TQPageSetupDialog.prg \
   TQPainter.prg \
   TQPaintEvent.prg \
   TQPalette.prg \
   TQPen.prg \
   TQPicture.prg \
   TQPixmap.prg \
   TQPoint.prg \
   TQPointF.prg \
   TQPrintDialog.prg \
   TQPrintEngine.prg \
   TQPrinter.prg \
   TQPrintPreviewDialog.prg \
   TQProcess.prg \
   TQProgressBar.prg \
   TQProgressDialog.prg \
   TQPushButton.prg \
   TQRadialGradient.prg \
   TQRadioButton.prg \
   TQRect.prg \
   TQRectF.prg \
   TQRegion.prg \
   TQResizeEvent.prg \
   TQResource.prg \
   TQScrollArea.prg \
   TQScrollBar.prg \
   TQSignalMapper.prg \
   TQSize.prg \
   TQSizeF.prg \
   TQSizeGrip.prg \
   TQSizePolicy.prg \
   TQSlider.prg \
   TQSound.prg \
   TQSpinBox.prg \
   TQSplashScreen.prg \
   TQSplitter.prg \
   TQStandardItem.prg \
   TQStandardItemModel.prg \
   TQStatusBar.prg \
   TQStringList.prg \
   TQStringListModel.prg \
   TQStyle.prg \
   TQStyledItemDelegate.prg \
   TQStyleFactory.prg \
   TQStyleHintReturn.prg \
   TQStyleHintReturnMask.prg \
   TQStyleHintReturnVariant.prg \
   TQStyleOption.prg \
   TQStyleOptionButton.prg \
   TQStyleOptionComboBox.prg \
   TQStyleOptionComplex.prg \
   TQStyleOptionDockWidget.prg \
   TQStyleOptionFocusRect.prg \
   TQStyleOptionFrame.prg \
   TQStyleOptionGroupBox.prg \
   TQStyleOptionHeader.prg \
   TQStyleOptionMenuItem.prg \
   TQStyleOptionProgressBar.prg \
   TQStyleOptionSizeGrip.prg \
   TQStyleOptionSlider.prg \
   TQStyleOptionSpinBox.prg \
   TQStyleOptionTab.prg \
   TQStyleOptionTabBarBase.prg \
   TQStyleOptionTabWidgetFrame.prg \
   TQStyleOptionTitleBar.prg \
   TQStyleOptionToolBar.prg \
   TQStyleOptionToolBox.prg \
   TQStyleOptionToolButton.prg \
   TQStyleOptionViewItem.prg \
   TQStylePainter.prg \
   TQSystemTrayIcon.prg \
   TQTabBar.prg \
   TQTableView.prg \
   TQTableWidget.prg \
   TQTableWidgetItem.prg \
   TQTabWidget.prg \
   TQTextBlock.prg \
   TQTextBlockFormat.prg \
   TQTextBlockGroup.prg \
   TQTextBrowser.prg \
   TQTextBoundaryFinder.prg \
   TQTextCharFormat.prg \
   TQTextCodec.prg \
   TQTextCursor.prg \
   TQTextDecoder.prg \
   TQTextDocument.prg \
   TQTextDocumentFragment.prg \
   TQTextDocumentWriter.prg \
   TQTextEdit.prg \
   TQTextEncoder.prg \
   TQTextFormat.prg \
   TQTextFragment.prg \
   TQTextFrame.prg \
   TQTextFrameFormat.prg \
   TQTextImageFormat.prg \
   TQTextInlineObject.prg \
   TQTextItem.prg \
   TQTextLayout.prg \
   TQTextLength.prg \
   TQTextLine.prg \
   TQTextObject.prg \
   TQTextStream.prg \
   TQTimeEdit.prg \
   TQTimer.prg \
   TQToolBar.prg \
   TQToolBox.prg \
   TQToolButton.prg \
   TQTreeView.prg \
   TQTreeWidget.prg \
   TQTreeWidgetItem.prg \
   TQUrl.prg \
   TQVariant.prg \
   TQVBoxLayout.prg \
   TQWebFrame.prg \
   TQWebHistory.prg \
   TQWebHistoryInterface.prg \
   TQWebHistoryItem.prg \
   TQWebHitTestResult.prg \
   TQWebPage.prg \
   TQWebPluginFactory.prg \
   TQWebSecurityOrigin.prg \
   TQWebSettings.prg \
   TQWebView.prg \
   TQWheelEvent.prg \
   TQWidget.prg \
   TQWidgetAction.prg \
   TQWidgetItem.prg \
   TQWindowsStyle.prg \
   TQWindowsXPStyle.prg \
   TQWizard.prg \

# Don't delete this comment, it's here to ensure empty
# line above is kept intact.
