/*
 * $Id$
 *
 *
 * --------------------------------------------------------------------
 * WARNING: Automatically generated source file. DO NOT EDIT!
 *          Instead, edit corresponding .qth file,
 *          or the generator tool itself, and run regenarate.
 * --------------------------------------------------------------------
 */

extern QT_G_FUNC( release_QAbstractButton );
extern QT_G_FUNC( release_QAbstractItemDelegate );
extern QT_G_FUNC( release_QAbstractItemModel );
extern QT_G_FUNC( release_QAbstractItemView );
extern QT_G_FUNC( release_QAbstractListModel );
extern QT_G_FUNC( release_QAbstractProxyModel );
extern QT_G_FUNC( release_QAbstractPrintDialog );
extern QT_G_FUNC( release_QAbstractScrollArea );
extern QT_G_FUNC( release_QAbstractSlider );
extern QT_G_FUNC( release_QAbstractSpinBox );
extern QT_G_FUNC( release_QAbstractTableModel );
extern QT_G_FUNC( release_QAbstractTextDocumentLayout );
extern QT_G_FUNC( release_QAction );
extern QT_G_FUNC( release_QActionGroup );
extern QT_G_FUNC( release_QApplication );
extern QT_G_FUNC( release_QBitArray );
extern QT_G_FUNC( release_QBitmap );
extern QT_G_FUNC( release_QBoxLayout );
extern QT_G_FUNC( release_QBrush );
extern QT_G_FUNC( release_QButtonGroup );
extern QT_G_FUNC( release_QByteArray );
extern QT_G_FUNC( release_QCalendarWidget );
extern QT_G_FUNC( release_QCheckBox );
extern QT_G_FUNC( release_QClipboard );
extern QT_G_FUNC( release_QColor );
extern QT_G_FUNC( release_QColorDialog );
extern QT_G_FUNC( release_QComboBox );
extern QT_G_FUNC( release_QCommandLinkButton );
extern QT_G_FUNC( release_QCommonStyle );
extern QT_G_FUNC( release_QCompleter );
extern QT_G_FUNC( release_QConicalGradient );
extern QT_G_FUNC( release_QContextMenuEvent );
extern QT_G_FUNC( release_QCoreApplication );
extern QT_G_FUNC( release_QCursor );
extern QT_G_FUNC( release_QDataStream );
extern QT_G_FUNC( release_QDate );
extern QT_G_FUNC( release_QDateEdit );
extern QT_G_FUNC( release_QDateTime );
extern QT_G_FUNC( release_QDateTimeEdit );
extern QT_G_FUNC( release_QDesktopWidget );
extern QT_G_FUNC( release_QDial );
extern QT_G_FUNC( release_QDialog );
extern QT_G_FUNC( release_QDir );
extern QT_G_FUNC( release_QDirModel );
extern QT_G_FUNC( release_QDockWidget );
extern QT_G_FUNC( release_QDoubleSpinBox );
extern QT_G_FUNC( release_QDropEvent );
extern QT_G_FUNC( release_QDragMoveEvent );
extern QT_G_FUNC( release_QDragEnterEvent );
extern QT_G_FUNC( release_QDragLeaveEvent );
extern QT_G_FUNC( release_QErrorMessage );
extern QT_G_FUNC( release_QEvent );
extern QT_G_FUNC( release_QEventLoop );
extern QT_G_FUNC( release_QFile );
extern QT_G_FUNC( release_QFileDialog );
extern QT_G_FUNC( release_QFileInfo );
extern QT_G_FUNC( release_QFileIconProvider );
extern QT_G_FUNC( release_QFileSystemModel );
extern QT_G_FUNC( release_QFocusEvent );
extern QT_G_FUNC( release_QFocusFrame );
extern QT_G_FUNC( release_QFont );
extern QT_G_FUNC( release_QFontComboBox );
extern QT_G_FUNC( release_QFontDatabase );
extern QT_G_FUNC( release_QFontDialog );
extern QT_G_FUNC( release_QFontInfo );
extern QT_G_FUNC( release_QFontMetrics );
extern QT_G_FUNC( release_QFontMetricsF );
extern QT_G_FUNC( release_QFormLayout );
extern QT_G_FUNC( release_QFrame );
extern QT_G_FUNC( release_QFtp );
extern QT_G_FUNC( release_QGradient );
extern QT_G_FUNC( release_QGridLayout );
extern QT_G_FUNC( release_QGroupBox );
extern QT_G_FUNC( release_QHBoxLayout );
extern QT_G_FUNC( release_QHeaderView );
extern QT_G_FUNC( release_QHelpEvent );
extern QT_G_FUNC( release_QHttp );
extern QT_G_FUNC( release_QHttpRequestHeader );
extern QT_G_FUNC( release_QHttpResponseHeader );
extern QT_G_FUNC( release_QIcon );
extern QT_G_FUNC( release_QInputContext );
extern QT_G_FUNC( release_QInputMethodEvent );
extern QT_G_FUNC( release_QImage );
extern QT_G_FUNC( release_QImageReader );
extern QT_G_FUNC( release_QImageWriter );
extern QT_G_FUNC( release_QInputDialog );
extern QT_G_FUNC( release_QInputEvent );
extern QT_G_FUNC( release_QIODevice );
extern QT_G_FUNC( release_QItemSelection );
extern QT_G_FUNC( release_QItemSelectionModel );
extern QT_G_FUNC( release_QKeyEvent );
extern QT_G_FUNC( release_QKeySequence );
extern QT_G_FUNC( release_QLabel );
extern QT_G_FUNC( release_QLatin1Char );
extern QT_G_FUNC( release_QLatin1String );
extern QT_G_FUNC( release_QLayout );
extern QT_G_FUNC( release_QLayoutItem );
extern QT_G_FUNC( release_QLCDNumber );
extern QT_G_FUNC( release_QLine );
extern QT_G_FUNC( release_QLineF );
extern QT_G_FUNC( release_QLinearGradient );
extern QT_G_FUNC( release_QLineEdit );
extern QT_G_FUNC( release_QList );
extern QT_G_FUNC( release_QListView );
extern QT_G_FUNC( release_QListWidget );
extern QT_G_FUNC( release_QListWidgetItem );
extern QT_G_FUNC( release_QLocale );
extern QT_G_FUNC( release_QMainWindow );
extern QT_G_FUNC( release_QMatrix );
extern QT_G_FUNC( release_QMenu );
extern QT_G_FUNC( release_QMenuBar );
extern QT_G_FUNC( release_QMessageBox );
extern QT_G_FUNC( release_QMimeData );
extern QT_G_FUNC( release_QModelIndex );
extern QT_G_FUNC( release_QMouseEvent );
extern QT_G_FUNC( release_QMoveEvent );
extern QT_G_FUNC( release_QMovie );
extern QT_G_FUNC( release_QNetworkRequest );
extern QT_G_FUNC( release_QObject );
extern QT_G_FUNC( release_QPaintDevice );
extern QT_G_FUNC( release_QPainterPath );
extern QT_G_FUNC( release_QPageSetupDialog );
extern QT_G_FUNC( release_QPainter );
extern QT_G_FUNC( release_QPaintEvent );
extern QT_G_FUNC( release_QPalette );
extern QT_G_FUNC( release_QPen );
extern QT_G_FUNC( release_QPicture );
extern QT_G_FUNC( release_QPixmap );
extern QT_G_FUNC( release_QPoint );
extern QT_G_FUNC( release_QPointF );
extern QT_G_FUNC( release_QPolygon );
extern QT_G_FUNC( release_QPolygonF );
extern QT_G_FUNC( release_QPrintDialog );
extern QT_G_FUNC( release_QPrintEngine );
extern QT_G_FUNC( release_QPrinter );
extern QT_G_FUNC( release_QPrintPreviewDialog );
extern QT_G_FUNC( release_QProcess );
extern QT_G_FUNC( release_QProgressBar );
extern QT_G_FUNC( release_QProgressDialog );
extern QT_G_FUNC( release_QPushButton );
extern QT_G_FUNC( release_QRadialGradient );
extern QT_G_FUNC( release_QRadioButton );
extern QT_G_FUNC( release_QRect );
extern QT_G_FUNC( release_QRectF );
extern QT_G_FUNC( release_QRegion );
extern QT_G_FUNC( release_QRegExp );
extern QT_G_FUNC( release_QResizeEvent );
extern QT_G_FUNC( release_QResource );
extern QT_G_FUNC( release_QScrollArea );
extern QT_G_FUNC( release_QScrollBar );
extern QT_G_FUNC( release_QSessionManager );
extern QT_G_FUNC( release_QSignalMapper );
extern QT_G_FUNC( release_QSize );
extern QT_G_FUNC( release_QSizeF );
extern QT_G_FUNC( release_QSizeGrip );
extern QT_G_FUNC( release_QSizePolicy );
extern QT_G_FUNC( release_QSlider );
extern QT_G_FUNC( release_QSound );
extern QT_G_FUNC( release_QSpacerItem );
extern QT_G_FUNC( release_QSpinBox );
extern QT_G_FUNC( release_QSplashScreen );
extern QT_G_FUNC( release_QSplitter );
extern QT_G_FUNC( release_QStandardItem );
extern QT_G_FUNC( release_QStandardItemModel );
extern QT_G_FUNC( release_QStatusBar );
extern QT_G_FUNC( release_QStringList );
extern QT_G_FUNC( release_QStringListModel );
extern QT_G_FUNC( release_QStyle );
extern QT_G_FUNC( release_QStyledItemDelegate );
extern QT_G_FUNC( release_QStyleFactory );
extern QT_G_FUNC( release_QStyleHintReturn );
extern QT_G_FUNC( release_QStyleHintReturnMask );
extern QT_G_FUNC( release_QStyleHintReturnVariant );
extern QT_G_FUNC( release_QStyleOption );
extern QT_G_FUNC( release_QStyleOptionButton );
extern QT_G_FUNC( release_QStyleOptionComboBox );
extern QT_G_FUNC( release_QStyleOptionComplex );
extern QT_G_FUNC( release_QStyleOptionDockWidget );
extern QT_G_FUNC( release_QStyleOptionFocusRect );
extern QT_G_FUNC( release_QStyleOptionFrame );
extern QT_G_FUNC( release_QStyleOptionGroupBox );
extern QT_G_FUNC( release_QStyleOptionHeader );
extern QT_G_FUNC( release_QStyleOptionMenuItem );
extern QT_G_FUNC( release_QStyleOptionProgressBar );
extern QT_G_FUNC( release_QStyleOptionSizeGrip );
extern QT_G_FUNC( release_QStyleOptionSlider );
extern QT_G_FUNC( release_QStyleOptionSpinBox );
extern QT_G_FUNC( release_QStyleOptionTab );
extern QT_G_FUNC( release_QStyleOptionTabBarBase );
extern QT_G_FUNC( release_QStyleOptionTabWidgetFrame );
extern QT_G_FUNC( release_QStyleOptionTitleBar );
extern QT_G_FUNC( release_QStyleOptionToolBar );
extern QT_G_FUNC( release_QStyleOptionToolBox );
extern QT_G_FUNC( release_QStyleOptionToolButton );
extern QT_G_FUNC( release_QStyleOptionViewItem );
extern QT_G_FUNC( release_QStylePainter );
extern QT_G_FUNC( release_QSyntaxHighlighter );
extern QT_G_FUNC( release_QSystemTrayIcon );
extern QT_G_FUNC( release_QTabBar );
extern QT_G_FUNC( release_QTableView );
extern QT_G_FUNC( release_QTableWidget );
extern QT_G_FUNC( release_QTableWidgetItem );
extern QT_G_FUNC( release_QTabWidget );
extern QT_G_FUNC( release_QTableWidgetSelectionRange );
extern QT_G_FUNC( release_QTextBlock );
extern QT_G_FUNC( release_QTextBlockFormat );
extern QT_G_FUNC( release_QTextBlockGroup );
extern QT_G_FUNC( release_QTextBrowser );
extern QT_G_FUNC( release_QTextBoundaryFinder );
extern QT_G_FUNC( release_QTextCharFormat );
extern QT_G_FUNC( release_QTextCodec );
extern QT_G_FUNC( release_QTextCursor );
extern QT_G_FUNC( release_QTextDecoder );
extern QT_G_FUNC( release_QTextDocument );
extern QT_G_FUNC( release_QTextDocumentFragment );
extern QT_G_FUNC( release_QTextDocumentWriter );
extern QT_G_FUNC( release_QTextEdit );
extern QT_G_FUNC( release_QTextEncoder );
extern QT_G_FUNC( release_QTextFormat );
extern QT_G_FUNC( release_QTextFragment );
extern QT_G_FUNC( release_QTextFrame );
extern QT_G_FUNC( release_QTextFrameFormat );
extern QT_G_FUNC( release_QTextImageFormat );
extern QT_G_FUNC( release_QTextInlineObject );
extern QT_G_FUNC( release_QTextItem );
extern QT_G_FUNC( release_QTextLayout );
extern QT_G_FUNC( release_QTextLength );
extern QT_G_FUNC( release_QTextLine );
extern QT_G_FUNC( release_QTextListFormat );
extern QT_G_FUNC( release_QTextObject );
extern QT_G_FUNC( release_QTextOption );
extern QT_G_FUNC( release_QTextStream );
extern QT_G_FUNC( release_QTextTableFormat );
extern QT_G_FUNC( release_QThread );
extern QT_G_FUNC( release_QTime );
extern QT_G_FUNC( release_QTimeEdit );
extern QT_G_FUNC( release_QTimer );
extern QT_G_FUNC( release_QToolBar );
extern QT_G_FUNC( release_QToolBox );
extern QT_G_FUNC( release_QToolButton );
extern QT_G_FUNC( release_QTransform );
extern QT_G_FUNC( release_QTranslator );
extern QT_G_FUNC( release_QTreeView );
extern QT_G_FUNC( release_QTreeWidget );
extern QT_G_FUNC( release_QTreeWidgetItem );
extern QT_G_FUNC( release_QUiLoader );
extern QT_G_FUNC( release_QUrl );
extern QT_G_FUNC( release_QValidator );
extern QT_G_FUNC( release_QVariant );
extern QT_G_FUNC( release_QVBoxLayout );
extern QT_G_FUNC( release_QWebFrame );
extern QT_G_FUNC( release_QWebHistory );
extern QT_G_FUNC( release_QWebHistoryInterface );
extern QT_G_FUNC( release_QWebHistoryItem );
extern QT_G_FUNC( release_QWebHitTestResult );
extern QT_G_FUNC( release_QWebPage );
extern QT_G_FUNC( release_QWebPluginFactory );
extern QT_G_FUNC( release_QWebSecurityOrigin );
extern QT_G_FUNC( release_QWebSettings );
extern QT_G_FUNC( release_QWebView );
extern QT_G_FUNC( release_QWheelEvent );
extern QT_G_FUNC( release_QWidget );
extern QT_G_FUNC( release_QWidgetAction );
extern QT_G_FUNC( release_QWidgetItem );
extern QT_G_FUNC( release_QWindowsStyle );
extern QT_G_FUNC( release_QWindowsXPStyle );
extern QT_G_FUNC( release_QWizard );
extern QT_G_FUNC( release_QWizardPage );

extern void * gcAllocate_QAbstractButton( void * pObj );
extern void * gcAllocate_QAbstractItemDelegate( void * pObj );
extern void * gcAllocate_QAbstractItemModel( void * pObj );
extern void * gcAllocate_QAbstractItemView( void * pObj );
extern void * gcAllocate_QAbstractListModel( void * pObj );
extern void * gcAllocate_QAbstractProxyModel( void * pObj );
extern void * gcAllocate_QAbstractPrintDialog( void * pObj );
extern void * gcAllocate_QAbstractScrollArea( void * pObj );
extern void * gcAllocate_QAbstractSlider( void * pObj );
extern void * gcAllocate_QAbstractSpinBox( void * pObj );
extern void * gcAllocate_QAbstractTableModel( void * pObj );
extern void * gcAllocate_QAbstractTextDocumentLayout( void * pObj );
extern void * gcAllocate_QAction( void * pObj );
extern void * gcAllocate_QActionGroup( void * pObj );
extern void * gcAllocate_QApplication( void * pObj );
extern void * gcAllocate_QBitArray( void * pObj );
extern void * gcAllocate_QBitmap( void * pObj );
extern void * gcAllocate_QBoxLayout( void * pObj );
extern void * gcAllocate_QBrush( void * pObj );
extern void * gcAllocate_QButtonGroup( void * pObj );
extern void * gcAllocate_QByteArray( void * pObj );
extern void * gcAllocate_QCalendarWidget( void * pObj );
extern void * gcAllocate_QCheckBox( void * pObj );
extern void * gcAllocate_QClipboard( void * pObj );
extern void * gcAllocate_QColor( void * pObj );
extern void * gcAllocate_QColorDialog( void * pObj );
extern void * gcAllocate_QComboBox( void * pObj );
extern void * gcAllocate_QCommandLinkButton( void * pObj );
extern void * gcAllocate_QCommonStyle( void * pObj );
extern void * gcAllocate_QCompleter( void * pObj );
extern void * gcAllocate_QConicalGradient( void * pObj );
extern void * gcAllocate_QContextMenuEvent( void * pObj );
extern void * gcAllocate_QCoreApplication( void * pObj );
extern void * gcAllocate_QCursor( void * pObj );
extern void * gcAllocate_QDataStream( void * pObj );
extern void * gcAllocate_QDate( void * pObj );
extern void * gcAllocate_QDateEdit( void * pObj );
extern void * gcAllocate_QDateTime( void * pObj );
extern void * gcAllocate_QDateTimeEdit( void * pObj );
extern void * gcAllocate_QDesktopWidget( void * pObj );
extern void * gcAllocate_QDial( void * pObj );
extern void * gcAllocate_QDialog( void * pObj );
extern void * gcAllocate_QDir( void * pObj );
extern void * gcAllocate_QDirModel( void * pObj );
extern void * gcAllocate_QDockWidget( void * pObj );
extern void * gcAllocate_QDoubleSpinBox( void * pObj );
extern void * gcAllocate_QDropEvent( void * pObj );
extern void * gcAllocate_QDragMoveEvent( void * pObj );
extern void * gcAllocate_QDragEnterEvent( void * pObj );
extern void * gcAllocate_QDragLeaveEvent( void * pObj );
extern void * gcAllocate_QErrorMessage( void * pObj );
extern void * gcAllocate_QEvent( void * pObj );
extern void * gcAllocate_QEventLoop( void * pObj );
extern void * gcAllocate_QFile( void * pObj );
extern void * gcAllocate_QFileDialog( void * pObj );
extern void * gcAllocate_QFileInfo( void * pObj );
extern void * gcAllocate_QFileIconProvider( void * pObj );
extern void * gcAllocate_QFileSystemModel( void * pObj );
extern void * gcAllocate_QFocusEvent( void * pObj );
extern void * gcAllocate_QFocusFrame( void * pObj );
extern void * gcAllocate_QFont( void * pObj );
extern void * gcAllocate_QFontComboBox( void * pObj );
extern void * gcAllocate_QFontDatabase( void * pObj );
extern void * gcAllocate_QFontDialog( void * pObj );
extern void * gcAllocate_QFontInfo( void * pObj );
extern void * gcAllocate_QFontMetrics( void * pObj );
extern void * gcAllocate_QFontMetricsF( void * pObj );
extern void * gcAllocate_QFormLayout( void * pObj );
extern void * gcAllocate_QFrame( void * pObj );
extern void * gcAllocate_QFtp( void * pObj );
extern void * gcAllocate_QGradient( void * pObj );
extern void * gcAllocate_QGridLayout( void * pObj );
extern void * gcAllocate_QGroupBox( void * pObj );
extern void * gcAllocate_QHBoxLayout( void * pObj );
extern void * gcAllocate_QHeaderView( void * pObj );
extern void * gcAllocate_QHelpEvent( void * pObj );
extern void * gcAllocate_QHttp( void * pObj );
extern void * gcAllocate_QHttpRequestHeader( void * pObj );
extern void * gcAllocate_QHttpResponseHeader( void * pObj );
extern void * gcAllocate_QIcon( void * pObj );
extern void * gcAllocate_QInputContext( void * pObj );
extern void * gcAllocate_QInputMethodEvent( void * pObj );
extern void * gcAllocate_QImage( void * pObj );
extern void * gcAllocate_QImageReader( void * pObj );
extern void * gcAllocate_QImageWriter( void * pObj );
extern void * gcAllocate_QInputDialog( void * pObj );
extern void * gcAllocate_QInputEvent( void * pObj );
extern void * gcAllocate_QIODevice( void * pObj );
extern void * gcAllocate_QItemSelection( void * pObj );
extern void * gcAllocate_QItemSelectionModel( void * pObj );
extern void * gcAllocate_QKeyEvent( void * pObj );
extern void * gcAllocate_QKeySequence( void * pObj );
extern void * gcAllocate_QLabel( void * pObj );
extern void * gcAllocate_QLatin1Char( void * pObj );
extern void * gcAllocate_QLatin1String( void * pObj );
extern void * gcAllocate_QLayout( void * pObj );
extern void * gcAllocate_QLayoutItem( void * pObj );
extern void * gcAllocate_QLCDNumber( void * pObj );
extern void * gcAllocate_QLine( void * pObj );
extern void * gcAllocate_QLineF( void * pObj );
extern void * gcAllocate_QLinearGradient( void * pObj );
extern void * gcAllocate_QLineEdit( void * pObj );
extern void * gcAllocate_QList( void * pObj );
extern void * gcAllocate_QListView( void * pObj );
extern void * gcAllocate_QListWidget( void * pObj );
extern void * gcAllocate_QListWidgetItem( void * pObj );
extern void * gcAllocate_QLocale( void * pObj );
extern void * gcAllocate_QMainWindow( void * pObj );
extern void * gcAllocate_QMatrix( void * pObj );
extern void * gcAllocate_QMenu( void * pObj );
extern void * gcAllocate_QMenuBar( void * pObj );
extern void * gcAllocate_QMessageBox( void * pObj );
extern void * gcAllocate_QMimeData( void * pObj );
extern void * gcAllocate_QModelIndex( void * pObj );
extern void * gcAllocate_QMouseEvent( void * pObj );
extern void * gcAllocate_QMoveEvent( void * pObj );
extern void * gcAllocate_QMovie( void * pObj );
extern void * gcAllocate_QNetworkRequest( void * pObj );
extern void * gcAllocate_QObject( void * pObj );
extern void * gcAllocate_QPaintDevice( void * pObj );
extern void * gcAllocate_QPainterPath( void * pObj );
extern void * gcAllocate_QPageSetupDialog( void * pObj );
extern void * gcAllocate_QPainter( void * pObj );
extern void * gcAllocate_QPaintEvent( void * pObj );
extern void * gcAllocate_QPalette( void * pObj );
extern void * gcAllocate_QPen( void * pObj );
extern void * gcAllocate_QPicture( void * pObj );
extern void * gcAllocate_QPixmap( void * pObj );
extern void * gcAllocate_QPoint( void * pObj );
extern void * gcAllocate_QPointF( void * pObj );
extern void * gcAllocate_QPolygon( void * pObj );
extern void * gcAllocate_QPolygonF( void * pObj );
extern void * gcAllocate_QPrintDialog( void * pObj );
extern void * gcAllocate_QPrintEngine( void * pObj );
extern void * gcAllocate_QPrinter( void * pObj );
extern void * gcAllocate_QPrintPreviewDialog( void * pObj );
extern void * gcAllocate_QProcess( void * pObj );
extern void * gcAllocate_QProgressBar( void * pObj );
extern void * gcAllocate_QProgressDialog( void * pObj );
extern void * gcAllocate_QPushButton( void * pObj );
extern void * gcAllocate_QRadialGradient( void * pObj );
extern void * gcAllocate_QRadioButton( void * pObj );
extern void * gcAllocate_QRect( void * pObj );
extern void * gcAllocate_QRectF( void * pObj );
extern void * gcAllocate_QRegion( void * pObj );
extern void * gcAllocate_QRegExp( void * pObj );
extern void * gcAllocate_QResizeEvent( void * pObj );
extern void * gcAllocate_QResource( void * pObj );
extern void * gcAllocate_QScrollArea( void * pObj );
extern void * gcAllocate_QScrollBar( void * pObj );
extern void * gcAllocate_QSessionManager( void * pObj );
extern void * gcAllocate_QSignalMapper( void * pObj );
extern void * gcAllocate_QSize( void * pObj );
extern void * gcAllocate_QSizeF( void * pObj );
extern void * gcAllocate_QSizeGrip( void * pObj );
extern void * gcAllocate_QSizePolicy( void * pObj );
extern void * gcAllocate_QSlider( void * pObj );
extern void * gcAllocate_QSound( void * pObj );
extern void * gcAllocate_QSpacerItem( void * pObj );
extern void * gcAllocate_QSpinBox( void * pObj );
extern void * gcAllocate_QSplashScreen( void * pObj );
extern void * gcAllocate_QSplitter( void * pObj );
extern void * gcAllocate_QStandardItem( void * pObj );
extern void * gcAllocate_QStandardItemModel( void * pObj );
extern void * gcAllocate_QStatusBar( void * pObj );
extern void * gcAllocate_QStringList( void * pObj );
extern void * gcAllocate_QStringListModel( void * pObj );
extern void * gcAllocate_QStyle( void * pObj );
extern void * gcAllocate_QStyledItemDelegate( void * pObj );
extern void * gcAllocate_QStyleFactory( void * pObj );
extern void * gcAllocate_QStyleHintReturn( void * pObj );
extern void * gcAllocate_QStyleHintReturnMask( void * pObj );
extern void * gcAllocate_QStyleHintReturnVariant( void * pObj );
extern void * gcAllocate_QStyleOption( void * pObj );
extern void * gcAllocate_QStyleOptionButton( void * pObj );
extern void * gcAllocate_QStyleOptionComboBox( void * pObj );
extern void * gcAllocate_QStyleOptionComplex( void * pObj );
extern void * gcAllocate_QStyleOptionDockWidget( void * pObj );
extern void * gcAllocate_QStyleOptionFocusRect( void * pObj );
extern void * gcAllocate_QStyleOptionFrame( void * pObj );
extern void * gcAllocate_QStyleOptionGroupBox( void * pObj );
extern void * gcAllocate_QStyleOptionHeader( void * pObj );
extern void * gcAllocate_QStyleOptionMenuItem( void * pObj );
extern void * gcAllocate_QStyleOptionProgressBar( void * pObj );
extern void * gcAllocate_QStyleOptionSizeGrip( void * pObj );
extern void * gcAllocate_QStyleOptionSlider( void * pObj );
extern void * gcAllocate_QStyleOptionSpinBox( void * pObj );
extern void * gcAllocate_QStyleOptionTab( void * pObj );
extern void * gcAllocate_QStyleOptionTabBarBase( void * pObj );
extern void * gcAllocate_QStyleOptionTabWidgetFrame( void * pObj );
extern void * gcAllocate_QStyleOptionTitleBar( void * pObj );
extern void * gcAllocate_QStyleOptionToolBar( void * pObj );
extern void * gcAllocate_QStyleOptionToolBox( void * pObj );
extern void * gcAllocate_QStyleOptionToolButton( void * pObj );
extern void * gcAllocate_QStyleOptionViewItem( void * pObj );
extern void * gcAllocate_QStylePainter( void * pObj );
extern void * gcAllocate_QSyntaxHighlighter( void * pObj );
extern void * gcAllocate_QSystemTrayIcon( void * pObj );
extern void * gcAllocate_QTabBar( void * pObj );
extern void * gcAllocate_QTableView( void * pObj );
extern void * gcAllocate_QTableWidget( void * pObj );
extern void * gcAllocate_QTableWidgetItem( void * pObj );
extern void * gcAllocate_QTabWidget( void * pObj );
extern void * gcAllocate_QTableWidgetSelectionRange( void * pObj );
extern void * gcAllocate_QTextBlock( void * pObj );
extern void * gcAllocate_QTextBlockFormat( void * pObj );
extern void * gcAllocate_QTextBlockGroup( void * pObj );
extern void * gcAllocate_QTextBrowser( void * pObj );
extern void * gcAllocate_QTextBoundaryFinder( void * pObj );
extern void * gcAllocate_QTextCharFormat( void * pObj );
extern void * gcAllocate_QTextCodec( void * pObj );
extern void * gcAllocate_QTextCursor( void * pObj );
extern void * gcAllocate_QTextDecoder( void * pObj );
extern void * gcAllocate_QTextDocument( void * pObj );
extern void * gcAllocate_QTextDocumentFragment( void * pObj );
extern void * gcAllocate_QTextDocumentWriter( void * pObj );
extern void * gcAllocate_QTextEdit( void * pObj );
extern void * gcAllocate_QTextEncoder( void * pObj );
extern void * gcAllocate_QTextFormat( void * pObj );
extern void * gcAllocate_QTextFragment( void * pObj );
extern void * gcAllocate_QTextFrame( void * pObj );
extern void * gcAllocate_QTextFrameFormat( void * pObj );
extern void * gcAllocate_QTextImageFormat( void * pObj );
extern void * gcAllocate_QTextInlineObject( void * pObj );
extern void * gcAllocate_QTextItem( void * pObj );
extern void * gcAllocate_QTextLayout( void * pObj );
extern void * gcAllocate_QTextLength( void * pObj );
extern void * gcAllocate_QTextLine( void * pObj );
extern void * gcAllocate_QTextListFormat( void * pObj );
extern void * gcAllocate_QTextObject( void * pObj );
extern void * gcAllocate_QTextOption( void * pObj );
extern void * gcAllocate_QTextStream( void * pObj );
extern void * gcAllocate_QTextTableFormat( void * pObj );
extern void * gcAllocate_QThread( void * pObj );
extern void * gcAllocate_QTime( void * pObj );
extern void * gcAllocate_QTimeEdit( void * pObj );
extern void * gcAllocate_QTimer( void * pObj );
extern void * gcAllocate_QToolBar( void * pObj );
extern void * gcAllocate_QToolBox( void * pObj );
extern void * gcAllocate_QToolButton( void * pObj );
extern void * gcAllocate_QTransform( void * pObj );
extern void * gcAllocate_QTranslator( void * pObj );
extern void * gcAllocate_QTreeView( void * pObj );
extern void * gcAllocate_QTreeWidget( void * pObj );
extern void * gcAllocate_QTreeWidgetItem( void * pObj );
extern void * gcAllocate_QUiLoader( void * pObj );
extern void * gcAllocate_QUrl( void * pObj );
extern void * gcAllocate_QValidator( void * pObj );
extern void * gcAllocate_QVariant( void * pObj );
extern void * gcAllocate_QVBoxLayout( void * pObj );
extern void * gcAllocate_QWebFrame( void * pObj );
extern void * gcAllocate_QWebHistory( void * pObj );
extern void * gcAllocate_QWebHistoryInterface( void * pObj );
extern void * gcAllocate_QWebHistoryItem( void * pObj );
extern void * gcAllocate_QWebHitTestResult( void * pObj );
extern void * gcAllocate_QWebPage( void * pObj );
extern void * gcAllocate_QWebPluginFactory( void * pObj );
extern void * gcAllocate_QWebSecurityOrigin( void * pObj );
extern void * gcAllocate_QWebSettings( void * pObj );
extern void * gcAllocate_QWebView( void * pObj );
extern void * gcAllocate_QWheelEvent( void * pObj );
extern void * gcAllocate_QWidget( void * pObj );
extern void * gcAllocate_QWidgetAction( void * pObj );
extern void * gcAllocate_QWidgetItem( void * pObj );
extern void * gcAllocate_QWindowsStyle( void * pObj );
extern void * gcAllocate_QWindowsXPStyle( void * pObj );
extern void * gcAllocate_QWizard( void * pObj );
extern void * gcAllocate_QWizardPage( void * pObj );

