/*
 * $Id$
 */

/* -------------------------------------------------------------------- */
/* WARNING: Automatically generated source file. DO NOT EDIT!           */
/*          Instead, edit corresponding .qth file,                      */
/*          or the generator tool itself, and run regenarate.           */
/* -------------------------------------------------------------------- */

extern QT_G_FUNC( hbqt_gcRelease_QAbstractButton );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractItemDelegate );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractItemModel );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractItemView );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractListModel );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractProxyModel );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractPrintDialog );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractScrollArea );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractSlider );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractSpinBox );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractTableModel );
extern QT_G_FUNC( hbqt_gcRelease_QAbstractTextDocumentLayout );
extern QT_G_FUNC( hbqt_gcRelease_QAction );
extern QT_G_FUNC( hbqt_gcRelease_QActionGroup );
extern QT_G_FUNC( hbqt_gcRelease_QApplication );
extern QT_G_FUNC( hbqt_gcRelease_QBitArray );
extern QT_G_FUNC( hbqt_gcRelease_QBitmap );
extern QT_G_FUNC( hbqt_gcRelease_QBoxLayout );
extern QT_G_FUNC( hbqt_gcRelease_QBrush );
extern QT_G_FUNC( hbqt_gcRelease_QButtonGroup );
extern QT_G_FUNC( hbqt_gcRelease_QByteArray );
extern QT_G_FUNC( hbqt_gcRelease_QCalendarWidget );
extern QT_G_FUNC( hbqt_gcRelease_QCheckBox );
extern QT_G_FUNC( hbqt_gcRelease_QClipboard );
extern QT_G_FUNC( hbqt_gcRelease_QColor );
extern QT_G_FUNC( hbqt_gcRelease_QColorDialog );
extern QT_G_FUNC( hbqt_gcRelease_QComboBox );
extern QT_G_FUNC( hbqt_gcRelease_QCommandLinkButton );
extern QT_G_FUNC( hbqt_gcRelease_QCommonStyle );
extern QT_G_FUNC( hbqt_gcRelease_QCompleter );
extern QT_G_FUNC( hbqt_gcRelease_QConicalGradient );
extern QT_G_FUNC( hbqt_gcRelease_QContextMenuEvent );
extern QT_G_FUNC( hbqt_gcRelease_QCoreApplication );
extern QT_G_FUNC( hbqt_gcRelease_QCursor );
extern QT_G_FUNC( hbqt_gcRelease_QDataStream );
extern QT_G_FUNC( hbqt_gcRelease_QDate );
extern QT_G_FUNC( hbqt_gcRelease_QDateEdit );
extern QT_G_FUNC( hbqt_gcRelease_QDateTime );
extern QT_G_FUNC( hbqt_gcRelease_QDateTimeEdit );
extern QT_G_FUNC( hbqt_gcRelease_QDesktopWidget );
extern QT_G_FUNC( hbqt_gcRelease_QDial );
extern QT_G_FUNC( hbqt_gcRelease_QDialog );
extern QT_G_FUNC( hbqt_gcRelease_QDir );
extern QT_G_FUNC( hbqt_gcRelease_QDirModel );
extern QT_G_FUNC( hbqt_gcRelease_QDockWidget );
extern QT_G_FUNC( hbqt_gcRelease_QDoubleSpinBox );
extern QT_G_FUNC( hbqt_gcRelease_QDropEvent );
extern QT_G_FUNC( hbqt_gcRelease_QDragMoveEvent );
extern QT_G_FUNC( hbqt_gcRelease_QDragEnterEvent );
extern QT_G_FUNC( hbqt_gcRelease_QDragLeaveEvent );
extern QT_G_FUNC( hbqt_gcRelease_QErrorMessage );
extern QT_G_FUNC( hbqt_gcRelease_QEvent );
extern QT_G_FUNC( hbqt_gcRelease_QEventLoop );
extern QT_G_FUNC( hbqt_gcRelease_QFile );
extern QT_G_FUNC( hbqt_gcRelease_QFileDialog );
extern QT_G_FUNC( hbqt_gcRelease_QFileInfo );
extern QT_G_FUNC( hbqt_gcRelease_QFileIconProvider );
extern QT_G_FUNC( hbqt_gcRelease_QFileSystemModel );
extern QT_G_FUNC( hbqt_gcRelease_QFocusEvent );
extern QT_G_FUNC( hbqt_gcRelease_QFocusFrame );
extern QT_G_FUNC( hbqt_gcRelease_QFont );
extern QT_G_FUNC( hbqt_gcRelease_QFontComboBox );
extern QT_G_FUNC( hbqt_gcRelease_QFontDatabase );
extern QT_G_FUNC( hbqt_gcRelease_QFontDialog );
extern QT_G_FUNC( hbqt_gcRelease_QFontInfo );
extern QT_G_FUNC( hbqt_gcRelease_QFontMetrics );
extern QT_G_FUNC( hbqt_gcRelease_QFontMetricsF );
extern QT_G_FUNC( hbqt_gcRelease_QFormLayout );
extern QT_G_FUNC( hbqt_gcRelease_QFrame );
extern QT_G_FUNC( hbqt_gcRelease_QFtp );
extern QT_G_FUNC( hbqt_gcRelease_QGradient );
extern QT_G_FUNC( hbqt_gcRelease_QGridLayout );
extern QT_G_FUNC( hbqt_gcRelease_QGroupBox );
extern QT_G_FUNC( hbqt_gcRelease_QHBoxLayout );
extern QT_G_FUNC( hbqt_gcRelease_QHeaderView );
extern QT_G_FUNC( hbqt_gcRelease_QHelpEvent );
extern QT_G_FUNC( hbqt_gcRelease_QHttp );
extern QT_G_FUNC( hbqt_gcRelease_QHttpHeader );
extern QT_G_FUNC( hbqt_gcRelease_QHttpRequestHeader );
extern QT_G_FUNC( hbqt_gcRelease_QHttpResponseHeader );
extern QT_G_FUNC( hbqt_gcRelease_QIcon );
extern QT_G_FUNC( hbqt_gcRelease_QInputContext );
extern QT_G_FUNC( hbqt_gcRelease_QInputMethodEvent );
extern QT_G_FUNC( hbqt_gcRelease_QImage );
extern QT_G_FUNC( hbqt_gcRelease_QImageReader );
extern QT_G_FUNC( hbqt_gcRelease_QImageWriter );
extern QT_G_FUNC( hbqt_gcRelease_QInputDialog );
extern QT_G_FUNC( hbqt_gcRelease_QInputEvent );
extern QT_G_FUNC( hbqt_gcRelease_QIODevice );
extern QT_G_FUNC( hbqt_gcRelease_QItemSelection );
extern QT_G_FUNC( hbqt_gcRelease_QItemSelectionModel );
extern QT_G_FUNC( hbqt_gcRelease_QKeyEvent );
extern QT_G_FUNC( hbqt_gcRelease_QKeySequence );
extern QT_G_FUNC( hbqt_gcRelease_QLabel );
extern QT_G_FUNC( hbqt_gcRelease_QLatin1Char );
extern QT_G_FUNC( hbqt_gcRelease_QLatin1String );
extern QT_G_FUNC( hbqt_gcRelease_QLayout );
extern QT_G_FUNC( hbqt_gcRelease_QLayoutItem );
extern QT_G_FUNC( hbqt_gcRelease_QLCDNumber );
extern QT_G_FUNC( hbqt_gcRelease_QLine );
extern QT_G_FUNC( hbqt_gcRelease_QLineF );
extern QT_G_FUNC( hbqt_gcRelease_QLinearGradient );
extern QT_G_FUNC( hbqt_gcRelease_QLineEdit );
extern QT_G_FUNC( hbqt_gcRelease_QList );
extern QT_G_FUNC( hbqt_gcRelease_QListView );
extern QT_G_FUNC( hbqt_gcRelease_QListWidget );
extern QT_G_FUNC( hbqt_gcRelease_QListWidgetItem );
extern QT_G_FUNC( hbqt_gcRelease_QLocale );
extern QT_G_FUNC( hbqt_gcRelease_QMainWindow );
extern QT_G_FUNC( hbqt_gcRelease_QMatrix );
extern QT_G_FUNC( hbqt_gcRelease_QMdiArea );
extern QT_G_FUNC( hbqt_gcRelease_QMdiSubWindow );
extern QT_G_FUNC( hbqt_gcRelease_QMenu );
extern QT_G_FUNC( hbqt_gcRelease_QMenuBar );
extern QT_G_FUNC( hbqt_gcRelease_QMessageBox );
extern QT_G_FUNC( hbqt_gcRelease_QMimeData );
extern QT_G_FUNC( hbqt_gcRelease_QModelIndex );
extern QT_G_FUNC( hbqt_gcRelease_QMouseEvent );
extern QT_G_FUNC( hbqt_gcRelease_QMoveEvent );
extern QT_G_FUNC( hbqt_gcRelease_QMovie );
extern QT_G_FUNC( hbqt_gcRelease_QNetworkRequest );
extern QT_G_FUNC( hbqt_gcRelease_QObject );
extern QT_G_FUNC( hbqt_gcRelease_QPaintDevice );
extern QT_G_FUNC( hbqt_gcRelease_QPainterPath );
extern QT_G_FUNC( hbqt_gcRelease_QPageSetupDialog );
extern QT_G_FUNC( hbqt_gcRelease_QPainter );
extern QT_G_FUNC( hbqt_gcRelease_QPaintEvent );
extern QT_G_FUNC( hbqt_gcRelease_QPalette );
extern QT_G_FUNC( hbqt_gcRelease_QPen );
extern QT_G_FUNC( hbqt_gcRelease_QPicture );
extern QT_G_FUNC( hbqt_gcRelease_QPixmap );
extern QT_G_FUNC( hbqt_gcRelease_QPlainTextEdit );
extern QT_G_FUNC( hbqt_gcRelease_QPoint );
extern QT_G_FUNC( hbqt_gcRelease_QPointF );
extern QT_G_FUNC( hbqt_gcRelease_QPolygon );
extern QT_G_FUNC( hbqt_gcRelease_QPolygonF );
extern QT_G_FUNC( hbqt_gcRelease_QPrintDialog );
extern QT_G_FUNC( hbqt_gcRelease_QPrintEngine );
extern QT_G_FUNC( hbqt_gcRelease_QPrinter );
extern QT_G_FUNC( hbqt_gcRelease_QPrintPreviewDialog );
extern QT_G_FUNC( hbqt_gcRelease_QProcess );
extern QT_G_FUNC( hbqt_gcRelease_QProgressBar );
extern QT_G_FUNC( hbqt_gcRelease_QProgressDialog );
extern QT_G_FUNC( hbqt_gcRelease_QPushButton );
extern QT_G_FUNC( hbqt_gcRelease_QRadialGradient );
extern QT_G_FUNC( hbqt_gcRelease_QRadioButton );
extern QT_G_FUNC( hbqt_gcRelease_QRect );
extern QT_G_FUNC( hbqt_gcRelease_QRectF );
extern QT_G_FUNC( hbqt_gcRelease_QRegion );
extern QT_G_FUNC( hbqt_gcRelease_QRegExp );
extern QT_G_FUNC( hbqt_gcRelease_QResizeEvent );
extern QT_G_FUNC( hbqt_gcRelease_QResource );
extern QT_G_FUNC( hbqt_gcRelease_QScrollArea );
extern QT_G_FUNC( hbqt_gcRelease_QScrollBar );
extern QT_G_FUNC( hbqt_gcRelease_QSessionManager );
extern QT_G_FUNC( hbqt_gcRelease_QSettings );
extern QT_G_FUNC( hbqt_gcRelease_QSignalMapper );
extern QT_G_FUNC( hbqt_gcRelease_QSize );
extern QT_G_FUNC( hbqt_gcRelease_QSizeF );
extern QT_G_FUNC( hbqt_gcRelease_QSizeGrip );
extern QT_G_FUNC( hbqt_gcRelease_QSizePolicy );
extern QT_G_FUNC( hbqt_gcRelease_QSlider );
extern QT_G_FUNC( hbqt_gcRelease_QSound );
extern QT_G_FUNC( hbqt_gcRelease_QSpacerItem );
extern QT_G_FUNC( hbqt_gcRelease_QSpinBox );
extern QT_G_FUNC( hbqt_gcRelease_QSplashScreen );
extern QT_G_FUNC( hbqt_gcRelease_QSplitter );
extern QT_G_FUNC( hbqt_gcRelease_QStandardItem );
extern QT_G_FUNC( hbqt_gcRelease_QStandardItemModel );
extern QT_G_FUNC( hbqt_gcRelease_QStatusBar );
extern QT_G_FUNC( hbqt_gcRelease_QStringList );
extern QT_G_FUNC( hbqt_gcRelease_QStringListModel );
extern QT_G_FUNC( hbqt_gcRelease_QStyle );
extern QT_G_FUNC( hbqt_gcRelease_QStyledItemDelegate );
extern QT_G_FUNC( hbqt_gcRelease_QStyleFactory );
extern QT_G_FUNC( hbqt_gcRelease_QStyleHintReturn );
extern QT_G_FUNC( hbqt_gcRelease_QStyleHintReturnMask );
extern QT_G_FUNC( hbqt_gcRelease_QStyleHintReturnVariant );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOption );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionButton );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionComboBox );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionComplex );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionDockWidget );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionFocusRect );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionFrame );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionGroupBox );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionHeader );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionMenuItem );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionProgressBar );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionSizeGrip );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionSlider );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionSpinBox );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionTab );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionTabBarBase );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionTabWidgetFrame );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionTitleBar );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionToolBar );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionToolBox );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionToolButton );
extern QT_G_FUNC( hbqt_gcRelease_QStyleOptionViewItem );
extern QT_G_FUNC( hbqt_gcRelease_QStylePainter );
extern QT_G_FUNC( hbqt_gcRelease_QSyntaxHighlighter );
extern QT_G_FUNC( hbqt_gcRelease_QSystemTrayIcon );
extern QT_G_FUNC( hbqt_gcRelease_QTabBar );
extern QT_G_FUNC( hbqt_gcRelease_QTableView );
extern QT_G_FUNC( hbqt_gcRelease_QTableWidget );
extern QT_G_FUNC( hbqt_gcRelease_QTableWidgetItem );
extern QT_G_FUNC( hbqt_gcRelease_QTabWidget );
extern QT_G_FUNC( hbqt_gcRelease_QTableWidgetSelectionRange );
extern QT_G_FUNC( hbqt_gcRelease_QTextBlock );
extern QT_G_FUNC( hbqt_gcRelease_QTextBlockFormat );
extern QT_G_FUNC( hbqt_gcRelease_QTextBlockGroup );
extern QT_G_FUNC( hbqt_gcRelease_QTextBrowser );
extern QT_G_FUNC( hbqt_gcRelease_QTextBoundaryFinder );
extern QT_G_FUNC( hbqt_gcRelease_QTextCharFormat );
extern QT_G_FUNC( hbqt_gcRelease_QTextCodec );
extern QT_G_FUNC( hbqt_gcRelease_QTextCursor );
extern QT_G_FUNC( hbqt_gcRelease_QTextDecoder );
extern QT_G_FUNC( hbqt_gcRelease_QTextDocument );
extern QT_G_FUNC( hbqt_gcRelease_QTextDocumentFragment );
extern QT_G_FUNC( hbqt_gcRelease_QTextDocumentWriter );
extern QT_G_FUNC( hbqt_gcRelease_QTextEdit );
extern QT_G_FUNC( hbqt_gcRelease_QTextEncoder );
extern QT_G_FUNC( hbqt_gcRelease_QTextFormat );
extern QT_G_FUNC( hbqt_gcRelease_QTextFragment );
extern QT_G_FUNC( hbqt_gcRelease_QTextFrame );
extern QT_G_FUNC( hbqt_gcRelease_QTextFrameFormat );
extern QT_G_FUNC( hbqt_gcRelease_QTextImageFormat );
extern QT_G_FUNC( hbqt_gcRelease_QTextInlineObject );
extern QT_G_FUNC( hbqt_gcRelease_QTextItem );
extern QT_G_FUNC( hbqt_gcRelease_QTextLayout );
extern QT_G_FUNC( hbqt_gcRelease_QTextLength );
extern QT_G_FUNC( hbqt_gcRelease_QTextLine );
extern QT_G_FUNC( hbqt_gcRelease_QTextListFormat );
extern QT_G_FUNC( hbqt_gcRelease_QTextObject );
extern QT_G_FUNC( hbqt_gcRelease_QTextOption );
extern QT_G_FUNC( hbqt_gcRelease_QTextStream );
extern QT_G_FUNC( hbqt_gcRelease_QTextTableFormat );
extern QT_G_FUNC( hbqt_gcRelease_QThread );
extern QT_G_FUNC( hbqt_gcRelease_QTime );
extern QT_G_FUNC( hbqt_gcRelease_QTimeEdit );
extern QT_G_FUNC( hbqt_gcRelease_QTimer );
extern QT_G_FUNC( hbqt_gcRelease_QToolBar );
extern QT_G_FUNC( hbqt_gcRelease_QToolBox );
extern QT_G_FUNC( hbqt_gcRelease_QToolButton );
extern QT_G_FUNC( hbqt_gcRelease_QTransform );
extern QT_G_FUNC( hbqt_gcRelease_QTranslator );
extern QT_G_FUNC( hbqt_gcRelease_QTreeView );
extern QT_G_FUNC( hbqt_gcRelease_QTreeWidget );
extern QT_G_FUNC( hbqt_gcRelease_QTreeWidgetItem );
extern QT_G_FUNC( hbqt_gcRelease_QUiLoader );
extern QT_G_FUNC( hbqt_gcRelease_QUrl );
extern QT_G_FUNC( hbqt_gcRelease_QValidator );
extern QT_G_FUNC( hbqt_gcRelease_QVariant );
extern QT_G_FUNC( hbqt_gcRelease_QVBoxLayout );
extern QT_G_FUNC( hbqt_gcRelease_QWebFrame );
extern QT_G_FUNC( hbqt_gcRelease_QWebHistory );
extern QT_G_FUNC( hbqt_gcRelease_QWebHistoryInterface );
extern QT_G_FUNC( hbqt_gcRelease_QWebHistoryItem );
extern QT_G_FUNC( hbqt_gcRelease_QWebHitTestResult );
extern QT_G_FUNC( hbqt_gcRelease_QWebPage );
extern QT_G_FUNC( hbqt_gcRelease_QWebPluginFactory );
extern QT_G_FUNC( hbqt_gcRelease_QWebSecurityOrigin );
extern QT_G_FUNC( hbqt_gcRelease_QWebSettings );
extern QT_G_FUNC( hbqt_gcRelease_QWebView );
extern QT_G_FUNC( hbqt_gcRelease_QWheelEvent );
extern QT_G_FUNC( hbqt_gcRelease_QWidget );
extern QT_G_FUNC( hbqt_gcRelease_QWidgetAction );
extern QT_G_FUNC( hbqt_gcRelease_QWidgetItem );
extern QT_G_FUNC( hbqt_gcRelease_QWindowsStyle );
extern QT_G_FUNC( hbqt_gcRelease_QWizard );
extern QT_G_FUNC( hbqt_gcRelease_QWizardPage );

extern void * hbqt_gcAllocate_QAbstractButton( void * pObj );
extern void * hbqt_gcAllocate_QAbstractItemDelegate( void * pObj );
extern void * hbqt_gcAllocate_QAbstractItemModel( void * pObj );
extern void * hbqt_gcAllocate_QAbstractItemView( void * pObj );
extern void * hbqt_gcAllocate_QAbstractListModel( void * pObj );
extern void * hbqt_gcAllocate_QAbstractProxyModel( void * pObj );
extern void * hbqt_gcAllocate_QAbstractPrintDialog( void * pObj );
extern void * hbqt_gcAllocate_QAbstractScrollArea( void * pObj );
extern void * hbqt_gcAllocate_QAbstractSlider( void * pObj );
extern void * hbqt_gcAllocate_QAbstractSpinBox( void * pObj );
extern void * hbqt_gcAllocate_QAbstractTableModel( void * pObj );
extern void * hbqt_gcAllocate_QAbstractTextDocumentLayout( void * pObj );
extern void * hbqt_gcAllocate_QAction( void * pObj );
extern void * hbqt_gcAllocate_QActionGroup( void * pObj );
extern void * hbqt_gcAllocate_QApplication( void * pObj );
extern void * hbqt_gcAllocate_QBitArray( void * pObj );
extern void * hbqt_gcAllocate_QBitmap( void * pObj );
extern void * hbqt_gcAllocate_QBoxLayout( void * pObj );
extern void * hbqt_gcAllocate_QBrush( void * pObj );
extern void * hbqt_gcAllocate_QButtonGroup( void * pObj );
extern void * hbqt_gcAllocate_QByteArray( void * pObj );
extern void * hbqt_gcAllocate_QCalendarWidget( void * pObj );
extern void * hbqt_gcAllocate_QCheckBox( void * pObj );
extern void * hbqt_gcAllocate_QClipboard( void * pObj );
extern void * hbqt_gcAllocate_QColor( void * pObj );
extern void * hbqt_gcAllocate_QColorDialog( void * pObj );
extern void * hbqt_gcAllocate_QComboBox( void * pObj );
extern void * hbqt_gcAllocate_QCommandLinkButton( void * pObj );
extern void * hbqt_gcAllocate_QCommonStyle( void * pObj );
extern void * hbqt_gcAllocate_QCompleter( void * pObj );
extern void * hbqt_gcAllocate_QConicalGradient( void * pObj );
extern void * hbqt_gcAllocate_QContextMenuEvent( void * pObj );
extern void * hbqt_gcAllocate_QCoreApplication( void * pObj );
extern void * hbqt_gcAllocate_QCursor( void * pObj );
extern void * hbqt_gcAllocate_QDataStream( void * pObj );
extern void * hbqt_gcAllocate_QDate( void * pObj );
extern void * hbqt_gcAllocate_QDateEdit( void * pObj );
extern void * hbqt_gcAllocate_QDateTime( void * pObj );
extern void * hbqt_gcAllocate_QDateTimeEdit( void * pObj );
extern void * hbqt_gcAllocate_QDesktopWidget( void * pObj );
extern void * hbqt_gcAllocate_QDial( void * pObj );
extern void * hbqt_gcAllocate_QDialog( void * pObj );
extern void * hbqt_gcAllocate_QDir( void * pObj );
extern void * hbqt_gcAllocate_QDirModel( void * pObj );
extern void * hbqt_gcAllocate_QDockWidget( void * pObj );
extern void * hbqt_gcAllocate_QDoubleSpinBox( void * pObj );
extern void * hbqt_gcAllocate_QDropEvent( void * pObj );
extern void * hbqt_gcAllocate_QDragMoveEvent( void * pObj );
extern void * hbqt_gcAllocate_QDragEnterEvent( void * pObj );
extern void * hbqt_gcAllocate_QDragLeaveEvent( void * pObj );
extern void * hbqt_gcAllocate_QErrorMessage( void * pObj );
extern void * hbqt_gcAllocate_QEvent( void * pObj );
extern void * hbqt_gcAllocate_QEventLoop( void * pObj );
extern void * hbqt_gcAllocate_QFile( void * pObj );
extern void * hbqt_gcAllocate_QFileDialog( void * pObj );
extern void * hbqt_gcAllocate_QFileInfo( void * pObj );
extern void * hbqt_gcAllocate_QFileIconProvider( void * pObj );
extern void * hbqt_gcAllocate_QFileSystemModel( void * pObj );
extern void * hbqt_gcAllocate_QFocusEvent( void * pObj );
extern void * hbqt_gcAllocate_QFocusFrame( void * pObj );
extern void * hbqt_gcAllocate_QFont( void * pObj );
extern void * hbqt_gcAllocate_QFontComboBox( void * pObj );
extern void * hbqt_gcAllocate_QFontDatabase( void * pObj );
extern void * hbqt_gcAllocate_QFontDialog( void * pObj );
extern void * hbqt_gcAllocate_QFontInfo( void * pObj );
extern void * hbqt_gcAllocate_QFontMetrics( void * pObj );
extern void * hbqt_gcAllocate_QFontMetricsF( void * pObj );
extern void * hbqt_gcAllocate_QFormLayout( void * pObj );
extern void * hbqt_gcAllocate_QFrame( void * pObj );
extern void * hbqt_gcAllocate_QFtp( void * pObj );
extern void * hbqt_gcAllocate_QGradient( void * pObj );
extern void * hbqt_gcAllocate_QGridLayout( void * pObj );
extern void * hbqt_gcAllocate_QGroupBox( void * pObj );
extern void * hbqt_gcAllocate_QHBoxLayout( void * pObj );
extern void * hbqt_gcAllocate_QHeaderView( void * pObj );
extern void * hbqt_gcAllocate_QHelpEvent( void * pObj );
extern void * hbqt_gcAllocate_QHttp( void * pObj );
extern void * hbqt_gcAllocate_QHttpHeader( void * pObj );
extern void * hbqt_gcAllocate_QHttpRequestHeader( void * pObj );
extern void * hbqt_gcAllocate_QHttpResponseHeader( void * pObj );
extern void * hbqt_gcAllocate_QIcon( void * pObj );
extern void * hbqt_gcAllocate_QInputContext( void * pObj );
extern void * hbqt_gcAllocate_QInputMethodEvent( void * pObj );
extern void * hbqt_gcAllocate_QImage( void * pObj );
extern void * hbqt_gcAllocate_QImageReader( void * pObj );
extern void * hbqt_gcAllocate_QImageWriter( void * pObj );
extern void * hbqt_gcAllocate_QInputDialog( void * pObj );
extern void * hbqt_gcAllocate_QInputEvent( void * pObj );
extern void * hbqt_gcAllocate_QIODevice( void * pObj );
extern void * hbqt_gcAllocate_QItemSelection( void * pObj );
extern void * hbqt_gcAllocate_QItemSelectionModel( void * pObj );
extern void * hbqt_gcAllocate_QKeyEvent( void * pObj );
extern void * hbqt_gcAllocate_QKeySequence( void * pObj );
extern void * hbqt_gcAllocate_QLabel( void * pObj );
extern void * hbqt_gcAllocate_QLatin1Char( void * pObj );
extern void * hbqt_gcAllocate_QLatin1String( void * pObj );
extern void * hbqt_gcAllocate_QLayout( void * pObj );
extern void * hbqt_gcAllocate_QLayoutItem( void * pObj );
extern void * hbqt_gcAllocate_QLCDNumber( void * pObj );
extern void * hbqt_gcAllocate_QLine( void * pObj );
extern void * hbqt_gcAllocate_QLineF( void * pObj );
extern void * hbqt_gcAllocate_QLinearGradient( void * pObj );
extern void * hbqt_gcAllocate_QLineEdit( void * pObj );
extern void * hbqt_gcAllocate_QList( void * pObj );
extern void * hbqt_gcAllocate_QListView( void * pObj );
extern void * hbqt_gcAllocate_QListWidget( void * pObj );
extern void * hbqt_gcAllocate_QListWidgetItem( void * pObj );
extern void * hbqt_gcAllocate_QLocale( void * pObj );
extern void * hbqt_gcAllocate_QMainWindow( void * pObj );
extern void * hbqt_gcAllocate_QMatrix( void * pObj );
extern void * hbqt_gcAllocate_QMdiArea( void * pObj );
extern void * hbqt_gcAllocate_QMdiSubWindow( void * pObj );
extern void * hbqt_gcAllocate_QMenu( void * pObj );
extern void * hbqt_gcAllocate_QMenuBar( void * pObj );
extern void * hbqt_gcAllocate_QMessageBox( void * pObj );
extern void * hbqt_gcAllocate_QMimeData( void * pObj );
extern void * hbqt_gcAllocate_QModelIndex( void * pObj );
extern void * hbqt_gcAllocate_QMouseEvent( void * pObj );
extern void * hbqt_gcAllocate_QMoveEvent( void * pObj );
extern void * hbqt_gcAllocate_QMovie( void * pObj );
extern void * hbqt_gcAllocate_QNetworkRequest( void * pObj );
extern void * hbqt_gcAllocate_QObject( void * pObj );
extern void * hbqt_gcAllocate_QPaintDevice( void * pObj );
extern void * hbqt_gcAllocate_QPainterPath( void * pObj );
extern void * hbqt_gcAllocate_QPageSetupDialog( void * pObj );
extern void * hbqt_gcAllocate_QPainter( void * pObj );
extern void * hbqt_gcAllocate_QPaintEvent( void * pObj );
extern void * hbqt_gcAllocate_QPalette( void * pObj );
extern void * hbqt_gcAllocate_QPen( void * pObj );
extern void * hbqt_gcAllocate_QPicture( void * pObj );
extern void * hbqt_gcAllocate_QPixmap( void * pObj );
extern void * hbqt_gcAllocate_QPlainTextEdit( void * pObj );
extern void * hbqt_gcAllocate_QPoint( void * pObj );
extern void * hbqt_gcAllocate_QPointF( void * pObj );
extern void * hbqt_gcAllocate_QPolygon( void * pObj );
extern void * hbqt_gcAllocate_QPolygonF( void * pObj );
extern void * hbqt_gcAllocate_QPrintDialog( void * pObj );
extern void * hbqt_gcAllocate_QPrintEngine( void * pObj );
extern void * hbqt_gcAllocate_QPrinter( void * pObj );
extern void * hbqt_gcAllocate_QPrintPreviewDialog( void * pObj );
extern void * hbqt_gcAllocate_QProcess( void * pObj );
extern void * hbqt_gcAllocate_QProgressBar( void * pObj );
extern void * hbqt_gcAllocate_QProgressDialog( void * pObj );
extern void * hbqt_gcAllocate_QPushButton( void * pObj );
extern void * hbqt_gcAllocate_QRadialGradient( void * pObj );
extern void * hbqt_gcAllocate_QRadioButton( void * pObj );
extern void * hbqt_gcAllocate_QRect( void * pObj );
extern void * hbqt_gcAllocate_QRectF( void * pObj );
extern void * hbqt_gcAllocate_QRegion( void * pObj );
extern void * hbqt_gcAllocate_QRegExp( void * pObj );
extern void * hbqt_gcAllocate_QResizeEvent( void * pObj );
extern void * hbqt_gcAllocate_QResource( void * pObj );
extern void * hbqt_gcAllocate_QScrollArea( void * pObj );
extern void * hbqt_gcAllocate_QScrollBar( void * pObj );
extern void * hbqt_gcAllocate_QSessionManager( void * pObj );
extern void * hbqt_gcAllocate_QSettings( void * pObj );
extern void * hbqt_gcAllocate_QSignalMapper( void * pObj );
extern void * hbqt_gcAllocate_QSize( void * pObj );
extern void * hbqt_gcAllocate_QSizeF( void * pObj );
extern void * hbqt_gcAllocate_QSizeGrip( void * pObj );
extern void * hbqt_gcAllocate_QSizePolicy( void * pObj );
extern void * hbqt_gcAllocate_QSlider( void * pObj );
extern void * hbqt_gcAllocate_QSound( void * pObj );
extern void * hbqt_gcAllocate_QSpacerItem( void * pObj );
extern void * hbqt_gcAllocate_QSpinBox( void * pObj );
extern void * hbqt_gcAllocate_QSplashScreen( void * pObj );
extern void * hbqt_gcAllocate_QSplitter( void * pObj );
extern void * hbqt_gcAllocate_QStandardItem( void * pObj );
extern void * hbqt_gcAllocate_QStandardItemModel( void * pObj );
extern void * hbqt_gcAllocate_QStatusBar( void * pObj );
extern void * hbqt_gcAllocate_QStringList( void * pObj );
extern void * hbqt_gcAllocate_QStringListModel( void * pObj );
extern void * hbqt_gcAllocate_QStyle( void * pObj );
extern void * hbqt_gcAllocate_QStyledItemDelegate( void * pObj );
extern void * hbqt_gcAllocate_QStyleFactory( void * pObj );
extern void * hbqt_gcAllocate_QStyleHintReturn( void * pObj );
extern void * hbqt_gcAllocate_QStyleHintReturnMask( void * pObj );
extern void * hbqt_gcAllocate_QStyleHintReturnVariant( void * pObj );
extern void * hbqt_gcAllocate_QStyleOption( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionButton( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionComboBox( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionComplex( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionDockWidget( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionFocusRect( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionFrame( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionGroupBox( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionHeader( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionMenuItem( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionProgressBar( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionSizeGrip( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionSlider( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionSpinBox( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionTab( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionTabBarBase( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionTabWidgetFrame( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionTitleBar( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionToolBar( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionToolBox( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionToolButton( void * pObj );
extern void * hbqt_gcAllocate_QStyleOptionViewItem( void * pObj );
extern void * hbqt_gcAllocate_QStylePainter( void * pObj );
extern void * hbqt_gcAllocate_QSyntaxHighlighter( void * pObj );
extern void * hbqt_gcAllocate_QSystemTrayIcon( void * pObj );
extern void * hbqt_gcAllocate_QTabBar( void * pObj );
extern void * hbqt_gcAllocate_QTableView( void * pObj );
extern void * hbqt_gcAllocate_QTableWidget( void * pObj );
extern void * hbqt_gcAllocate_QTableWidgetItem( void * pObj );
extern void * hbqt_gcAllocate_QTabWidget( void * pObj );
extern void * hbqt_gcAllocate_QTableWidgetSelectionRange( void * pObj );
extern void * hbqt_gcAllocate_QTextBlock( void * pObj );
extern void * hbqt_gcAllocate_QTextBlockFormat( void * pObj );
extern void * hbqt_gcAllocate_QTextBlockGroup( void * pObj );
extern void * hbqt_gcAllocate_QTextBrowser( void * pObj );
extern void * hbqt_gcAllocate_QTextBoundaryFinder( void * pObj );
extern void * hbqt_gcAllocate_QTextCharFormat( void * pObj );
extern void * hbqt_gcAllocate_QTextCodec( void * pObj );
extern void * hbqt_gcAllocate_QTextCursor( void * pObj );
extern void * hbqt_gcAllocate_QTextDecoder( void * pObj );
extern void * hbqt_gcAllocate_QTextDocument( void * pObj );
extern void * hbqt_gcAllocate_QTextDocumentFragment( void * pObj );
extern void * hbqt_gcAllocate_QTextDocumentWriter( void * pObj );
extern void * hbqt_gcAllocate_QTextEdit( void * pObj );
extern void * hbqt_gcAllocate_QTextEncoder( void * pObj );
extern void * hbqt_gcAllocate_QTextFormat( void * pObj );
extern void * hbqt_gcAllocate_QTextFragment( void * pObj );
extern void * hbqt_gcAllocate_QTextFrame( void * pObj );
extern void * hbqt_gcAllocate_QTextFrameFormat( void * pObj );
extern void * hbqt_gcAllocate_QTextImageFormat( void * pObj );
extern void * hbqt_gcAllocate_QTextInlineObject( void * pObj );
extern void * hbqt_gcAllocate_QTextItem( void * pObj );
extern void * hbqt_gcAllocate_QTextLayout( void * pObj );
extern void * hbqt_gcAllocate_QTextLength( void * pObj );
extern void * hbqt_gcAllocate_QTextLine( void * pObj );
extern void * hbqt_gcAllocate_QTextListFormat( void * pObj );
extern void * hbqt_gcAllocate_QTextObject( void * pObj );
extern void * hbqt_gcAllocate_QTextOption( void * pObj );
extern void * hbqt_gcAllocate_QTextStream( void * pObj );
extern void * hbqt_gcAllocate_QTextTableFormat( void * pObj );
extern void * hbqt_gcAllocate_QThread( void * pObj );
extern void * hbqt_gcAllocate_QTime( void * pObj );
extern void * hbqt_gcAllocate_QTimeEdit( void * pObj );
extern void * hbqt_gcAllocate_QTimer( void * pObj );
extern void * hbqt_gcAllocate_QToolBar( void * pObj );
extern void * hbqt_gcAllocate_QToolBox( void * pObj );
extern void * hbqt_gcAllocate_QToolButton( void * pObj );
extern void * hbqt_gcAllocate_QTransform( void * pObj );
extern void * hbqt_gcAllocate_QTranslator( void * pObj );
extern void * hbqt_gcAllocate_QTreeView( void * pObj );
extern void * hbqt_gcAllocate_QTreeWidget( void * pObj );
extern void * hbqt_gcAllocate_QTreeWidgetItem( void * pObj );
extern void * hbqt_gcAllocate_QUiLoader( void * pObj );
extern void * hbqt_gcAllocate_QUrl( void * pObj );
extern void * hbqt_gcAllocate_QValidator( void * pObj );
extern void * hbqt_gcAllocate_QVariant( void * pObj );
extern void * hbqt_gcAllocate_QVBoxLayout( void * pObj );
extern void * hbqt_gcAllocate_QWebFrame( void * pObj );
extern void * hbqt_gcAllocate_QWebHistory( void * pObj );
extern void * hbqt_gcAllocate_QWebHistoryInterface( void * pObj );
extern void * hbqt_gcAllocate_QWebHistoryItem( void * pObj );
extern void * hbqt_gcAllocate_QWebHitTestResult( void * pObj );
extern void * hbqt_gcAllocate_QWebPage( void * pObj );
extern void * hbqt_gcAllocate_QWebPluginFactory( void * pObj );
extern void * hbqt_gcAllocate_QWebSecurityOrigin( void * pObj );
extern void * hbqt_gcAllocate_QWebSettings( void * pObj );
extern void * hbqt_gcAllocate_QWebView( void * pObj );
extern void * hbqt_gcAllocate_QWheelEvent( void * pObj );
extern void * hbqt_gcAllocate_QWidget( void * pObj );
extern void * hbqt_gcAllocate_QWidgetAction( void * pObj );
extern void * hbqt_gcAllocate_QWidgetItem( void * pObj );
extern void * hbqt_gcAllocate_QWindowsStyle( void * pObj );
extern void * hbqt_gcAllocate_QWizard( void * pObj );
extern void * hbqt_gcAllocate_QWizardPage( void * pObj );

