ROOT := ../../

C_SOURCES := \

C_MAIN := harbour.c

RC_SOURCES := \
   $(TOP)$(ROOT)package/harbour.rc

LIBS := \
   hbcplr \
   hbpp \
   hbnortl \
   hbcommon \

include $(TOP)$(ROOT)config/bin.mk
