#
# $Id$
#

ROOT := ../../

LIBNAME := rddsql

C_SOURCES := \
   sqlbase.c \
   sqlmix.c \

PRG_HEADERS := \
   hbrddsql.ch \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
