#
# $Id$
#

ROOT := ../../

LIBNAME := rddsql

C_SOURCES := \
   sqlbase.c \
   sqlmix.c \

PRG_HEADERS := \
   hbrddsql.ch \

DIRS := \
   sddmy \
   sddpg \
   sddfb \
   sddoci \
   sddodbc \
   sddsqlt3 \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
include $(TOP)$(ROOT)config/dir.mk
