#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	gtwvg.c \
	wvtcore.c \
	wvtutils.c \

C_HEADERS=\
	gtwvg.h \

PRG_SOURCES=\
	wvtclass.prg \
	wvtpaint.prg \

PRG_HEADERS=\
	wvtwin.ch \

LIBNAME=hbgtwvg

include $(TOP)$(ROOT)config/lib.cf
