#
# $Id$
#

ROOT = ../../

C_SOURCES=\
        arrays.c \
        classes.c \
        codebloc.c \
        console.c \
        copyfile.c \
        dates.c \
        descend.c \
        dir.c \
	do.c \
        environ.c \
        errorapi.c \
        extend.c \
        filesys.c \
        fm.c \
        gtapi.c \
        hardcr.c \
        inkey.c \
        itemapi.c \
        math.c \
        memvars.c \
        mtran.c \
        set.c \
        setcolor.c \
        strings.c \
        transfrm.c \
        \
        gtxxx.c \
        msgxxx.c \

PRG_SOURCES=\
        alert.prg \
        asort.prg \
        devoutp.prg \
        error.prg \
        errorsys.prg \
        objfunc.prg \
        setkey.prg \
        tclass.prg \

LIB=rtl

include $(TOP)$(ROOT)config/lib.cf
