#
# $Id$
#

ROOT = ../../

C_SOURCES=\
        arrays.c \
        binnum.c \
        classes.c \
        codebloc.c \
        console.c \
        copyfile.c \
        dates.c \
        descend.c \
        dir.c \
	do.c \
        environ.c \
        errorapi.c \
        extend.c \
        filesys.c \
        fm.c \
        gtapi.c \
        hardcr.c \
        inkey.c \
        isprint.c \
        itemapi.c \
        langapi.c \
        math.c \
        memofile.c \
        memoline.c \
        memvars.c \
        mlcount.c \
        mouseapi.c \
        mtran.c \
        natmsg.c \
        net.c \
        oemansi.c \
        oldbox.c \
        oldclear.c \
        samples.c \
        set.c \
        setcolor.c \
        soundex.c \
        strings.c \
        tone.c \
        trace.c \
        transfrm.c \
        \
        gtxxx.c \
        mousexxx.c \
        msgxxx.c \

PRG_SOURCES=\
        achoice.prg \
        adir.prg \
        alert.prg \
        asort.prg \
        browdb.prg \
        browse.prg \
        dbedit.prg \
        devoutp.prg \
        dircmd.prg \
        dummy.prg \
        errorsys.prg \
        fieldbl.prg \
        harbinit.prg \
        input.prg \
	memvarbl.prg \
	menuto.prg \
        objfunc.prg \
        readkey.prg \
        readvar.prg \
        setfunc.prg \
        setkey.prg \
        setta.prg \
        tclass.prg \
        tbcolumn.prg \
        tbrowse.prg \
        terror.prg \
        text.prg \
        tget.prg \
        tgetlist.prg \
        wait.prg \
        xsavescr.prg \

LIBNAME=rtl

include $(TOP)$(ROOT)config/lib.cf
