#
# $Id$
#

ifeq ($(HB_MAIN),)
 HB_MAIN = std
endif

ROOT = ../../

PRG_SOURCES=\
        rt_array.prg \
        rt_date.prg  \
        rt_file.prg  \
        rt_hvm.prg   \
        rt_main.prg  \
        rt_math.prg  \
        rt_misc.prg  \
        rt_str.prg   \
        rt_trans.prg \

PRG_MAIN=rt_main.prg

LIBS=\
        tools \
        debug \
        rtl \
        rdd \
        vm \
        rdd \
        rtl \
	macro \
        pp \
        runner \
        common \

include $(TOP)$(ROOT)config/bin.cf
