.TH HBDOC 1

.SH NAME
hbdoc \- Harbour Project Doc Extractor

.SH SYNOPSIS
\fBhbdoc\fP \fB[options]\fP \fB<linkname>\fP \fB[<ifile>]\fP

.SH DESCRIPTION
\fBhbdoc\fP is the Harbour Project doc extractor.

.SH OPTIONS
.IP "\fB-txt\fP" 10
Create an ASCII file instead of a Norton Guide
.IP "\fB-con\fP" 10
Create an ASCII file without formfeeds
.IP "\fB-hpc\fP" 10
Helpc source file
.IP "\fB-ngi\fP" 10
Adds the -NG switch to EHC command for compile for DOS/Windows/Linux.
.IP "\fB-rtf\fP" 10
Winhelp source code for Windows
.IP "\fB-os2\fP" 10
OS/2 help source code For OS/2
.IP "\fB-htm\fP" 10
Generate HTML output
.IP "\fB-chm\fP" 10
Generate HTML source files for Windows .chm Help files
.IP "\fB-pdf\fP" 10
Generate an Adobe Portable Document (.pdf)
.IP "\fB-trf\fP" 10
Generate Linux TROFF code
.IP "\fB-doc\fP" 10
Create continuous ASCII file w/o author information

.SH AUTHOR

Author of hbdoc: The Harbour Project (http://www.harbour-project.org)

This manual page was written by Luis Mayoral <mayoral@linuxadicto.org>,
for the Debian GNU/Linux system (but may be used by others).
