#
# $Id$
#

ROOT = ../../../

PRG_SOURCES=\
	DBU.PRG \
	DBUCOPY.PRG \
	DBUEDIT.PRG \
	DBUHELP.PRG \
	DBUINDX.PRG \
	DBUNET.PRG \
	DBUSTRU.PRG \
	DBUUTIL.PRG \
	DBUVIEW.PRG \
	
PRG_MAIN=DBU.PRG

LIBS=\
	debug \
	vm \
	rtl \
	lang \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	dbfntx \
	dbfcdx \
	dbffpt \
	hbsix \
	common \

include $(TOP)$(ROOT)config/bin.cf
