#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	asciisum.c \
	ascpos.c \
	atdiff.c \
	chareven.c \
	charmix.c \
	charodd.c \
	chrcount.c \
	chrfirst.c \
	chrtotal.c \
	strasint.c \
	strcount.c \
	strcspn.c \
	strdiff.c \
	strexpan.c \
	strleft.c \
	strpbrk.c \
	strright.c \

PRG_SOURCES=\

LIBNAME=libgt

include $(TOP)$(ROOT)config/lib.cf
