#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	date.c \
	dbf.c \
	environ.c \
	gauge.c \
	num.c \
	stack.c \
	status.c \
	time.c \

PRG_SOURCES=\

PRG_HEADERS=\
	time87.ch \

LIBNAME=samples

include $(TOP)$(ROOT)config/lib.cf
