#
# $Id$
#


ROOT = ../../

C_SOURCES = \
          zipfile.c \
          zipfile2.c \
          zlibapi1.c \
          tzipfile.c \
          strcomp.c \
          adler32.c \
          compress.c \
          crc32.c \
          deflate.c \
          gzio.c \
          infblock.c \
          infcodes.c \
          inffast.c \
          inflate.c \
          inftrees.c \
          infutil.c \
          trees.c \
          uncompr.c \
          zutil.c \


LIBNAME=zlib

include $(TOP)$(ROOT)config/lib.cf

