#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
        editorhi.prg \
	
C_SOURCES=\
	editorlo.c \

PRG_MAIN=pe.prg

LIBS=\
        runner \
	tools \
        debug \
	rdd \
	vm \
	rdd \
	rtl \
	pp \
	common \
	macro \

include $(TOP)$(ROOT)config/bin.cf
