#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
        editorhi.prg \
	
C_SOURCES=\
	editorlo.c \

PRG_MAIN=pe.prg

LIBS=\
        tools \
        debug \
        vm \
        rtl \
        rdd \
        rtl \
        vm \
	macro \
        pp \
        common \

include $(TOP)$(ROOT)config/bin.cf
