#
# $Id$
#

ifeq ($(HB_MAIN),)
   HB_MAIN := std
endif

ROOT := ../../

PRG_SOURCES := \
   hbmk2.prg \

PRG_MAIN := hbmk2.prg

LIBS := \
   hbdebug \
   hbvmmt \
   hbrtl \
   hblang \
   hbcpage \
   hbnulrdd \
   hbrtl \
   hbvmmt \
   hbmacro \
   hbcplr \
   hbpp \
   hbcommon \

include $(TOP)$(ROOT)config/bin.cf
