#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	RLBACK.PRG \
	RLDIALG.PRG \
	RLFRONT.PRG \

PRG_MAIN=RLFRONT.PRG

LIBS=\
	hbdebug \
	hbvm \
	hbrtl \
	hblang \
	hbrdd \
	hbrtl \
	hbvm \
	hbmacro \
	hbpp \
	rddntx \
	rddcdx \
	rddfpt \
	hbsix \
	hbcommon \

include $(TOP)$(ROOT)config/bin.cf
