/*
 * $Id$
 *
 * Errors generated by Harbour compiler
*/
#define ERR_OUTSIDE             1
#define ERR_FUNC_DUPL           2
#define ERR_VAR_DUPL            3
#define ERR_FOLLOWS_EXEC        4
#define ERR_OUTER_VAR           5
#define ERR_NUMERIC_FORMAT      6
#define ERR_STRING_TERMINATOR   7
#define ERR_FUNC_RESERVED       8
#define ERR_ILLEGAL_INIT        9
#define ERR_CANT_OPEN_INCLUDE   10
#define ERR_ENDIF               11
#define ERR_ENDDO               12
#define ERR_ENDCASE             13
#define ERR_NEXTFOR             14
#define ERR_UNMATCHED_ELSE      15
#define ERR_UNMATCHED_ELSEIF    16
#define ERR_SYNTAX              17
#define ERR_UNCLOSED_STRU       18
#define ERR_UNMATCHED_EXIT      19

void GenError( int, char*, char * );      /* generic parsing error management function */
