#
# $Id$
#

ROOT = ../

C_HEADERS=\
	box.h \
	compiler.h \
	ctoharb.h \
	dates.h \
	errorapi.h \
	extend.h \
	filesys.h \
	gtapi.h \
	hbdefs.h \
	hberrors.h \
	hbpp.h \
	hbsetup.h \
	hbver.h \
	init.h \
	initsymb.h \
	inkey.h \
	itemapi.h \
	pcode.h \
	run_exp.h \
	set.h \

PRG_HEADERS=\
	box.ch \
	classes.ch \
	color.ch \
	error.ch \
	fileio.ch \
	inkey.ch \
	rddsys.ch \
	set.ch \
	setcurs.ch \

API_HEADERS=\
	error.api \
	extend.api \
	filesys.api \
	fm.api \
	gt.api \
	item.api \
	rdd.api \

include $(TOP)$(ROOT)config/header.cf
