#
# $Id$
#

ROOT = ../

C_HEADERS=\
	compiler.h \
	ctoharb.h \
	dates.h \
	extend.h \
	filesys.h \
	gtapi.h \
	harbclip.h \
	hberrors.h \
	hbsetup.h \
	init.h \
	itemapi.h \
	pcode.h \
	set.h \
	types.h \
	version.h \

PRG_HEADERS=\
	cgi.ch \
	error.ch \
	fileio.ch \
	inkey.ch \
	set.ch \
	setcurs.ch \
	test.ch \

API_HEADERS=\
	error.api \
	filesys.api \

include $(TOP)$(ROOT)config/header.cf
