#
# $Id$
#

ROOT = ../

C_HEADERS=\
        box.h        \
        clipdefs.h   \
        compiler.h   \
        ctoharb.h    \
        dates.h      \
        errorapi.h   \
        extend.h     \
        filesys.h    \
        gtapi.h      \
        hbdefs.h     \
        hberrors.h   \
        hbpp.h       \
        hbsetup.h    \
        hbver.h      \
        init.h       \
        initsymc.h   \
        initsymd.h   \
        inkey.h      \
        itemapi.h    \
        langapi.h    \
        pcode.h      \
        rddapi.h     \
        run_exp.h    \
        set.h        \

PRG_HEADERS=\
        achoice.ch   \
        assert.ch    \
        box.ch       \
        classes.ch   \
        color.ch     \
        common.ch    \
        dbedit.ch    \
        dbstruct.ch  \
        directry.ch  \
        error.ch     \
        fileio.ch    \
        getexit.ch   \
        inkey.ch     \
        memoedit.ch  \
        rddsys.ch    \
        set.ch       \
        setcurs.ch   \
        simpleio.ch  \

API_HEADERS=\
        caundoc.api  \
        error.api    \
        extend.api   \
        filesys.api  \
        fm.api       \
        gt.api       \
        item.api     \
        rdd.api      \
        vm.api       \

include $(TOP)$(ROOT)config/header.cf
