#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	DBU.PRG \
	DBUCOPY.PRG \
	DBUEDIT.PRG \
	DBUHELP.PRG \
	DBUINDX.PRG \
	DBUNET.PRG \
	DBUSTRU.PRG \
	DBUUTIL.PRG \
	DBUVIEW.PRG \

PRG_MAIN=DBU.PRG

LIBS=\
	hbdebug \
	hbvm \
	hbrtl \
	hblang \
	hbrdd \
	hbrtl \
	hbvm \
	hbmacro \
	hbpp \
	rddntx \
	rddcdx \
	rddfpt \
	hbsix \
	hbcommon \

include $(TOP)$(ROOT)config/bin.cf
