#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	hscript.prg \

PRG_MAIN=hscript.prg

LIBS=\
	hbdebug \
	hbvm \
	hbrtl \
	hblang \
	hbrdd \
	hbrtl \
	hbvm \
	hbmacro \
	hbpp \
	rddntx \
	rddcdx \
	rddfpt \
	hbsix \
	hbcommon \

include $(TOP)$(ROOT)config/bin.cf
