.TH HBPP 1

.SH NAME
hbpp \- Harbour Preprocessor

.SH SYNOPSIS
.B hbpp
.RI \fR\fI<file\fP[\fR\fI.prg\fP]\fR\fI>\fP
[
.I options
]

.SH DESCRIPTION
\fBhbpp\fP is fully functional standalone Harbour preprocessor
which can be used to preprocess any files but also to generate
C source code with preprocesor rules defined in given files.

.SH OPTIONS
.IP "\fB\-d\fR\fI<id>\fP[\fB=\fR\fI<val>\fP]" 16
#define \fR\fI<id>\fP
.IP "\fB-e\fP[\fR\fI<func>\fP]" 16
use \fR\fI<func>\fP as entry function in generated .c PP rules
.IP "\fB-i\fR\fI<path>\fP" 16
add #include file search path
.IP "\fB-u\fP[\fR\fI<file>\fP]" 16
use command def set in \fR\fI<file>\fP (or none)
.IP "\fB-c\fP[\fR\fI<file>\fP]" 16
look for ChangeLog file to extract version information
.IP "\fB-o\fR\fI<file>\fP" 16
creates .c file with PP rules
.IP "\fB-v\fR\fI<file>\fP" 16
creates .h file with version information
.IP "\fB-w\fP" 16
write preprocessed (.ppo) file
.IP "\fB-q\fP[\fB012\fP]" 16
disable information messages
.PP
If neither -o nor -v is specified then -w is default action.

.SH "ENVIRONMENT VARIABLES"
.IP "\fBINCLUDE\fR"
The value of \fB\s-1INCLUDE\s0\fR is a colon-separated list of
directories, much like shell's \fB\s-1PATH\s0\fR. It's used by
\fBhbpp\fR as default search paths for included files.

.SH AUTHOR
Przemyslaw Czerpak, The Harbour Project (http://harbour-project.org)
