#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	tprinter.c \
	w32_ole.c \
	w32_prn.c \
	w32_regc.c \

PRG_SOURCES=\
	w32_tole.prg \
	w32_tprn.prg \
	w32_reg.prg \

PRG_HEADERS = \
	hbw32.ch \

LIBNAME=hbw32

include $(TOP)$(ROOT)config/lib.cf
