/* This temp source file was generated by hbmk2 tool. (gtnap/cmake) */
/* We use it as a resources for IDE-Debugging example applications */
#include "hbapi.h"

#define stdin (__acrt_iob_func(0))
#define stdout (__acrt_iob_func(1))
#define stderr (__acrt_iob_func(2))
FILE _iob[3];

FILE *__cdecl __iob_func(void) {
  _iob[0] = *stdin;
  _iob[1] = *stdout;
  _iob[2] = *stderr;
  return _iob;
}

HB_FUNC_EXTERN(HB_GT_NAP);
HB_FUNC_EXTERN(HB_GT_WIN);

void _hb_lnk_ForceLink_hbmk(void) {
  HB_FUNC_EXEC(HB_GT_NAP);
  HB_FUNC_EXEC(HB_GT_WIN);
}
