/*
 * $Id$
 */

/* -------------------------------------------------------------------- */
/* WARNING: Automatically generated source file. DO NOT EDIT!           */
/*          Instead, edit corresponding .qth file,                      */
/*          or the generator tool itself, and run regenarate.           */
/* -------------------------------------------------------------------- */

#include "../hbqt.h"

extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_HBQMainWindow );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_HBQPlainTextEdit );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_HBQSyntaxHighlighter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_HBQTableView );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_HBQTextBlockUserData );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractButton );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractItemDelegate );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractItemView );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractPrintDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractProxyModel );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractScrollArea );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractSlider );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractSpinBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAbstractTextDocumentLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QAction );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QActionGroup );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QApplication );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QBitmap );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QBoxLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QBrush );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QButtonGroup );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QCalendarWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QCheckBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QClipboard );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QColor );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QColorDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QComboBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QCommandLinkButton );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QCommonStyle );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QCompleter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QConicalGradient );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QContextMenuEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QCursor );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDateEdit );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDateTimeEdit );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDesktopWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDial );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDirModel );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDockWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDoubleSpinBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDragEnterEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDragLeaveEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDragMoveEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QDropEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QErrorMessage );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFileDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFileIconProvider );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFileSystemModel );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFocusEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFocusFrame );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFont );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFontComboBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFontDatabase );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFontDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFontInfo );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFontMetrics );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFontMetricsF );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFormLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QFrame );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QGradient );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QGridLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QGroupBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QHBoxLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QHeaderView );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QHelpEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QHideEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QIcon );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QImage );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QImageReader );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QImageWriter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QInputDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QInputEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QInputMethodEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QItemDelegate );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QItemEditorCreatorBase );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QItemEditorFactory );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QItemSelection );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QItemSelectionModel );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QKeyEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QKeySequence );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QLabel );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QLayoutItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QLCDNumber );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QLinearGradient );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QLineEdit );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QListView );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QListWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QListWidgetItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMainWindow );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMatrix );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMdiArea );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMdiSubWindow );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMenu );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMenuBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMessageBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMouseEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMoveEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QMovie );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPageSetupDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPaintDevice );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPaintEngine );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPainter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPainterPath );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPaintEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPalette );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPen );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPicture );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPixmap );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPlainTextDocumentLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPlainTextEdit );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPolygon );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPolygonF );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPrintDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPrintEngine );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPrinter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPrintPreviewDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QProgressBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QProgressDialog );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QPushButton );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QRadialGradient );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QRadioButton );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QRegion );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QResizeEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QScrollArea );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QScrollBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSessionManager );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QShowEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSizeGrip );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSizePolicy );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSlider );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSound );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSpacerItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSpinBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSplashScreen );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSplitter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStackedWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStandardItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStandardItemModel );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStatusBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStringListModel );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyle );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyledItemDelegate );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleFactory );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleHintReturn );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleHintReturnMask );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleHintReturnVariant );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOption );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionButton );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionComboBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionComplex );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionDockWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionFocusRect );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionFrame );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionGroupBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionHeader );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionMenuItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionProgressBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionSizeGrip );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionSlider );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionSpinBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionTab );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionTabBarBase );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionTabWidgetFrame );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionTitleBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionToolBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionToolBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionToolButton );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStyleOptionViewItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QStylePainter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSyntaxHighlighter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QSystemTrayIcon );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTabBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTableView );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTableWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTableWidgetItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTableWidgetSelectionRange );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTabWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextBlock );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextBlockFormat );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextBlockGroup );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextBrowser );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextCharFormat );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextCursor );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextDocument );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextDocumentFragment );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextDocumentWriter );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextEdit );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextFormat );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextFragment );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextFrame );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextFrameFormat );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextImageFormat );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextInlineObject );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextLength );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextLine );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextList );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextListFormat );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextObject );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextOption );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTextTableFormat );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTimeEdit );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QToolBar );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QToolBox );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QToolButton );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTransform );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTreeView );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTreeWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QTreeWidgetItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QValidator );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QVBoxLayout );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QWheelEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QWidget );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QWidgetAction );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QWidgetItem );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QWindowsStyle );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QWindowStateChangeEvent );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QWizard );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QWizardPage );
extern HB_EXPORT QT_G_FUNC( hbqt_gcRelease_QUiLoader );

extern HB_EXPORT void * hbqt_gcAllocate_HBQMainWindow( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_HBQPlainTextEdit( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_HBQSyntaxHighlighter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_HBQTableView( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_HBQTextBlockUserData( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractButton( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractItemDelegate( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractItemView( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractPrintDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractProxyModel( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractScrollArea( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractSlider( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractSpinBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAbstractTextDocumentLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QAction( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QActionGroup( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QApplication( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QBitmap( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QBoxLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QBrush( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QButtonGroup( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QCalendarWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QCheckBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QClipboard( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QColor( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QColorDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QComboBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QCommandLinkButton( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QCommonStyle( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QCompleter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QConicalGradient( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QContextMenuEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QCursor( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDateEdit( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDateTimeEdit( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDesktopWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDial( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDirModel( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDockWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDoubleSpinBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDragEnterEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDragLeaveEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDragMoveEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QDropEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QErrorMessage( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFileDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFileIconProvider( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFileSystemModel( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFocusEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFocusFrame( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFont( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFontComboBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFontDatabase( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFontDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFontInfo( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFontMetrics( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFontMetricsF( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFormLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QFrame( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QGradient( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QGridLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QGroupBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QHBoxLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QHeaderView( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QHelpEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QHideEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QIcon( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QImage( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QImageReader( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QImageWriter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QInputDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QInputEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QInputMethodEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QItemDelegate( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QItemEditorCreatorBase( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QItemEditorFactory( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QItemSelection( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QItemSelectionModel( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QKeyEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QKeySequence( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QLabel( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QLayoutItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QLCDNumber( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QLinearGradient( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QLineEdit( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QListView( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QListWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QListWidgetItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMainWindow( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMatrix( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMdiArea( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMdiSubWindow( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMenu( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMenuBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMessageBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMouseEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMoveEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QMovie( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPageSetupDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPaintDevice( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPaintEngine( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPainter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPainterPath( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPaintEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPalette( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPen( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPicture( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPixmap( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPlainTextDocumentLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPlainTextEdit( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPolygon( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPolygonF( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPrintDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPrintEngine( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPrinter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPrintPreviewDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QProgressBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QProgressDialog( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QPushButton( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QRadialGradient( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QRadioButton( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QRegion( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QResizeEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QScrollArea( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QScrollBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSessionManager( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QShowEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSizeGrip( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSizePolicy( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSlider( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSound( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSpacerItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSpinBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSplashScreen( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSplitter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStackedWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStandardItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStandardItemModel( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStatusBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStringListModel( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyle( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyledItemDelegate( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleFactory( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleHintReturn( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleHintReturnMask( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleHintReturnVariant( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOption( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionButton( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionComboBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionComplex( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionDockWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionFocusRect( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionFrame( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionGroupBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionHeader( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionMenuItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionProgressBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionSizeGrip( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionSlider( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionSpinBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionTab( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionTabBarBase( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionTabWidgetFrame( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionTitleBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionToolBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionToolBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionToolButton( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStyleOptionViewItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QStylePainter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSyntaxHighlighter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QSystemTrayIcon( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTabBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTableView( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTableWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTableWidgetItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTableWidgetSelectionRange( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTabWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextBlock( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextBlockFormat( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextBlockGroup( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextBrowser( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextCharFormat( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextCursor( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextDocument( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextDocumentFragment( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextDocumentWriter( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextEdit( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextFormat( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextFragment( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextFrame( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextFrameFormat( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextImageFormat( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextInlineObject( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextLength( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextLine( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextList( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextListFormat( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextObject( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextOption( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTextTableFormat( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTimeEdit( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QToolBar( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QToolBox( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QToolButton( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTransform( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTreeView( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTreeWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QTreeWidgetItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QValidator( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QVBoxLayout( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QWheelEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QWidget( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QWidgetAction( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QWidgetItem( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QWindowsStyle( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QWindowStateChangeEvent( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QWizard( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QWizardPage( void * pObj, bool bNew );
extern HB_EXPORT void * hbqt_gcAllocate_QUiLoader( void * pObj, bool bNew );

