#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	dbgentry.c   \

PRG_SOURCES=\
	dbgmenu.prg  \
	dbghelp.prg  \
	dbgtmenu.prg \
	dbgtmitm.prg \
	dbgtwin.prg  \
	debugger.prg \
	dbgtarr.prg  \
	dbgthsh.prg  \
	dbgtobj.prg  \
	tbrwtext.prg \
	dbgwa.prg    \
	dbgbrwsr.prg \

LIBNAME=debug

include $(TOP)$(ROOT)config/lib.cf
