#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
        dbgmenu.prg \
        dbgtmenu.prg \
        dbgtwin.prg \
        debugger.prg \
        tbrwtext.prg \

LIBNAME=debug

include $(TOP)$(ROOT)config/lib.cf
