#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	dbgmenu.prg \
	dbgtmenu.prg \
	dbgtmitm.prg \
	dbgtwin.prg \
	debugger.prg \
   dbgtarr.prg \
   dbgtobj.prg \
	tbrwtext.prg \
	dbgwa.prg

LIBNAME=debug

include $(TOP)$(ROOT)config/lib.cf
