.TH HBTEST 1

.SH NAME
hbtest \- Harbour Regression Test Suite

.SH SYNOPSIS
\fBhbtest\fP \fB[options]\fP

.SH DESCRIPTION
\fBhbtest\fP is the Harbour regression test suite.

.SH OPTIONS
.IP "\fB-h, -?\fP" 10
Display help
.IP "\fB-all\fP" 10
Display all tests, not only the failures
.IP "\fB-skip:<list>\fP" 10
Skip the listed test numbers


.SH AUTHOR

Author of hbtest: The Harbour team (http://harbour-project.org)

This manual page was written by Luis Mayoral <mayoral@linuxadicto.org>,
for the Debian GNU/Linux system (but may be used by others).
