#
# $Id$
#

ifeq ($(HB_MAIN),)
 HB_MAIN = std
endif

ROOT = ../../

PRG_SOURCES=\
	pretest.prg \

PRG_MAIN=pretest.prg

LIBS=\
	hbdebug \
	hbvm \
	hbrtl \
	hblang \
	hbrdd \
	hbrtl \
	hbvm \
	hbmacro \
	hbpp \
	hbcommon \

include $(TOP)$(ROOT)config/bin.cf
