#
# $Id$
#

ROOT = ../../../../

PRG_SOURCES=\
	arrayrdd.prg \
	logrdd.prg \
	fcomma.prg \
	hscdx.prg \
	rlcdx.prg \
	dbtcdx.prg \
	fptcdx.prg \
	smtcdx.prg \
	vpfcdx.prg \


LIBNAME=usrrdds

include $(TOP)$(ROOT)config/lib.cf
