#
# $Id$
#

ROOT := ../../../../

PRG_SOURCES := \
   arrayrdd.prg \
   logrdd.prg \
   hscdx.prg \
   rlcdx.prg \
   dbtcdx.prg \
   fptcdx.prg \
   smtcdx.prg \
   vfpcdx.prg \

LIBNAME := hbuddall

include $(TOP)$(ROOT)config/lib.mk
