#
# $Id$
#

ifeq ($(HB_MAIN),)
 HB_MAIN = std
endif

ROOT = ../../

PRG_SOURCES=\
	hbextern.prg \

PRG_MAIN=hbextern.prg

LIBS=\
	debug \
	vm \
	rtl \
	lang \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	dbfntx \
	dbfcdx \
	dbffpt \
	hbsix \
	common \

include $(TOP)$(ROOT)config/bin.cf
