#
# $Id$
#

ifeq ($(HB_MAIN),)
 HB_MAIN = std
endif

ROOT = ../../

PRG_SOURCES=\
        hbextern.prg \

PRG_MAIN=hbextern.prg

LIBS=\
        debug \
        vm \
        rtl \
        rdd \
        rtl \
        vm \
	macro \
        pp \
        runner \
        common \

include $(TOP)$(ROOT)config/bin.cf
