#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	hscript.prg \
	
PRG_MAIN=hscript.prg

LIBS=\
        tools \
        debug \
        vm \
        rtl \
        rdd \
        rtl \
        vm \
	macro \
        pp \
        runner \
        common \

include $(TOP)$(ROOT)config/bin.cf
