#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	hscript.prg \
	
PRG_MAIN=hscript.prg

LIBS=\
        runner \
	tools \
        debug \
	rdd \
	vm \
	rdd \
	rtl \
	pp \
	common \
	macro \

include $(TOP)$(ROOT)config/bin.cf
