
ROOT := ../../

C_SOURCES := \
   expropt1.c \
   expropt2.c \
   funcid.c \
   hbarch.c \
   hbdate.c \
   hbffind.c \
   hbfopen.c \
   hbfsapi.c \
   hbgete.c \
   hbhash.c \
   hbmem.c \
   hbprintf.c \
   hbstr.c \
   hbstrbm.c \
   hbtrace.c \
   hbver.c \
   hbverdsp.c \
   hbwin.c \
   hbwince.c \
   strwild.c \

LIBNAME := hbcommon

include $(TOP)$(ROOT)config/lib.mk
