#
# $Id$
#

ifeq ($(HB_ARCHITECTURE),w32)

ROOT = ../../../

C_SOURCES=\
	win32.c \

PRG_SOURCES=\
	button.prg \
	edit.prg \
	form.prg \
	menu.prg \
	menuitem.prg \
	winctrl.prg \

LIBNAME=hbgfw32

include $(TOP)$(ROOT)config/lib.cf

endif
