#
# $Id$
#

ROOT = ../../

C_SOURCES=\
	cdpgedos.c    \
	cdpla850.c    \
	cdppl852.c    \
	cdppliso.c    \
	cdpplmaz.c    \
	cdpru866.c    \
	cdprukoi.c    \
	cdpruwin.c
	
LIBNAME=codepage

include $(TOP)$(ROOT)config/lib.cf
