#
# $Id$
#

ROOT = ../../


C_SOURCES=\
	cpbg866.c     \
	cpbgiso.c     \
	cpbgwin.c     \
	cpeldos.c     \
	cpelwin.c     \
	cpesdos.c     \
	cpeswin.c     \
	cpesmwi.c     \
	cpfrdos.c     \
	cpgedos.c     \
	cpgewin.c     \
	cphr1250.c    \
	cphr437.c     \
	cphr852.c     \
	cphu852.c     \
	cphuiso.c     \
	cphuwin.c     \
	cpit437.c     \
	cpit850.c     \
	cpitisb.c     \
	cpitiso.c     \
	cpltwin.c     \
	cppl852.c     \
	cppliso.c     \
	cpplmaz.c     \
	cpplwin.c     \
	cppt850.c     \
	cpptiso.c     \
	cpru866.c     \
	cprukoi.c     \
	cpruwin.c     \
	cpsl437.c     \
	cpsl852.c     \
	cpsliso.c     \
	cpslwin.c     \
	cpsrwin.c     \
	cpua866.c     \
	cpuakoi.c     \
	cpuawin.c     \
	uc1250.c      \
	uc1251.c      \
	uc1253.c      \
	uc1257.c      \
	uc737.c       \
	uc850.c       \
	uc852.c       \
	uc866.c       \
	uc8859_1.c    \
	uc88591b.c    \
	uc8859_2.c    \
	uc8859_5.c    \
	uckoi8.c      \
	uckoi8u.c     \
	ucmaz.c       \

LIBNAME=codepage

include $(TOP)$(ROOT)config/lib.cf
