#
# $Id$
#

ROOT := ../../

LIBNAME := hbvpdf

PRG_SOURCES := \
   hbvpdf.prg \
   hbvpdft.prg \
   hbvpsup.prg \

PRG_HEADERS := \
   hbvpdf.ch \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
