#
# $Id: Makefile 4853 2001-12-25 16:51:58Z lculik $
#

ROOT = ../../

CFLAGS += -I/opt/firebird/include

C_SOURCES=\
        firebird.c \

PRG_SOURCES=\
        tfirebird.prg  \

LIBNAME=firebird

include $(TOP)$(ROOT)config/lib.cf
