#
# $Id$
#

ifeq ($(HB_MAIN),)
    HB_MAIN = std
endif

ROOT = ../../../

CONTRIBS=\
	firebird \

PRG_SOURCES=\
	simple.prg \

PRG_MAIN=\
	simple.prg

LIBS=\
	hbdebug \
	hbvm \
	hbrtl \
	hblang \
	hbrdd \
	hbrtl \
	hbvm \
	hbmacro \
	hbcommon \
	hbfbird \
	fbclient \

include $(TOP)$(ROOT)config/bin.cf
