#
# $Id$
#

ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

LIBNAME := hbtpathy

PRG_SOURCES := \
   telepath.prg \

PRG_HEADERS := \
   telepath.ch \

include $(TOP)$(ROOT)config/header.mk
include $(TOP)$(ROOT)config/lib.mk
