#
# $Id$
#

ROOT = ../../../

PRG_SOURCES=\
	hscript.prg \
	
PRG_MAIN=hscript.prg

LIBS=\
	debug \
	vm \
	rtl \
	lang \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	dbfntx \
	dbfcdx \
	dbffpt \
	hbsix \
	common \

include $(TOP)$(ROOT)config/bin.cf
