.TH HBPP 1

.SH NAME
hbpp \- Harbour Project Preprocessor

.SH SYNOPSIS
\fBhbpp\fP \fB<file[.prg]>\fP \fB[options]\fP

.SH DESCRIPTION
\fBhbpp\fP is the old Harbour Project preprocessor.

.SH OPTIONS
.IP "\fB-d<id>[=<val>]\fP" 10
#define <id>
.IP "\fB-i<path>\fP" 10
add #include file search path
.IP "\fB-o\fP" 10
creates hbpp.out with all tables
.IP "\fB-n\fP" 10
with those only, which defined in your file
.IP "\fB-w\fP" 10
enable warnings


.SH AUTHOR

Author of hbpp: The Harbour Project (http://harbour-project.org)

This manual page was written by Luis Mayoral <mayoral@linuxadicto.org>,
for the Debian GNU/Linux system (but may be used by others).
